--<ScriptOptions statementTerminator=";"/>

CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS"LICHT" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"ARTIKEL" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"ABBILDUNG" VARCHAR(255),
		"ANMERKUNG" VARCHAR(100),
		"ARTIKEL_ID" VARCHAR(6) NOT NULL,
		"BELADUNG" VARCHAR(100),
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"KAUFDATUM" DATE,
		"PREIS" DECIMAL(6 , 2),
		"STATUS" VARCHAR(255) NOT NULL,
		"STUCK" INTEGER NOT NULL,
		"VERBLEIBENDE" INTEGER NOT NULL,
		"DECODER_ID" BIGINT,
		"KUPPLUNG_ID" BIGINT,
		"LICHT_ID" BIGINT,
		"MOTOR_TYP_ID" BIGINT,
		"PRODUKT_ID" BIGINT NOT NULL,
		"STEUERUNG_ID" BIGINT,
		"WAHRUNG_ID" BIGINT
	);

CREATE TABLE IF NOT EXISTS"DECODER_TYP_FUNKTION" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100),
		"FUNKTION" VARCHAR(4),
		"PROGRAMMABLE" BOOLEAN NOT NULL,
		"REIHE" INTEGER NOT NULL,
		"DECODER_TYP_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"UNTER_KATEGORIE" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50),
		"KATEGORIE_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"LAND" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL,
		"WAHRUNG_ID" BIGINT
	);

CREATE TABLE IF NOT EXISTS"KATEGORIE" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"VORBILD" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"ABBILDUNG" VARCHAR(255),
		"ANFAHRZUGKRAFT" DECIMAL(19 , 2),
		"ANZAHL" INTEGER,
		"AUFBAU" VARCHAR(100),
		"AUSSERDIENST" DATE,
		"BAUZEIT" DATE,
		"BETREIBSNUMMER" VARCHAR(100),
		"BEZEICHNUNG" VARCHAR(100),
		"DIENSTGEWICHT" DECIMAL(19 , 2),
		"DM_LAUFRAD_HINTEN" DECIMAL(19 , 2),
		"DM_LAUFRAD_VORN" DECIMAL(19 , 2),
		"DM_TREIBRAD" DECIMAL(19 , 2),
		"DM_ZYLINDER" DECIMAL(19 , 2),
		"DREHGESTELL_BAUART" VARCHAR(100),
		"FAHRMOTOREN" INTEGER,
		"GESCHWINDIGKEIT" INTEGER,
		"HERSTELLER" VARCHAR(100),
		"KAPAZITAT" DECIMAL(19 , 2),
		"KESSELUBERDRUCK" DECIMAL(19 , 2),
		"KLASSE" INTEGER,
		"KOLBENHUB" DECIMAL(19 , 2),
		"LANGE" DECIMAL(19 , 2),
		"LEISTUNG" DECIMAL(19 , 2),
		"LEISTUNGSUBERTRAGUNG" VARCHAR(255),
		"MITTELWAGEN" INTEGER,
		"MOTORBAUART" VARCHAR(100),
		"REICHWEITE" DECIMAL(19 , 2),
		"ROSTFLACHE" DECIMAL(19 , 2),
		"SITZPLATZEKL1" INTEGER,
		"SITZPLATZEKL2" INTEGER,
		"SITZPLATZEKL3" INTEGER,
		"SITZPLATZEKL4" INTEGER,
		"TRIEBKOPF" INTEGER,
		"UBERHITZERFLACHE" DECIMAL(19 , 2),
		"VERDAMPFUNG" DECIMAL(19 , 2),
		"WASSERVORRAT" DECIMAL(19 , 2),
		"ZYLINDER" INTEGER,
		"ACHSFOLG_ID" BIGINT NOT NULL,
		"ANTRIEB_ID" BIGINT NOT NULL,
		"BAHNVERWALTUNG_ID" BIGINT NOT NULL,
		"GATTUNG_ID" BIGINT NOT NULL,
		"UNTER_KATEGORIE_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"MOTOR_TYP" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"BAHNVERWALTUNG" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"WAHRUNG" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL,
		"DEZIMAL" INTEGER
	);

CREATE TABLE IF NOT EXISTS"DECODER_CV" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"WERT" INTEGER,
		"CV_ID" BIGINT NOT NULL,
		"DECODER_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"ANDERUNG" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"ANDERUNG_ID" INTEGER NOT NULL,
		"ANDERUNGSDATUM" DATE,
		"ANDERUNGS_TYP" VARCHAR(255) NOT NULL,
		"ANMERKUNG" VARCHAR(255),
		"BEZEICHNUNG" VARCHAR(100),
		"STUCK" INTEGER,
		"ARTIKEL_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"ZUG_CONSIST" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"POSITION" INTEGER NOT NULL,
		"ARTIKEL_ID" BIGINT NOT NULL,
		"ZUG_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"GATTUNG" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"PRODUKT_TEIL" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"ANZAHL" INTEGER NOT NULL,
		"PRODUKT_ID" BIGINT NOT NULL,
		"TEIL_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"USER" (
		"ID" INTEGER NOT NULL,
		"CONFIRMATION_TOKEN" VARCHAR(255),
		"CREDENTIALS_EXPIRED" BOOLEAN,
		"EMAIL" VARCHAR(255) NOT NULL,
		"ENABLED" BOOLEAN,
		"EXPIRED" BOOLEAN,
		"FIRST_NAME" VARCHAR(255),
		"LAST_NAME" VARCHAR(255),
		"LOCKED" BOOLEAN,
		"RESET_TOKEN" VARCHAR(255)
	);

CREATE TABLE IF NOT EXISTS"ZUG" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL,
		"ZUG_TYP_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"KUPPLUNG" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"DECODER_ADRESS" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"ADRESS" INTEGER NOT NULL,
		"ADRESS_TYP" VARCHAR(10) NOT NULL,
		"INDEX" INTEGER NOT NULL,
		"DECODER_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"ZUG_TYP" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"AUFBAU" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"HERSTELLER" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL,
		"TELEFON" VARCHAR(20),
		"URL" VARCHAR(255)
	);

CREATE TABLE IF NOT EXISTS"ACHSFOLG" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"EPOCH" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"DECODER_TYP" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"ANLEITUNGEN" VARCHAR(512),
		"BESTELL_NR" VARCHAR(255),
		"BEZEICHNUNG" VARCHAR(100),
		"FAHRSTUFE" INTEGER,
		"I_MAX" DECIMAL(6 , 2),
		"KONFIGURATION" VARCHAR(15) NOT NULL,
		"SOUND" BOOLEAN NOT NULL,
		"STECKER" VARCHAR(10) NOT NULL,
		"HERSTELLER_ID" BIGINT NOT NULL,
		"PROTOKOLL_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"ANTRIEB" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"PROTOKOLL" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"STEUERUNG" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"DECODER_TYP_CV" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100),
		"CV" INTEGER NOT NULL,
		"MAXIMAL" INTEGER,
		"MINIMAL" INTEGER,
		"WERKSEINSTELLUNG" INTEGER,
		"DECODER_TYP_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"MASSSTAB" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"PRODUKT" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"ABBILDUNG" VARCHAR(255),
		"ANLEITUNGEN" VARCHAR(512),
		"ANMERKUNG" VARCHAR(100),
		"BAUZEIT" DATE,
		"BESTELL_NR" VARCHAR(255),
		"BETREIBSNUMMER" VARCHAR(100),
		"BEZEICHNUNG" VARCHAR(100),
		"EXPLOSIONSZEICHNUNG" VARCHAR(512),
		"LANGE" DECIMAL(6 , 2),
		"ACHSFOLG_ID" BIGINT,
		"AUFBAU_ID" BIGINT,
		"BAHNVERWALTUNG_ID" BIGINT,
		"DECODER_TYP_ID" BIGINT,
		"EPOCH_ID" BIGINT,
		"GATTUNG_ID" BIGINT,
		"HERSTELLER_ID" BIGINT NOT NULL,
		"KUPPLUNG_ID" BIGINT,
		"LICHT_ID" BIGINT,
		"MASSSTAB_ID" BIGINT NOT NULL,
		"MOTOR_TYP_ID" BIGINT,
		"SONDERMODELL_ID" BIGINT,
		"SPURWEITE_ID" BIGINT NOT NULL,
		"STEUERUNG_ID" BIGINT,
		"UNTER_KATEGORIE_ID" BIGINT NOT NULL,
		"VORBILD_ID" BIGINT
	);

CREATE TABLE IF NOT EXISTS"flyway_schema_history" (
		"installed_rank" INTEGER NOT NULL,
		"version" VARCHAR(50),
		"description" VARCHAR(200) NOT NULL,
		"type" VARCHAR(20) NOT NULL,
		"script" VARCHAR(1000) NOT NULL,
		"checksum" INTEGER,
		"installed_by" VARCHAR(100) NOT NULL,
		"installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
		"execution_time" INTEGER NOT NULL,
		"success" BOOLEAN NOT NULL
	);

CREATE TABLE IF NOT EXISTS"DECODER" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"DECODER_ID" VARCHAR(6) NOT NULL,
		"FAHRSTUFE" INTEGER,
		"STATUS" INTEGER,
		"DECODER_TYP_ID" BIGINT NOT NULL,
		"PROTOKOLL_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"USER_ROLES" (
		"USER_ID" INTEGER NOT NULL,
		"ROLES" VARCHAR(255)
	);

CREATE TABLE IF NOT EXISTS"DECODER_FUNKTION" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"DECODER_ID" BIGINT NOT NULL,
		"FUNKTION_ID" BIGINT NOT NULL
	);

CREATE TABLE IF NOT EXISTS"SPURWEITE" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"SONDER_MODELL" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"BEZEICHNUNG" VARCHAR(100) NOT NULL,
		"NAME" VARCHAR(50) NOT NULL
	);

CREATE TABLE IF NOT EXISTS"DECODER_TYP_ADRESS" (
		"ID" BIGINT NOT NULL,
		"DELETED" BOOLEAN NOT NULL,
		"WERKSEINSTELLUNG" INTEGER,
		"ADRESS_TYP" INTEGER NOT NULL,
		"INDEX" INTEGER NOT NULL,
		"SPAN" INTEGER NOT NULL,
		"DECODER_TYP_ID" BIGINT NOT NULL
	);

CREATE UNIQUE INDEX IF NOT EXISTS "ZUG_ID" ON "ZUG" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ZUG_TYP_NAME" ON "ZUG_TYP" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_CV_ID" ON "DECODER_CV" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "BAHNVERWALTUNG_NAME" ON "BAHNVERWALTUNG" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_ADRESS_DECODER_ID" ON "DECODER_ADRESS" ("DECODER_ID" ASC, "INDEX" ASC);

CREATE INDEX IF NOT EXISTS "ANDERUNG_ID" ON "ANDERUNG" ("ANDERUNG_ID" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_TYP_ID" ON "DECODER_TYP_CV" ("DECODER_TYP_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "HERSTELLER" ON "HERSTELLER" ("NAME" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_TYP_ID" ON "DECODER" ("DECODER_TYP_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "KATEGORIE" ON "KATEGORIE" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "KUPPLUNG_ID" ON "PRODUKT" ("KUPPLUNG_ID" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_ID" ON "DECODER_CV" ("DECODER_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "UNTER_KATEGORIE" ON "UNTER_KATEGORIE" ("KATEGORIE_ID" ASC, "NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_CV" ON "DECODER_CV" ("DECODER_ID" ASC, "CV_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ANDERUNG" ON "ANDERUNG" ("ARTIKEL_ID" ASC, "ANDERUNG_ID" ASC);

CREATE INDEX IF NOT EXISTS "LICHT_ID" ON "PRODUKT" ("LICHT_ID" ASC);

CREATE INDEX IF NOT EXISTS "AUFBAU_ID" ON "PRODUKT" ("AUFBAU_ID" ASC);

CREATE INDEX IF NOT EXISTS "MASSSTAB_ID" ON "PRODUKT" ("MASSSTAB_ID" ASC);

CREATE INDEX IF NOT EXISTS "VORBILD_FK3_INDEX_5" ON "VORBILD" ("BAHNVERWALTUNG_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ANTRIEB" ON "ANTRIEB" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "EPOCH" ON "EPOCH" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_FUNKTION" ON "DECODER_FUNKTION" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "GATTUNG" ON "GATTUNG" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("UNTER_KATEGORIE_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "WAHRUNG" ON "WAHRUNG" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ZUG_TYP" ON "ZUG_TYP" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_TYP" ON "DECODER_TYP" ("HERSTELLER_ID" ASC, "BESTELL_NR" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("BAHNVERWALTUNG_ID" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_TYP_ADRESS" ON "DECODER_TYP_ADRESS" ("INDEX" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("ACHSFOLG_ID" ASC);

CREATE INDEX IF NOT EXISTS "ANDERUNG" ON "ANDERUNG" ("ARTIKEL_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_TYP_FUNKTION" ON "DECODER_TYP_FUNKTION" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "DECODER" ON "DECODER" ("PROTOKOLL_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "EPOCH" ON "EPOCH" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("SPURWEITE_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "MASSSTAB" ON "MASSSTAB" ("NAME" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_FUNKTION" ON "DECODER_FUNKTION" ("DECODER_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "KUPPLUNG" ON "KUPPLUNG" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ZUG" ON "ZUG" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ACHSFOLG" ON "ACHSFOLG" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ZUG_CONSIST" ON "ZUG_CONSIST" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ANDERUNG" ON "ANDERUNG" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "ARTIKEL" ON "ARTIKEL" ("PRODUKT_ID" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_CV" ON "DECODER_CV" ("CV_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "LICHT" ON "LICHT" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "flyway_schema_history" ON "flyway_schema_history" ("installed_rank" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ARTIKEL" ON "ARTIKEL" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "flyway_schema_history_s_idx" ON "flyway_schema_history" ("success" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "PRIMARY_KEY_4" ON "LICHT" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "IDXFT8M7XN4JD8Y4W7MFINGR6LV4" ON "DECODER_TYP" ("HERSTELLER_ID" ASC);

CREATE INDEX IF NOT EXISTS "IDX5OWO2U1AUA8XO6NH12NL19O2B" ON "DECODER_TYP" ("PROTOKOLL_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "UKGU6B9KC6OWMMNNA28QA7R4X36_INDEX_7" ON "DECODER_TYP_FUNKTION" ("DECODER_TYP_ID" ASC, "REIHE" ASC, "FUNKTION" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "PRIMARY_KEY_6F" ON "PRODUKT_TEIL" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "IDX3S2YNWK09QSNSCDOYBQJR77T5" ON "PRODUKT" ("DECODER_TYP_ID" ASC);

CREATE INDEX IF NOT EXISTS "IDXK4AJTWG9F6KF3SMGM3LAAUWAV" ON "ZUG_CONSIST" ("ZUG_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "PRIMARY_KEY_A9" ON "SPURWEITE" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "GATTUNG" ON "GATTUNG" ("NAME" ASC);

CREATE INDEX IF NOT EXISTS "USER_ROLES" ON "USER_ROLES" ("USER_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_TYP_CV" ON "DECODER_TYP_CV" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_TYP_ADRESS" ON "DECODER_TYP_ADRESS" ("DECODER_TYP_ID" ASC, "INDEX" ASC);

CREATE INDEX IF NOT EXISTS "UNTER_KATEGORIE" ON "UNTER_KATEGORIE" ("KATEGORIE_ID" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_TYP_FUNKTION" ON "DECODER_TYP_FUNKTION" ("DECODER_TYP_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ZUG_CONSIST" ON "ZUG_CONSIST" ("ZUG_ID" ASC, "POSITION" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_ADRESS" ON "DECODER_ADRESS" ("DECODER_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "USER" ON "USER" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("VORBILD_ID" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT_TEIL" ON "PRODUKT_TEIL" ("TEIL_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_ADRESS" ON "DECODER_ADRESS" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "UNTER_KATEGORIE" ON "UNTER_KATEGORIE" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("HERSTELLER_ID" ASC, "BESTELL_NR" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "SONDER_MODELL" ON "SONDER_MODELL" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "SPURWEITE" ON "SPURWEITE" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "VORBILD" ON "VORBILD" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "ACHSFOLG_ID" ON "VORBILD" ("ACHSFOLG_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_FUNKTION" ON "DECODER_FUNKTION" ("DECODER_ID" ASC, "FUNKTION_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_TYP_CV" ON "DECODER_TYP_CV" ("DECODER_TYP_ID" ASC, "CV" ASC);

CREATE INDEX IF NOT EXISTS "ARTIKEL" ON "ARTIKEL" ("DECODER_ID" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("HERSTELLER_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "BAHNVERWALTUNG" ON "BAHNVERWALTUNG" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER" ON "DECODER" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER" ON "DECODER" ("DECODER_ID" ASC);

CREATE INDEX IF NOT EXISTS "LICHT_ID" ON "ARTIKEL" ("LICHT_ID" ASC);

CREATE INDEX IF NOT EXISTS "KUPPLUNG_ID" ON "ARTIKEL" ("KUPPLUNG_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "KATEGORIE" ON "KATEGORIE" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ACHSFOLG" ON "ACHSFOLG" ("NAME" ASC);

CREATE INDEX IF NOT EXISTS "ZUG_CONSIST" ON "ZUG_CONSIST" ("ARTIKEL_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "VORBILD" ON "WAHRUNG" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "VORBILD" ON "VORBILD" ("UNTER_KATEGORIE_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "LAND" ON "LAND" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("MOTOR_TYP_ID" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("SONDERMODELL_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "PRIMARY_KEY_82" ON "PROTOKOLL" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_TYP_ADRESS" ON "DECODER_TYP_ADRESS" ("DECODER_TYP_ID" ASC);

CREATE INDEX IF NOT EXISTS "LAND" ON "LAND" ("WAHRUNG_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_TYP" ON "DECODER_TYP" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "ZUG" ON "ZUG" ("ZUG_TYP_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ARTIKEL" ON "ARTIKEL" ("ARTIKEL_ID" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_TYP_CV" ON "DECODER_TYP_CV" ("CV" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "PROTOKOLL" ON "PROTOKOLL" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "HERSTELLER" ON "HERSTELLER" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("STEUERUNG_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "USER" ON "USER" ("EMAIL" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "AUFBAU" ON "AUFBAU" ("NAME" ASC);

CREATE INDEX IF NOT EXISTS "MOTOR_TYP_ID" ON "ARTIKEL" ("MOTOR_TYP_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "MOTOR_TYP" ON "MOTOR_TYP" ("NAME" ASC);

CREATE INDEX IF NOT EXISTS "DECODER_FUNKTION" ON "DECODER_FUNKTION" ("FUNKTION_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "AUFBAU" ON "AUFBAU" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "MOTOR_TYP" ON "MOTOR_TYP" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "KUPPLUNG" ON "KUPPLUNG" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "PRODUKT_TEIL" ON "PRODUKT_TEIL" ("PRODUKT_ID" ASC, "TEIL_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "VORBILD" ON "VORBILD" ("GATTUNG_ID" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("GATTUNG_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "STEUERUNG" ON "STEUERUNG" ("NAME" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("EPOCH_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "SONDER_MODELL" ON "SONDER_MODELL" ("NAME" ASC);

CREATE INDEX IF NOT EXISTS "ARTIKEL" ON "ARTIKEL" ("STEUERUNG_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "DECODER_TYP_ADRESS" ON "DECODER_TYP_ADRESS" ("ID" ASC);

CREATE INDEX IF NOT EXISTS "VORBILD" ON "VORBILD" ("ANTRIEB_ID" ASC);

CREATE INDEX IF NOT EXISTS "ARTIKEL" ON "ARTIKEL" ("WAHRUNG_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "ANTRIEB" ON "ANTRIEB" ("NAME" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "PRODUKT" ON "PRODUKT" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "MASSSTAB" ON "MASSSTAB" ("ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "LAND" ON "LAND" ("NAME" ASC);

CREATE INDEX IF NOT EXISTS "PRODUKT_TEIL_" ON "PRODUKT_TEIL" ("PRODUKT_ID" ASC);

CREATE UNIQUE INDEX IF NOT EXISTS "STEUERUNG_ID" ON "STEUERUNG" ("ID" ASC);

ALTER TABLE IF EXISTS "DECODER_TYP" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_C8" UNIQUE ("ID");

ALTER TABLE IF EXISTS "GATTUNG" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_1" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "MASSSTAB" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_3F" UNIQUE ("ID");

ALTER TABLE IF EXISTS "SONDER_MODELL" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_5" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "KUPPLUNG" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_8C" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "STEUERUNG" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_FF1" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "DECODER_TYP_CV" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_C2" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "USER" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_27" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "ZUG_CONSIST" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_83" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "KUPPLUNG" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_8C" UNIQUE ("ID");

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_18" UNIQUE ("ID");

ALTER TABLE IF EXISTS "ZUG_TYP" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_2E" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_18" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "UNTER_KATEGORIE" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_FB" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "DECODER" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_8" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "KATEGORIE" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_A5" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "HERSTELLER" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_A" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "DECODER_TYP" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_C8" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "ARTIKEL" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_FF" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "ANDERUNG" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_F" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "STEUERUNG" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_FF1" UNIQUE ("ID");

ALTER TABLE IF EXISTS "ZUG" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_15" UNIQUE ("ID");

ALTER TABLE IF EXISTS "LAND" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_2" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "KATEGORIE" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_A5" UNIQUE ("ID");

ALTER TABLE IF EXISTS "DECODER_ADRESS" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_72" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "ANTRIEB" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_F8" UNIQUE ("ID");

ALTER TABLE IF EXISTS "SPURWEITE" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_A9" UNIQUE ("ID");

ALTER TABLE IF EXISTS "DECODER_TYP_FUNKTION" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_729" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "VORBILD" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_50" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "PROTOKOLL" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_82" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "ANTRIEB" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_F8" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "PRODUKT_TEIL" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_6" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "DECODER_TYP_CV" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_C2" UNIQUE ("ID");

ALTER TABLE IF EXISTS "DECODER_FUNKTION" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_CD" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "HERSTELLER" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_A" UNIQUE ("ID");

ALTER TABLE IF EXISTS "BAHNVERWALTUNG" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_C" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "MASSSTAB" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_3F" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "ARTIKEL" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_FF" UNIQUE ("ID");

ALTER TABLE IF EXISTS "DECODER_CV" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_D" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "UNTER_KATEGORIE" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_FB" UNIQUE ("ID");

ALTER TABLE IF EXISTS "WAHRUNG" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_6D" UNIQUE ("ID");

ALTER TABLE IF EXISTS "ZUG_TYP" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_2E" UNIQUE ("ID");

ALTER TABLE IF EXISTS "SPURWEITE" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_A9" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "LICHT" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_4" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "EPOCH" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_3" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "PROTOKOLL" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_82" UNIQUE ("ID");

ALTER TABLE IF EXISTS "WAHRUNG" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_6D" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "SONDER_MODELL" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_5" UNIQUE ("ID");

ALTER TABLE IF EXISTS "ACHSFOLG" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_B" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "DECODER_TYP_FUNKTION" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_729" UNIQUE ("ID");

ALTER TABLE IF EXISTS "ZUG" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_15" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "VORBILD" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_50" UNIQUE ("ID");

ALTER TABLE IF EXISTS "USER" ADD CONSTRAINT IF NOT EXISTS "PRIMARY_KEY_27" UNIQUE ("ID");

ALTER TABLE IF EXISTS "AUFBAU" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_7" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "BAHNVERWALTUNG" ADD CONSTRAINT IF NOT EXISTS "BAHNVERWALTUNG_PK" UNIQUE ("ID");

ALTER TABLE IF EXISTS "DECODER_TYP_ADRESS" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_F6" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "flyway_schema_history" ADD CONSTRAINT IF NOT EXISTS "flyway_schema_history_pk" PRIMARY KEY ("installed_rank");

ALTER TABLE IF EXISTS "MOTOR_TYP" ADD CONSTRAINT IF NOT EXISTS "MOTOR_TYP_PK" UNIQUE ("ID");

ALTER TABLE IF EXISTS "MOTOR_TYP" ADD CONSTRAINT IF NOT EXISTS "CONSTRAINT_8E" PRIMARY KEY ("ID");

ALTER TABLE IF EXISTS "ACHSFOLG" ADD CONSTRAINT IF NOT EXISTS "ACHSFOLG_PK" UNIQUE ("ID");

ALTER TABLE IF EXISTS "EPOCH" ADD CONSTRAINT IF NOT EXISTS "EPOCH_PK" UNIQUE ("ID");

ALTER TABLE IF EXISTS "GATTUNG" ADD CONSTRAINT IF NOT EXISTS "GATTUNG_PK" UNIQUE ("ID");

ALTER TABLE IF EXISTS "AUFBAU" ADD CONSTRAINT IF NOT EXISTS "AUFBAU_PK" UNIQUE ("ID");

ALTER TABLE IF EXISTS "DECODER" ADD CONSTRAINT IF NOT EXISTS "DECODER_PK" UNIQUE ("ID");

ALTER TABLE IF EXISTS "LICHT" ADD CONSTRAINT IF NOT EXISTS "LICHT_PK" UNIQUE ("ID");

ALTER TABLE IF EXISTS "ARTIKEL" ADD CONSTRAINT IF NOT EXISTS "ARTIKEL_FK3" FOREIGN KEY ("STEUERUNG_ID")
	REFERENCES "STEUERUNG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK10" FOREIGN KEY ("LICHT_ID")
	REFERENCES "LICHT" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "ARTIKEL" ADD CONSTRAINT IF NOT EXISTS "ARTIKEL_FK5" FOREIGN KEY ("LICHT_ID")
	REFERENCES "LICHT" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "VORBILD" ADD CONSTRAINT IF NOT EXISTS "VORBILD_FK3" FOREIGN KEY ("BAHNVERWALTUNG_ID")
	REFERENCES "BAHNVERWALTUNG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER_TYP_ADRESS" ADD CONSTRAINT IF NOT EXISTS "DECODERTYPADRESS_FK1" FOREIGN KEY ("DECODER_TYP_ID")
	REFERENCES "DECODER_TYP" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK5" FOREIGN KEY ("MASSSTAB_ID")
	REFERENCES "MASSSTAB" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER_CV" ADD CONSTRAINT IF NOT EXISTS "DECODERCV_FK2" FOREIGN KEY ("CV_ID")
	REFERENCES "DECODER_TYP_CV" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "USER_ROLES" ADD CONSTRAINT IF NOT EXISTS "USER_ROLES_FK1" FOREIGN KEY ("USER_ID")
	REFERENCES "USER" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK12" FOREIGN KEY ("VORBILD_ID")
	REFERENCES "VORBILD" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK4" FOREIGN KEY ("ACHSFOLG_ID")
	REFERENCES "ACHSFOLG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK6" FOREIGN KEY ("SPURWEITE_ID")
	REFERENCES "SPURWEITE" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "VORBILD" ADD CONSTRAINT IF NOT EXISTS "VORBILD_FK5" FOREIGN KEY ("ACHSFOLG_ID")
	REFERENCES "ACHSFOLG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "ARTIKEL" ADD CONSTRAINT IF NOT EXISTS "ARTIKEL_FK7" FOREIGN KEY ("DECODER_ID")
	REFERENCES "DECODER" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "UNTER_KATEGORIE" ADD CONSTRAINT IF NOT EXISTS "UNTERKATEGORIE_FK1" FOREIGN KEY ("KATEGORIE_ID")
	REFERENCES "KATEGORIE" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "ZUG_CONSIST" ADD CONSTRAINT IF NOT EXISTS "ZUGCONSIST_FK1" FOREIGN KEY ("ZUG_ID")
	REFERENCES "ZUG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "ARTIKEL" ADD CONSTRAINT IF NOT EXISTS "ARTIKEL_FK2" FOREIGN KEY ("WAHRUNG_ID")
	REFERENCES "WAHRUNG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK13" FOREIGN KEY ("STEUERUNG_ID")
	REFERENCES "STEUERUNG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "ZUG_CONSIST" ADD CONSTRAINT IF NOT EXISTS "ZUGCONSIST_FK2" FOREIGN KEY ("ARTIKEL_ID")
	REFERENCES "ARTIKEL" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK15" FOREIGN KEY ("MOTOR_TYP_ID")
	REFERENCES "MOTOR_TYP" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "ARTIKEL" ADD CONSTRAINT IF NOT EXISTS "ARTIKEL_FK6" FOREIGN KEY ("KUPPLUNG_ID")
	REFERENCES "KUPPLUNG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "ARTIKEL" ADD CONSTRAINT IF NOT EXISTS "ARTIKEL_FK4" FOREIGN KEY ("MOTOR_TYP_ID")
	REFERENCES "MOTOR_TYP" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK2" FOREIGN KEY ("GATTUNG_ID")
	REFERENCES "GATTUNG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT_TEIL" ADD CONSTRAINT IF NOT EXISTS "PRODUKTTEIL_FK2" FOREIGN KEY ("TEIL_ID")
	REFERENCES "PRODUKT" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER_FUNKTION" ADD CONSTRAINT IF NOT EXISTS "DECODERFUNKTION_FK2" FOREIGN KEY ("FUNKTION_ID")
	REFERENCES "DECODER_TYP_FUNKTION" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "VORBILD" ADD CONSTRAINT IF NOT EXISTS "VORBILD_FK2" FOREIGN KEY ("UNTER_KATEGORIE_ID")
	REFERENCES "UNTER_KATEGORIE" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "VORBILD" ADD CONSTRAINT IF NOT EXISTS "VORBILD_FK4" FOREIGN KEY ("ANTRIEB_ID")
	REFERENCES "ANTRIEB" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "ANDERUNG" ADD CONSTRAINT IF NOT EXISTS "ANDERUNG_FK1" FOREIGN KEY ("ARTIKEL_ID")
	REFERENCES "ARTIKEL" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT_TEIL" ADD CONSTRAINT IF NOT EXISTS "PRODUKTTEIL_FK1" FOREIGN KEY ("PRODUKT_ID")
	REFERENCES "PRODUKT" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER_TYP" ADD CONSTRAINT IF NOT EXISTS "DECODERTYP_FK2" FOREIGN KEY ("HERSTELLER_ID")
	REFERENCES "HERSTELLER" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK7" FOREIGN KEY ("UNTER_KATEGORIE_ID")
	REFERENCES "UNTER_KATEGORIE" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "ZUG" ADD CONSTRAINT IF NOT EXISTS "ZUG_FK1" FOREIGN KEY ("ZUG_TYP_ID")
	REFERENCES "ZUG_TYP" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK11" FOREIGN KEY ("KUPPLUNG_ID")
	REFERENCES "KUPPLUNG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "LAND" ADD CONSTRAINT IF NOT EXISTS "FKD7C3AGPRCPARNMED569N76EIV" FOREIGN KEY ("WAHRUNG_ID")
	REFERENCES "WAHRUNG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "VORBILD" ADD CONSTRAINT IF NOT EXISTS "VORBILD_FK1" FOREIGN KEY ("GATTUNG_ID")
	REFERENCES "GATTUNG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER" ADD CONSTRAINT IF NOT EXISTS "DECODER_FK2" FOREIGN KEY ("PROTOKOLL_ID")
	REFERENCES "PROTOKOLL" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER_ADRESS" ADD CONSTRAINT IF NOT EXISTS "DECODERADRESS_FK1" FOREIGN KEY ("DECODER_ID")
	REFERENCES "DECODER" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER" ADD CONSTRAINT IF NOT EXISTS "DECODER_FK1" FOREIGN KEY ("DECODER_TYP_ID")
	REFERENCES "DECODER_TYP" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK1" FOREIGN KEY ("EPOCH_ID")
	REFERENCES "EPOCH" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER_TYP_FUNKTION" ADD CONSTRAINT IF NOT EXISTS "DECODERTYPFUNKTION_FK1" FOREIGN KEY ("DECODER_TYP_ID")
	REFERENCES "DECODER_TYP" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK3" FOREIGN KEY ("BAHNVERWALTUNG_ID")
	REFERENCES "BAHNVERWALTUNG" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER_CV" ADD CONSTRAINT IF NOT EXISTS "DECODERCV_FK1" FOREIGN KEY ("DECODER_ID")
	REFERENCES "DECODER" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER_FUNKTION" ADD CONSTRAINT IF NOT EXISTS "DECODERFUNKTION_FK1" FOREIGN KEY ("DECODER_ID")
	REFERENCES "DECODER" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER_TYP" ADD CONSTRAINT IF NOT EXISTS "DECODERTYP_FK3" FOREIGN KEY ("PROTOKOLL_ID")
	REFERENCES "PROTOKOLL" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK16" FOREIGN KEY ("HERSTELLER_ID")
	REFERENCES "HERSTELLER" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK14" FOREIGN KEY ("DECODER_TYP_ID")
	REFERENCES "DECODER_TYP" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "DECODER_TYP_CV" ADD CONSTRAINT IF NOT EXISTS "DECODERTYP_CV_FK1" FOREIGN KEY ("DECODER_TYP_ID")
	REFERENCES "DECODER_TYP" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK9" FOREIGN KEY ("AUFBAU_ID")
	REFERENCES "AUFBAU" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "ARTIKEL" ADD CONSTRAINT IF NOT EXISTS "ARTIKEL_FK1" FOREIGN KEY ("PRODUKT_ID")
	REFERENCES "PRODUKT" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE IF EXISTS "PRODUKT" ADD CONSTRAINT IF NOT EXISTS "PRODUKT_FK8" FOREIGN KEY ("SONDERMODELL_ID")
	REFERENCES "SONDER_MODELL" ("ID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

