--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "ARTIKEL" DROP CONSTRAINT "ARTIKEL_FK3" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK10" IF EXISTS;

ALTER TABLE "ARTIKEL" DROP CONSTRAINT "ARTIKEL_FK5" IF EXISTS;

ALTER TABLE "VORBILD" DROP CONSTRAINT "VORBILD_FK3" IF EXISTS;

ALTER TABLE "DECODER_TYP_ADRESS" DROP CONSTRAINT "DECODERTYPADRESS_FK1" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK5" IF EXISTS;

ALTER TABLE "DECODER_CV" DROP CONSTRAINT "DECODERCV_FK2" IF EXISTS;

ALTER TABLE "USER_ROLES" DROP CONSTRAINT "FK55ITPPKW3I07DO3H7QOCLQD4K" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK12" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK4" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK6" IF EXISTS;

ALTER TABLE "VORBILD" DROP CONSTRAINT "VORBILD_FK5" IF EXISTS;

ALTER TABLE "ARTIKEL" DROP CONSTRAINT "ARTIKEL_FK7" IF EXISTS;

ALTER TABLE "UNTER_KATEGORIE" DROP CONSTRAINT "UNTERKATEGORIE_FK1" IF EXISTS;

ALTER TABLE "ZUG_CONSIST" DROP CONSTRAINT "ZUGCONSIST_FK1" IF EXISTS;

ALTER TABLE "ARTIKEL" DROP CONSTRAINT "ARTIKEL_FK2" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK13" IF EXISTS;

ALTER TABLE "ZUG_CONSIST" DROP CONSTRAINT "ZUGCONSIST_FK2" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK15" IF EXISTS;

ALTER TABLE "ARTIKEL" DROP CONSTRAINT "ARTIKEL_FK6" IF EXISTS;

ALTER TABLE "ARTIKEL" DROP CONSTRAINT "ARTIKEL_FK4" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK2" IF EXISTS;

ALTER TABLE "PRODUKT_TEIL" DROP CONSTRAINT "PRODUKTTEIL_FK2" IF EXISTS;

ALTER TABLE "DECODER_FUNKTION" DROP CONSTRAINT "DECODERFUNKTION_FK2" IF EXISTS;

ALTER TABLE "VORBILD" DROP CONSTRAINT "VORBILD_FK2" IF EXISTS;

ALTER TABLE "VORBILD" DROP CONSTRAINT "VORBILD_FK4" IF EXISTS;

ALTER TABLE "ANDERUNG" DROP CONSTRAINT "ANDERUNG_FK1" IF EXISTS;

ALTER TABLE "PRODUKT_TEIL" DROP CONSTRAINT "PRODUKTTEIL_FK1" IF EXISTS;

ALTER TABLE "DECODER_TYP" DROP CONSTRAINT "DECODERTYP_FK2" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK7" IF EXISTS;

ALTER TABLE "ZUG" DROP CONSTRAINT "ZUG_FK1" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK11" IF EXISTS;

ALTER TABLE "LAND" DROP CONSTRAINT "FKD7C3AGPRCPARNMED569N76EIV" IF EXISTS;

ALTER TABLE "VORBILD" DROP CONSTRAINT "VORBILD_FK1" IF EXISTS;

ALTER TABLE "DECODER" DROP CONSTRAINT "DECODER_FK2" IF EXISTS;

ALTER TABLE "DECODER_ADRESS" DROP CONSTRAINT "DECODERADRESS_FK1" IF EXISTS;

ALTER TABLE "DECODER" DROP CONSTRAINT "DECODER_FK1" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK1" IF EXISTS;

ALTER TABLE "DECODER_TYP_FUNKTION" DROP CONSTRAINT "DECODERTYPFUNKTION_FK1" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK3" IF EXISTS;

ALTER TABLE "DECODER_CV" DROP CONSTRAINT "DECODERCV_FK1" IF EXISTS;

ALTER TABLE "DECODER_FUNKTION" DROP CONSTRAINT "DECODERFUNKTION_FK1" IF EXISTS;

ALTER TABLE "DECODER_TYP" DROP CONSTRAINT "DECODERTYP_FK3" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK16" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK14" IF EXISTS;

ALTER TABLE "DECODER_TYP_CV" DROP CONSTRAINT "DECODERTYPCV_FK1" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK9" IF EXISTS;

ALTER TABLE "ARTIKEL" DROP CONSTRAINT "ARTIKEL_FK1" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRODUKT_FK8" IF EXISTS;

ALTER TABLE "DECODER_TYP" DROP CONSTRAINT "PRIMARY_KEY_C8" IF EXISTS;

ALTER TABLE "GATTUNG" DROP CONSTRAINT "CONSTRAINT_1" IF EXISTS;

ALTER TABLE "MASSSTAB" DROP CONSTRAINT "PRIMARY_KEY_3F" IF EXISTS;

ALTER TABLE "SONDER_MODELL" DROP CONSTRAINT "CONSTRAINT_5" IF EXISTS;

ALTER TABLE "KUPPLUNG" DROP CONSTRAINT "CONSTRAINT_8C" IF EXISTS;

ALTER TABLE "STEUERUNG" DROP CONSTRAINT "CONSTRAINT_FF1" IF EXISTS;

ALTER TABLE "DECODER_TYP_CV" DROP CONSTRAINT "CONSTRAINT_C2" IF EXISTS;

ALTER TABLE "USER" DROP CONSTRAINT "CONSTRAINT_27" IF EXISTS;

ALTER TABLE "ZUG_CONSIST" DROP CONSTRAINT "CONSTRAINT_83" IF EXISTS;

ALTER TABLE "KUPPLUNG" DROP CONSTRAINT "PRIMARY_KEY_8C" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "PRIMARY_KEY_18" IF EXISTS;

ALTER TABLE "ZUG_TYP" DROP CONSTRAINT "CONSTRAINT_2E" IF EXISTS;

ALTER TABLE "PRODUKT" DROP CONSTRAINT "CONSTRAINT_18" IF EXISTS;

ALTER TABLE "UNTER_KATEGORIE" DROP CONSTRAINT "CONSTRAINT_FB" IF EXISTS;

ALTER TABLE "DECODER" DROP CONSTRAINT "CONSTRAINT_8" IF EXISTS;

ALTER TABLE "KATEGORIE" DROP CONSTRAINT "CONSTRAINT_A5" IF EXISTS;

ALTER TABLE "HERSTELLER" DROP CONSTRAINT "CONSTRAINT_A" IF EXISTS;

ALTER TABLE "DECODER_TYP" DROP CONSTRAINT "CONSTRAINT_C8" IF EXISTS;

ALTER TABLE "ARTIKEL" DROP CONSTRAINT "CONSTRAINT_FF" IF EXISTS;

ALTER TABLE "ANDERUNG" DROP CONSTRAINT "CONSTRAINT_F" IF EXISTS;

ALTER TABLE "STEUERUNG" DROP CONSTRAINT "PRIMARY_KEY_FF1" IF EXISTS;

ALTER TABLE "ZUG" DROP CONSTRAINT "PRIMARY_KEY_15" IF EXISTS;

ALTER TABLE "LAND" DROP CONSTRAINT "CONSTRAINT_2" IF EXISTS;

ALTER TABLE "KATEGORIE" DROP CONSTRAINT "PRIMARY_KEY_A5" IF EXISTS;

ALTER TABLE "DECODER_ADRESS" DROP CONSTRAINT "CONSTRAINT_72" IF EXISTS;

ALTER TABLE "ANTRIEB" DROP CONSTRAINT "PRIMARY_KEY_F8" IF EXISTS;

ALTER TABLE "SPURWEITE" DROP CONSTRAINT "PRIMARY_KEY_A9" IF EXISTS;

ALTER TABLE "DECODER_TYP_FUNKTION" DROP CONSTRAINT "CONSTRAINT_729" IF EXISTS;

ALTER TABLE "VORBILD" DROP CONSTRAINT "CONSTRAINT_50" IF EXISTS;

ALTER TABLE "PROTOKOLL" DROP CONSTRAINT "CONSTRAINT_82" IF EXISTS;

ALTER TABLE "ANTRIEB" DROP CONSTRAINT "CONSTRAINT_F8" IF EXISTS;

ALTER TABLE "PRODUKT_TEIL" DROP CONSTRAINT "CONSTRAINT_6" IF EXISTS;

ALTER TABLE "DECODER_TYP_CV" DROP CONSTRAINT "PRIMARY_KEY_C2" IF EXISTS;

ALTER TABLE "DECODER_FUNKTION" DROP CONSTRAINT "CONSTRAINT_CD" IF EXISTS;

ALTER TABLE "HERSTELLER" DROP CONSTRAINT "PRIMARY_KEY_A" IF EXISTS;

ALTER TABLE "BAHNVERWALTUNG" DROP CONSTRAINT "CONSTRAINT_C" IF EXISTS;

ALTER TABLE "MASSSTAB" DROP CONSTRAINT "CONSTRAINT_3F" IF EXISTS;

ALTER TABLE "ARTIKEL" DROP CONSTRAINT "PRIMARY_KEY_FF" IF EXISTS;

ALTER TABLE "DECODER_CV" DROP CONSTRAINT "CONSTRAINT_D" IF EXISTS;

ALTER TABLE "UNTER_KATEGORIE" DROP CONSTRAINT "PRIMARY_KEY_FB" IF EXISTS;

ALTER TABLE "WAHRUNG" DROP CONSTRAINT "PRIMARY_KEY_6D" IF EXISTS;

ALTER TABLE "ZUG_TYP" DROP CONSTRAINT "PRIMARY_KEY_2E" IF EXISTS;

ALTER TABLE "SPURWEITE" DROP CONSTRAINT "CONSTRAINT_A9" IF EXISTS;

ALTER TABLE "LICHT" DROP CONSTRAINT "CONSTRAINT_4" IF EXISTS;

ALTER TABLE "EPOCH" DROP CONSTRAINT "CONSTRAINT_3" IF EXISTS;

ALTER TABLE "PROTOKOLL" DROP CONSTRAINT "PRIMARY_KEY_82" IF EXISTS;

ALTER TABLE "WAHRUNG" DROP CONSTRAINT "CONSTRAINT_6D" IF EXISTS;

ALTER TABLE "SONDER_MODELL" DROP CONSTRAINT "PRIMARY_KEY_5" IF EXISTS;

ALTER TABLE "ACHSFOLG" DROP CONSTRAINT "CONSTRAINT_B" IF EXISTS;

ALTER TABLE "DECODER_TYP_FUNKTION" DROP CONSTRAINT "PRIMARY_KEY_729" IF EXISTS;

ALTER TABLE "ZUG" DROP CONSTRAINT "CONSTRAINT_15" IF EXISTS;

ALTER TABLE "VORBILD" DROP CONSTRAINT "PRIMARY_KEY_50" IF EXISTS;

ALTER TABLE "USER" DROP CONSTRAINT "PRIMARY_KEY_27" IF EXISTS;

ALTER TABLE "AUFBAU" DROP CONSTRAINT "CONSTRAINT_7" IF EXISTS;

ALTER TABLE "BAHNVERWALTUNG" DROP CONSTRAINT "PRIMARY_KEY_C" IF EXISTS;

ALTER TABLE "DECODER_TYP_ADRESS" DROP CONSTRAINT "CONSTRAINT_F6" IF EXISTS;

ALTER TABLE "flyway_schema_history" DROP CONSTRAINT "flyway_schema_history_pk" IF EXISTS;

ALTER TABLE "MOTOR_TYP" DROP CONSTRAINT "PRIMARY_KEY_8E" IF EXISTS;

ALTER TABLE "MOTOR_TYP" DROP CONSTRAINT "CONSTRAINT_8E" IF EXISTS;

ALTER TABLE "ACHSFOLG" DROP CONSTRAINT "PRIMARY_KEY_B" IF EXISTS;

ALTER TABLE "EPOCH" DROP CONSTRAINT "PRIMARY_KEY_3" IF EXISTS;

ALTER TABLE "GATTUNG" DROP CONSTRAINT "PRIMARY_KEY_1" IF EXISTS;

ALTER TABLE "AUFBAU" DROP CONSTRAINT "PRIMARY_KEY_7" IF EXISTS;

ALTER TABLE "DECODER" DROP CONSTRAINT "PRIMARY_KEY_8" IF EXISTS;

ALTER TABLE "LICHT" DROP CONSTRAINT "PRIMARY_KEY_4" IF EXISTS;

DROP INDEX "PRIMARY_KEY_15" IF EXISTS;

DROP INDEX "UK_MBCHHJFUEGIF7BQUQ5J6TKAL3_INDEX_2" IF EXISTS;

DROP INDEX "PRIMARY_KEY_D" IF EXISTS;

DROP INDEX "UK_R4FFBFLR2V4QMWQJXY84D7NUA_INDEX_C" IF EXISTS;

DROP INDEX "UKCSL4AG7ODE2NBL3TT2O73SXTH_INDEX_7" IF EXISTS;

DROP INDEX "IDXAVAIX6W1R0WWQ6IMQUQYL6SAH" IF EXISTS;

DROP INDEX "IDXJM9YMIWBJ8JNQA49I0JXS2LM2" IF EXISTS;

DROP INDEX "UK_E58QJC2BD88UN3BJCRAW0NOVA_INDEX_A" IF EXISTS;

DROP INDEX "IDXNSO15A75JG4O124ULT2LO0G5S" IF EXISTS;

DROP INDEX "PRIMARY_KEY_A5" IF EXISTS;

DROP INDEX "IDX9B0KWKKABKD7M1I4CXUN6GY4O" IF EXISTS;

DROP INDEX "DECODERCV_FK1_INDEX_D" IF EXISTS;

DROP INDEX "UKDN41ME6GRVPVX2A7N5T26U3XS_INDEX_F" IF EXISTS;

DROP INDEX "UK9LS2B8KUQNBI1RYRIF8XLDB5D_INDEX_D" IF EXISTS;

DROP INDEX "UK6R7GJBVUBQ5HT1C7A2OJURYXF_INDEX_F" IF EXISTS;

DROP INDEX "IDX9QOR9GKVQ1AUV5HSHT899FB7D" IF EXISTS;

DROP INDEX "IDXSGFRJCH0B5MNSQS2Q4LBOGWWN" IF EXISTS;

DROP INDEX "IDX5USYC4UL99FMHOANUQVF464OK" IF EXISTS;

DROP INDEX "VORBILD_FK3_INDEX_5" IF EXISTS;

DROP INDEX "PRIMARY_KEY_F8" IF EXISTS;

DROP INDEX "UK_8G0TJPCECYX7PNU04FXBFVE4T_INDEX_3" IF EXISTS;

DROP INDEX "PRIMARY_KEY_CD" IF EXISTS;

DROP INDEX "PRIMARY_KEY_1" IF EXISTS;

DROP INDEX "IDX4D1KC5D3SUPK2B4MX767449XS" IF EXISTS;

DROP INDEX "UK_EUKGDBSRH32KNTT88WS56HWMK_INDEX_6" IF EXISTS;

DROP INDEX "PRIMARY_KEY_2E" IF EXISTS;

DROP INDEX "UKQ1OK2WSBSJ045QNBINLDT3CAA_INDEX_C" IF EXISTS;

DROP INDEX "IDXCFP37QL8M5TPG530HCB0PLQ00" IF EXISTS;

DROP INDEX "IDXBSS3B1Q78465F0CPR67BTQPFL" IF EXISTS;

DROP INDEX "IDXF47QQ0U21QQO7ARTMR7T3PQQM" IF EXISTS;

DROP INDEX "IDXMTW1IY4TKCTQEF980GN2JDWH4" IF EXISTS;

DROP INDEX "PRIMARY_KEY_729" IF EXISTS;

DROP INDEX "IDXGUVS26KGYOCCJW9QOH5BS2WKD" IF EXISTS;

DROP INDEX "PRIMARY_KEY_3" IF EXISTS;

DROP INDEX "IDX6H0469RO7MXMR08P6KGS72F2W" IF EXISTS;

DROP INDEX "UK_JLGPBHQY7S4L0RB348P7XL44E_INDEX_3" IF EXISTS;

DROP INDEX "DECODERFUNKTION_FK1_INDEX_C" IF EXISTS;

DROP INDEX "PRIMARY_KEY_8C" IF EXISTS;

DROP INDEX "UK_JDYFX82XKNXYAMXCUOQ9BFOMA_INDEX_1" IF EXISTS;

DROP INDEX "PRIMARY_KEY_B" IF EXISTS;

DROP INDEX "PRIMARY_KEY_83" IF EXISTS;

DROP INDEX "PRIMARY_KEY_F" IF EXISTS;

DROP INDEX "IDXOKQTDQFY3MFGEKLA9G207T260" IF EXISTS;

DROP INDEX "DECODERCV_FK2_INDEX_D" IF EXISTS;

DROP INDEX "UK_R4VR916URFVY092FNM2AEGEPE_INDEX_4" IF EXISTS;

DROP INDEX "PRIMARY_KEY_6" IF EXISTS;

DROP INDEX "PRIMARY_KEY_FF" IF EXISTS;

DROP INDEX "flyway_schema_history_s_idx" IF EXISTS;

DROP INDEX "PRIMARY_KEY_4" IF EXISTS;

DROP INDEX "IDXFT8M7XN4JD8Y4W7MFINGR6LV4" IF EXISTS;

DROP INDEX "IDX5OWO2U1AUA8XO6NH12NL19O2B" IF EXISTS;

DROP INDEX "UKGU6B9KC6OWMMNNA28QA7R4X36_INDEX_7" IF EXISTS;

DROP INDEX "PRIMARY_KEY_6F" IF EXISTS;

DROP INDEX "IDX3S2YNWK09QSNSCDOYBQJR77T5" IF EXISTS;

DROP INDEX "IDXK4AJTWG9F6KF3SMGM3LAAUWAV" IF EXISTS;

DROP INDEX "PRIMARY_KEY_A9" IF EXISTS;

DROP INDEX "UK_9KE2194X83UFBNAG389FC9AEG_INDEX_1" IF EXISTS;

DROP INDEX "FK55ITPPKW3I07DO3H7QOCLQD4K_INDEX_C" IF EXISTS;

DROP INDEX "PRIMARY_KEY_C2" IF EXISTS;

DROP INDEX "UKB7V9QJV8KTE8DIAY7BXD7Y2B1_INDEX_F" IF EXISTS;

DROP INDEX "IDX1CQG6G0TN7AX8C0FSOXO4LR5P" IF EXISTS;

DROP INDEX "IDX466FY7XLHJNG7QKQ7TT3Y2PGS" IF EXISTS;

DROP INDEX "UK6Q1RY1QG17HTAJ8Y8RQM2BXUX_INDEX_8" IF EXISTS;

DROP INDEX "DECODERADRESS_FK1_INDEX_7" IF EXISTS;

DROP INDEX "PRIMARY_KEY_27" IF EXISTS;

DROP INDEX "IDXET8HWM31V3GJL8HWDKJNL57SI" IF EXISTS;

DROP INDEX "IDX42TIP4TRGDH9Q3AG6Y981N5DM" IF EXISTS;

DROP INDEX "PRIMARY_KEY_72" IF EXISTS;

DROP INDEX "PRIMARY_KEY_FB" IF EXISTS;

DROP INDEX "UKM6WMHL0R2FIORTBPWLM57J79Y_INDEX_1" IF EXISTS;

DROP INDEX "PRIMARY_KEY_5" IF EXISTS;

DROP INDEX "UK_JL307IH43DRNQD394SE5YB52R_INDEX_A" IF EXISTS;

DROP INDEX "PRIMARY_KEY_50" IF EXISTS;

DROP INDEX "IDXSDWGF1GGV92CXFGUYJ8RQYIOW" IF EXISTS;

DROP INDEX "UKPUMYW3NR1U4XLVD0M1NADSO15_INDEX_C" IF EXISTS;

DROP INDEX "UKDXNBM0K02VE68T0PFAS2Q33AL_INDEX_C" IF EXISTS;

DROP INDEX "IDX22ER2TP295EAS75EXJVQTW213" IF EXISTS;

DROP INDEX "IDX12I1OBV4IKIGUX9LRF1Y2AEQV" IF EXISTS;

DROP INDEX "PRIMARY_KEY_C" IF EXISTS;

DROP INDEX "PRIMARY_KEY_8" IF EXISTS;

DROP INDEX "UK_ORDEVYWLK5437FT6BXP996JPE_INDEX_8" IF EXISTS;

DROP INDEX "IDXNRS3X28GGME3DF0GF5ISV2BU" IF EXISTS;

DROP INDEX "IDX60N1NWR9SYF40R17SISM0P75F" IF EXISTS;

DROP INDEX "UK_FGHH9XT5LBA3704OF5P0BOPG2_INDEX_A" IF EXISTS;

DROP INDEX "UK_FY8U67U46V5HPRXWGKQQWB9C3_INDEX_B" IF EXISTS;

DROP INDEX "IDXBKFP5LV7PUIT5VL836DGUACYR" IF EXISTS;

DROP INDEX "PRIMARY_KEY_6D" IF EXISTS;

DROP INDEX "IDXOTUYIDFQ5691BF5DWFV9OAWR" IF EXISTS;

DROP INDEX "PRIMARY_KEY_2" IF EXISTS;

DROP INDEX "IDXHFJHJ2RFI3TC81JVS0R6LS7ST" IF EXISTS;

DROP INDEX "IDXFHU4EVYYCLS1A1PNIX21SADAS" IF EXISTS;

DROP INDEX "PRIMARY_KEY_82" IF EXISTS;

DROP INDEX "IDXA3XBFBA9RQ4NW1K629IXDM5R9" IF EXISTS;

DROP INDEX "FKD7C3AGPRCPARNMED569N76EIV_INDEX_2" IF EXISTS;

DROP INDEX "PRIMARY_KEY_C8" IF EXISTS;

DROP INDEX "IDXMM97SRJSKIV22U3RLWTR86YDP" IF EXISTS;

DROP INDEX "UK_PI24NCTFCDA9UWT8I8P8J7388_INDEX_F" IF EXISTS;

DROP INDEX "IDXQH6XLOI9C6SF9KQIKUEEYQ3BK" IF EXISTS;

DROP INDEX "UK_PXSAO93KTNQOOB2U03NDNBMEC_INDEX_8" IF EXISTS;

DROP INDEX "PRIMARY_KEY_A" IF EXISTS;

DROP INDEX "IDXFTPFHTWYC1QFKQ9F1F2NA8D0W" IF EXISTS;

DROP INDEX "UK_OB8KQYQQGMEFL0ACO34AKDTPE_INDEX_2" IF EXISTS;

DROP INDEX "UK_Q500PA6UM871VYFR0HGWAPU2Q_INDEX_7" IF EXISTS;

DROP INDEX "IDXPICWNCS1WM83Q896LEINBY9HX" IF EXISTS;

DROP INDEX "UK_N66IG0OYOMQ45JCL34LUBVILY_INDEX_8" IF EXISTS;

DROP INDEX "DECODERFUNKTION_FK2_INDEX_C" IF EXISTS;

DROP INDEX "PRIMARY_KEY_7" IF EXISTS;

DROP INDEX "PRIMARY_KEY_8E" IF EXISTS;

DROP INDEX "UK_RJYSOLH7ON8XHRLII99I9X9XK_INDEX_8" IF EXISTS;

DROP INDEX "UKBQOVUQVFQRPYKG7C6PRRVNMK2_INDEX_6" IF EXISTS;

DROP INDEX "UKBYXLJKR4MDSM3ABKKA6COS9C_INDEX_5" IF EXISTS;

DROP INDEX "IDXHV6HMP04PCUJR2IVR68PVRHUU" IF EXISTS;

DROP INDEX "UK_5U32DDL5AEF15B8B1YSDNX9M6_INDEX_F" IF EXISTS;

DROP INDEX "IDX8YYOIQPTKUIY6L26NT3GFMW00" IF EXISTS;

DROP INDEX "UK_IXSD3RJL6DQ24DW9F50XLMFAF_INDEX_5" IF EXISTS;

DROP INDEX "IDXJ127QDAW1004AGOVBVS54WI3I" IF EXISTS;

DROP INDEX "PRIMARY_KEY_F6" IF EXISTS;

DROP INDEX "IDXTIX27OR32TH3N2HA2V21YUDOL" IF EXISTS;

DROP INDEX "IDXLAM6THWQ8BGKXL5E517NTXS5V" IF EXISTS;

DROP INDEX "UK_5AXPTMX387UMYA26EGWT76CH0_INDEX_F" IF EXISTS;

DROP INDEX "PRIMARY_KEY_18" IF EXISTS;

DROP INDEX "PRIMARY_KEY_3F" IF EXISTS;

DROP INDEX "UK_74UP4CVT5VIMFY09M7OVFMXIF_INDEX_2" IF EXISTS;

DROP INDEX "IDX6Y603UN8L4T01GDO7B2DHRSOC" IF EXISTS;

DROP INDEX "PRIMARY_KEY_FF1" IF EXISTS;

DROP TABLE "LICHT" IF EXISTS;

DROP TABLE "ARTIKEL" IF EXISTS;

DROP TABLE "DECODER_TYP_FUNKTION" IF EXISTS;

DROP TABLE "UNTER_KATEGORIE" IF EXISTS;

DROP TABLE "LAND" IF EXISTS;

DROP TABLE "KATEGORIE" IF EXISTS;

DROP TABLE "VORBILD" IF EXISTS;

DROP TABLE "MOTOR_TYP" IF EXISTS;

DROP TABLE "BAHNVERWALTUNG" IF EXISTS;

DROP TABLE "WAHRUNG" IF EXISTS;

DROP TABLE "DECODER_CV" IF EXISTS;

DROP TABLE "ANDERUNG" IF EXISTS;

DROP TABLE "ZUG_CONSIST" IF EXISTS;

DROP TABLE "GATTUNG" IF EXISTS;

DROP TABLE "PRODUKT_TEIL" IF EXISTS;

DROP TABLE "USER" IF EXISTS;

DROP TABLE "ZUG" IF EXISTS;

DROP TABLE "KUPPLUNG" IF EXISTS;

DROP TABLE "DECODER_ADRESS" IF EXISTS;

DROP TABLE "ZUG_TYP" IF EXISTS;

DROP TABLE "AUFBAU" IF EXISTS;

DROP TABLE "HERSTELLER" IF EXISTS;

DROP TABLE "ACHSFOLG" IF EXISTS;

DROP TABLE "EPOCH" IF EXISTS;

DROP TABLE "DECODER_TYP" IF EXISTS;

DROP TABLE "ANTRIEB" IF EXISTS;

DROP TABLE "PROTOKOLL" IF EXISTS;

DROP TABLE "STEUERUNG" IF EXISTS;

DROP TABLE "DECODER_TYP_CV" IF EXISTS;

DROP TABLE "MASSSTAB" IF EXISTS;

DROP TABLE "PRODUKT" IF EXISTS;

DROP TABLE "flyway_schema_history" IF EXISTS;

DROP TABLE "DECODER" IF EXISTS;

DROP TABLE "USER_ROLES" IF EXISTS;

DROP TABLE "DECODER_FUNKTION" IF EXISTS;

DROP TABLE "SPURWEITE" IF EXISTS;

DROP TABLE "SONDER_MODELL" IF EXISTS;

DROP TABLE "DECODER_TYP_ADRESS" IF EXISTS;

DROP CREATE SEQUENCE HIBERNATE_SEQUENCE IF EXISTS;
