--<ScriptOptions statementTerminator=";"/>

ALTER TABLE ANDERUNG DROP CONSTRAINT ANDERUNG_FK1;

ALTER TABLE DECODER_TYP_FUNKTION DROP CONSTRAINT DECODERTYPFUNKTION_FK1;

ALTER TABLE DECODER_TYP_ADRESS DROP CONSTRAINT DECODERTYPADRESS_FK1;

ALTER TABLE DECODER_CV DROP CONSTRAINT DECODERCV_FK1;

ALTER TABLE VORBILD DROP CONSTRAINT VORBILD_FK3;

ALTER TABLE DECODER_FUNKTION DROP CONSTRAINT DECODERFUNKTION_FK2;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK4;

ALTER TABLE DECODER DROP CONSTRAINT DECODER_FK2;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK1;

ALTER TABLE USER_ROLES DROP CONSTRAINT FK55ITPPKW3I07DO3H7QOCLQD4K;

ALTER TABLE UNTER_KATEGORIE DROP CONSTRAINT UNTERKATEGORIE_FK1;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK7;

ALTER TABLE DECODER_ADRESS DROP CONSTRAINT DECODERADRESS_FK1;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK8;

ALTER TABLE ZUG DROP CONSTRAINT ZUG_FK1;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK5;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK13;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK2;

ALTER TABLE ZUG_CONSIST DROP CONSTRAINT ZUGCONSIST_FK1;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK11;

ALTER TABLE PRODUKT_TEIL DROP CONSTRAINT PRODUKTTEIL_FK2;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK16;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK15;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK6;

ALTER TABLE DECODER_TYP DROP CONSTRAINT DECODERTYP_FK2;

ALTER TABLE VORBILD DROP CONSTRAINT VORBILD_FK5;

ALTER TABLE VORBILD DROP CONSTRAINT VORBILD_FK2;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK1;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK7;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK9;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK3;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK12;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK4;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK5;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK2;

ALTER TABLE PRODUKT_TEIL DROP CONSTRAINT PRODUKTTEIL_FK1;

ALTER TABLE DECODER_TYP_CV DROP CONSTRAINT DECODERTYPCV_FK1;

ALTER TABLE VORBILD DROP CONSTRAINT VORBILD_FK1;

ALTER TABLE DECODER_FUNKTION DROP CONSTRAINT DECODERFUNKTION_FK1;

ALTER TABLE DECODER_CV DROP CONSTRAINT DECODERCV_FK2;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK3;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK10;

ALTER TABLE ZUG_CONSIST DROP CONSTRAINT ZUGCONSIST_FK2;

ALTER TABLE DECODER_TYP DROP CONSTRAINT DECODERTYP_FK3;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK6;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK14;

ALTER TABLE DECODER DROP CONSTRAINT DECODER_FK1;

ALTER TABLE LAND DROP CONSTRAINT FKD7C3AGPRCPARNMED569N76EIV;

ALTER TABLE VORBILD DROP CONSTRAINT VORBILD_FK4;

ALTER TABLE MOTOR_TYP DROP CONSTRAINT CONSTRAINT_8E;

ALTER TABLE LICHT DROP CONSTRAINT PRIMARY_KEY_4;

ALTER TABLE DECODER_TYP_FUNKTION DROP CONSTRAINT CONSTRAINT_729;

ALTER TABLE ZUG DROP CONSTRAINT PRIMARY_KEY_15;

ALTER TABLE AUFBAU DROP CONSTRAINT CONSTRAINT_7;

ALTER TABLE ZUG_CONSIST DROP CONSTRAINT CONSTRAINT_83;

ALTER TABLE ACHSFOLG DROP CONSTRAINT CONSTRAINT_B;

ALTER TABLE PRODUKT_TEIL DROP CONSTRAINT CONSTRAINT_6;

ALTER TABLE EPOCH DROP CONSTRAINT PRIMARY_KEY_3;

ALTER TABLE SONDER_MODELL DROP CONSTRAINT PRIMARY_KEY_5;

ALTER TABLE ANTRIEB DROP CONSTRAINT CONSTRAINT_F8;

ALTER TABLE SPURWEITE DROP CONSTRAINT CONSTRAINT_A9;

ALTER TABLE HERSTELLER DROP CONSTRAINT PRIMARY_KEY_A;

ALTER TABLE ACHSFOLG DROP CONSTRAINT PRIMARY_KEY_B;

ALTER TABLE ZUG DROP CONSTRAINT CONSTRAINT_15;

ALTER TABLE ANDERUNG DROP CONSTRAINT CONSTRAINT_F;

ALTER TABLE PROTOKOLL DROP CONSTRAINT PRIMARY_KEY_82;

ALTER TABLE DECODER_ADRESS DROP CONSTRAINT CONSTRAINT_72;

ALTER TABLE SPURWEITE DROP CONSTRAINT PRIMARY_KEY_A9;

ALTER TABLE VORBILD DROP CONSTRAINT PRIMARY_KEY_50;

ALTER TABLE WAHRUNG DROP CONSTRAINT CONSTRAINT_6D;

ALTER TABLE MASSSTAB DROP CONSTRAINT PRIMARY_KEY_3F;

ALTER TABLE LAND DROP CONSTRAINT CONSTRAINT_2;

ALTER TABLE BAHNVERWALTUNG DROP CONSTRAINT CONSTRAINT_C;

ALTER TABLE AUFBAU DROP CONSTRAINT PRIMARY_KEY_7;

ALTER TABLE DECODER_TYP_FUNKTION DROP CONSTRAINT PRIMARY_KEY_729;

ALTER TABLE ZUG_TYP DROP CONSTRAINT CONSTRAINT_2E;

ALTER TABLE EPOCH DROP CONSTRAINT CONSTRAINT_3;

ALTER TABLE PROTOKOLL DROP CONSTRAINT CONSTRAINT_82;

ALTER TABLE flyway_schema_history DROP CONSTRAINT flyway_schema_history_pk;

ALTER TABLE BAHNVERWALTUNG DROP CONSTRAINT PRIMARY_KEY_C;

ALTER TABLE DECODER_TYP_ADRESS DROP CONSTRAINT CONSTRAINT_F6;

ALTER TABLE UNTER_KATEGORIE DROP CONSTRAINT CONSTRAINT_FB;

ALTER TABLE HERSTELLER DROP CONSTRAINT CONSTRAINT_A;

ALTER TABLE SONDER_MODELL DROP CONSTRAINT CONSTRAINT_5;

ALTER TABLE USER DROP CONSTRAINT PRIMARY_KEY_27;

ALTER TABLE ZUG_TYP DROP CONSTRAINT PRIMARY_KEY_2E;

ALTER TABLE DECODER_TYP DROP CONSTRAINT PRIMARY_KEY_C8;

ALTER TABLE GATTUNG DROP CONSTRAINT PRIMARY_KEY_1;

ALTER TABLE KATEGORIE DROP CONSTRAINT CONSTRAINT_A5;

ALTER TABLE UNTER_KATEGORIE DROP CONSTRAINT PRIMARY_KEY_FB;

ALTER TABLE STEUERUNG DROP CONSTRAINT PRIMARY_KEY_FF1;

ALTER TABLE KUPPLUNG DROP CONSTRAINT PRIMARY_KEY_8C;

ALTER TABLE ARTIKEL DROP CONSTRAINT PRIMARY_KEY_FF;

ALTER TABLE USER DROP CONSTRAINT CONSTRAINT_27;

ALTER TABLE PRODUKT DROP CONSTRAINT CONSTRAINT_18;

ALTER TABLE ANTRIEB DROP CONSTRAINT PRIMARY_KEY_F8;

ALTER TABLE GATTUNG DROP CONSTRAINT CONSTRAINT_1;

ALTER TABLE DECODER_CV DROP CONSTRAINT CONSTRAINT_D;

ALTER TABLE LICHT DROP CONSTRAINT CONSTRAINT_4;

ALTER TABLE DECODER_FUNKTION DROP CONSTRAINT CONSTRAINT_CD;

ALTER TABLE PRODUKT DROP CONSTRAINT PRIMARY_KEY_18;

ALTER TABLE DECODER DROP CONSTRAINT CONSTRAINT_8;

ALTER TABLE DECODER_TYP DROP CONSTRAINT CONSTRAINT_C8;

ALTER TABLE DECODER_TYP_CV DROP CONSTRAINT CONSTRAINT_9;

ALTER TABLE MASSSTAB DROP CONSTRAINT CONSTRAINT_3F;

ALTER TABLE VORBILD DROP CONSTRAINT CONSTRAINT_50;

ALTER TABLE KATEGORIE DROP CONSTRAINT PRIMARY_KEY_A5;

ALTER TABLE DECODER DROP CONSTRAINT PRIMARY_KEY_8;

ALTER TABLE ARTIKEL DROP CONSTRAINT CONSTRAINT_FF;

ALTER TABLE MOTOR_TYP DROP CONSTRAINT PRIMARY_KEY_8E;

ALTER TABLE STEUERUNG DROP CONSTRAINT CONSTRAINT_FF1;

ALTER TABLE WAHRUNG DROP CONSTRAINT PRIMARY_KEY_6D;

ALTER TABLE KUPPLUNG DROP CONSTRAINT CONSTRAINT_8C;

ALTER TABLE DECODER_TYP_CV DROP CONSTRAINT PRIMARY_KEY_9;

DROP INDEX PRIMARY_KEY_9;

DROP INDEX PRIMARY_KEY_6D;

DROP INDEX PRODUKT_IX1;

DROP INDEX PRODUKT_IX14;

DROP INDEX DECODERADRESS_FK1_INDEX_7;

DROP INDEX ZUGCONSIST_IX2;

DROP INDEX VORBILD_IX4;

DROP INDEX PRIMARY_KEY_7;

DROP INDEX DECODERTYPADRESS_IX1_INDEX_F;

DROP INDEX UK_74UP4CVT5VIMFY09M7OVFMXIF_INDEX_2;

DROP INDEX UK_JLGPBHQY7S4L0RB348P7XL44E_INDEX_3;

DROP INDEX UNTERKATEGORIE_IX2;

DROP INDEX DECODERTYP_UC1_INDEX_C;

DROP INDEX UK_ORDEVYWLK5437FT6BXP996JPE_INDEX_8;

DROP INDEX PRIMARY_KEY_F6;

DROP INDEX DECODERFUNKTION_FK1_INDEX_C;

DROP INDEX DECODERFUNKTION_FK2_INDEX_C;

DROP INDEX ARTIKEL_IX6;

DROP INDEX DECODERTYP_IX2;

DROP INDEX PRODUKT_IX15;

DROP INDEX PRIMARY_KEY_B;

DROP INDEX FK55ITPPKW3I07DO3H7QOCLQD4K_INDEX_C;

DROP INDEX ZUGCONSIST_IX1;

DROP INDEX PRIMARY_KEY_FF;

DROP INDEX PRODUKT_IX16;

DROP INDEX ANDERUNG_IX1;

DROP INDEX ARTIKEL_IX7;

DROP INDEX PRIMARY_KEY_D;

DROP INDEX DECODERTYPADRESS_IX3;

DROP INDEX UK_FGHH9XT5LBA3704OF5P0BOPG2_INDEX_A;

DROP INDEX ARTIKEL_IX5;

DROP INDEX DECODERTYPADRESS_IX2;

DROP INDEX ARTIKEL_IX4;

DROP INDEX DECODERCV_FK2_INDEX_D;

DROP INDEX UK_9KE2194X83UFBNAG389FC9AEG_INDEX_1;

DROP INDEX PRODUKT_IX7;

DROP INDEX ARTIKEL_IX3;

DROP INDEX PRIMARY_KEY_3F;

DROP INDEX UK_PXSAO93KTNQOOB2U03NDNBMEC_INDEX_8;

DROP INDEX PRIMARY_KEY_2E;

DROP INDEX PRODUKTTEIL_IX2;

DROP INDEX VORBILD_IX2;

DROP INDEX UNTERKATEGORIE_IX1_INDEX_F;

DROP INDEX PRODUKT_IX11;

DROP INDEX VORBILD_IX1_INDEX_5;

DROP INDEX PRIMARY_KEY_15;

DROP INDEX DECODERTYPCV_IX3;

DROP INDEX DECODER_IX3;

DROP INDEX VORBILD_IX3;

DROP INDEX PRIMARY_KEY_83;

DROP INDEX DECODERTYP_IX1;

DROP INDEX PRIMARY_KEY_27;

DROP INDEX DECODERFUNKTION_IX1_INDEX_C;

DROP INDEX PRIMARY_KEY_6;

DROP INDEX DECODERADRESS_IX1_INDEX_7;

DROP INDEX PRIMARY_KEY_FF1;

DROP INDEX DECODERTYPFUNKTION_IX1_INDEX_7;

DROP INDEX USER_IX1_INDEX_2;

DROP INDEX PRIMARY_KEY_1;

DROP INDEX UK_E58QJC2BD88UN3BJCRAW0NOVA_INDEX_A;

DROP INDEX UK_N66IG0OYOMQ45JCL34LUBVILY_INDEX_8;

DROP INDEX PRIMARY_KEY_6F;

DROP INDEX PRODUKT_IX6;

DROP INDEX PRIMARY_KEY_CD;

DROP INDEX ARTIKEL_IX1;

DROP INDEX UK_8G0TJPCECYX7PNU04FXBFVE4T_INDEX_3;

DROP INDEX PRIMARY_KEY_4;

DROP INDEX ANDERUNG_UC1_INDEX_F;

DROP INDEX UK_PI24NCTFCDA9UWT8I8P8J7388_INDEX_F;

DROP INDEX VORBILD_FK3_INDEX_5;

DROP INDEX UK_5AXPTMX387UMYA26EGWT76CH0_INDEX_F;

DROP INDEX PRIMARY_KEY_18;

DROP INDEX PRODUKT_IX9;

DROP INDEX PRODUKT_IX5;

DROP INDEX UK_R4FFBFLR2V4QMWQJXY84D7NUA_INDEX_C;

DROP INDEX PRIMARY_KEY_A;

DROP INDEX UK_FY8U67U46V5HPRXWGKQQWB9C3_INDEX_B;

DROP INDEX DECODERTYPCV_IX1_INDEX_9;

DROP INDEX ANDERUNG_IX2;

DROP INDEX UK_5U32DDL5AEF15B8B1YSDNX9M6_INDEX_F;

DROP INDEX PRIMARY_KEY_50;

DROP INDEX PRODUKTTEIL_IX3;

DROP INDEX DECODERCV_IX1_INDEX_D;

DROP INDEX PRIMARY_KEY_F8;

DROP INDEX PRIMARY_KEY_5;

DROP INDEX PRODUKT_IX2;

DROP INDEX PRODUKT_IX13;

DROP INDEX PRIMARY_KEY_8E;

DROP INDEX ARTIKEL_IX2;

DROP INDEX PRIMARY_KEY_2;

DROP INDEX UK_RJYSOLH7ON8XHRLII99I9X9XK_INDEX_8;

DROP INDEX PRIMARY_KEY_FB;

DROP INDEX PRODUKT_IX12;

DROP INDEX ZUGCONSIST_UC1_INDEX_8;

DROP INDEX DECODERTYPCV_IX2;

DROP INDEX FKD7C3AGPRCPARNMED569N76EIV_INDEX_2;

DROP INDEX UK_JDYFX82XKNXYAMXCUOQ9BFOMA_INDEX_1;

DROP INDEX PRIMARY_KEY_8C;

DROP INDEX UK_EUKGDBSRH32KNTT88WS56HWMK_INDEX_6;

DROP INDEX PRIMARY_KEY_72;

DROP INDEX PRIMARY_KEY_F;

DROP INDEX PRODUKTTEIL_IX1_INDEX_6;

DROP INDEX DECODERCV_FK1_INDEX_D;

DROP INDEX UK_JL307IH43DRNQD394SE5YB52R_INDEX_A;

DROP INDEX flyway_schema_history_s_idx;

DROP INDEX UK_IXSD3RJL6DQ24DW9F50XLMFAF_INDEX_5;

DROP INDEX PRIMARY_KEY_3;

DROP INDEX UK_R4VR916URFVY092FNM2AEGEPE_INDEX_4;

DROP INDEX PRIMARY_KEY_82;

DROP INDEX PRODUKT_IX10;

DROP INDEX PRODUKT_IX8;

DROP INDEX UK_Q500PA6UM871VYFR0HGWAPU2Q_INDEX_7;

DROP INDEX PRODUKT_UC1_INDEX_1;

DROP INDEX PRIMARY_KEY_A9;

DROP INDEX DECODER_IX2;

DROP INDEX PRIMARY_KEY_C;

DROP INDEX ZUG_IX2;

DROP INDEX PRIMARY_KEY_729;

DROP INDEX UK_MBCHHJFUEGIF7BQUQ5J6TKAL3_INDEX_2;

DROP INDEX DECODERTYPFUNKTION_IX2;

DROP INDEX PRODUKT_IX4;

DROP INDEX PRIMARY_KEY_8;

DROP INDEX PRIMARY_KEY_A5;

DROP INDEX PRIMARY_KEY_C8;

DROP INDEX PRODUKT_IX3;

DROP TABLE DECODER_TYP_ADRESS;

DROP TABLE LAND;

DROP TABLE ZUG_TYP;

DROP TABLE SPURWEITE;

DROP TABLE HERSTELLER;

DROP TABLE DECODER_TYP_CV;

DROP TABLE PRODUKT;

DROP TABLE WAHRUNG;

DROP TABLE KATEGORIE;

DROP TABLE ZUG;

DROP TABLE EPOCH;

DROP TABLE DECODER_TYP_FUNKTION;

DROP TABLE USER;

DROP TABLE VORBILD;

DROP TABLE GATTUNG;

DROP TABLE ZUG_CONSIST;

DROP TABLE PROTOKOLL;

DROP TABLE ACHSFOLG;

DROP TABLE DECODER_CV;

DROP TABLE PRODUKT_TEIL;

DROP TABLE STEUERUNG;

DROP TABLE DECODER_TYP;

DROP TABLE ANTRIEB;

DROP TABLE DECODER;

DROP TABLE flyway_schema_history;

DROP TABLE DECODER_ADRESS;

DROP TABLE UNTER_KATEGORIE;

DROP TABLE ANDERUNG;

DROP TABLE LICHT;

DROP TABLE BAHNVERWALTUNG;

DROP TABLE DECODER_FUNKTION;

DROP TABLE MOTOR_TYP;

DROP TABLE ARTIKEL;

DROP TABLE KUPPLUNG;

DROP TABLE MASSSTAB;

DROP TABLE USER_ROLES;

DROP TABLE AUFBAU;

DROP TABLE SONDER_MODELL;

CREATE TABLE DECODER_TYP_ADRESS (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		WERKSEINSTELLUNG INTEGER,
		ADRESS_TYP INTEGER NOT NULL,
		INDEX INTEGER NOT NULL,
		SPAN INTEGER NOT NULL,
		DECODER_TYP_ID BIGINT NOT NULL
	);

CREATE TABLE LAND (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL,
		WAHRUNG_ID BIGINT
	);

CREATE TABLE ZUG_TYP (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE SPURWEITE (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE HERSTELLER (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL,
		TELEFON VARCHAR(20),
		URL VARCHAR(255)
	);

CREATE TABLE DECODER_TYP_CV (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100),
		CV INTEGER NOT NULL,
		MAXIMAL INTEGER,
		MINIMAL INTEGER,
		WERKSEINSTELLUNG INTEGER,
		DECODER_TYP_ID BIGINT NOT NULL
	);

CREATE TABLE PRODUKT (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ABBILDUNG VARCHAR(255),
		ANLEITUNGEN VARCHAR(512),
		ANMERKUNG VARCHAR(100),
		BAUZEIT DATE,
		BESTELL_NR VARCHAR(255),
		BETREIBSNUMMER VARCHAR(100),
		BEZEICHNUNG VARCHAR(100),
		EXPLOSIONSZEICHNUNG VARCHAR(512),
		LANGE DECIMAL(6 , 2),
		ACHSFOLG_ID BIGINT,
		AUFBAU_ID BIGINT,
		BAHNVERWALTUNG_ID BIGINT,
		DECODER_TYP_ID BIGINT,
		EPOCH_ID BIGINT,
		GATTUNG_ID BIGINT,
		HERSTELLER_ID BIGINT NOT NULL,
		KUPPLUNG_ID BIGINT,
		LICHT_ID BIGINT,
		MASSSTAB_ID BIGINT NOT NULL,
		MOTOR_TYP_ID BIGINT,
		SONDERMODELL_ID BIGINT,
		SPURWEITE_ID BIGINT NOT NULL,
		STEUERUNG_ID BIGINT,
		UNTER_KATEGORIE_ID BIGINT NOT NULL,
		VORBILD_ID BIGINT
	);

CREATE TABLE WAHRUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL,
		DEZIMAL INTEGER
	);

CREATE TABLE KATEGORIE (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE ZUG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL,
		ZUG_TYP_ID BIGINT NOT NULL
	);

CREATE TABLE EPOCH (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE DECODER_TYP_FUNKTION (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100),
		FUNKTION VARCHAR(4),
		PROGRAMMABLE BOOLEAN NOT NULL,
		REIHE INTEGER NOT NULL,
		DECODER_TYP_ID BIGINT NOT NULL
	);

CREATE TABLE USER (
		ID INTEGER NOT NULL,
		CONFIRMATION_TOKEN VARCHAR(255),
		CREDENTIALS_EXPIRED BOOLEAN,
		EMAIL VARCHAR(255) NOT NULL,
		ENABLED BOOLEAN,
		EXPIRED BOOLEAN,
		FIRST_NAME VARCHAR(255) NOT NULL,
		LAST_NAME VARCHAR(255) NOT NULL,
		LOCKED BOOLEAN,
		RESET_TOKEN VARCHAR(255)
	);

CREATE TABLE VORBILD (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ABBILDUNG VARCHAR(255),
		ANFAHRZUGKRAFT DECIMAL(19 , 2),
		ANZAHL INTEGER,
		AUFBAU VARCHAR(100),
		AUSSERDIENST DATE,
		BAUZEIT DATE,
		BETREIBSNUMMER VARCHAR(100),
		BEZEICHNUNG VARCHAR(100),
		DIENSTGEWICHT DECIMAL(19 , 2),
		DM_LAUFRAD_HINTEN DECIMAL(19 , 2),
		DM_LAUFRAD_VORN DECIMAL(19 , 2),
		DM_TREIBRAD DECIMAL(19 , 2),
		DM_ZYLINDER DECIMAL(19 , 2),
		DREHGESTELL_BAUART VARCHAR(100),
		FAHRMOTOREN INTEGER,
		GESCHWINDIGKEIT INTEGER,
		HERSTELLER VARCHAR(100),
		KAPAZITAT DECIMAL(19 , 2),
		KESSELUBERDRUCK DECIMAL(19 , 2),
		KLASSE INTEGER,
		KOLBENHUB DECIMAL(19 , 2),
		LANGE DECIMAL(19 , 2),
		LEISTUNG DECIMAL(19 , 2),
		LEISTUNGSUBERTRAGUNG VARCHAR(255),
		MITTELWAGEN INTEGER,
		MOTORBAUART VARCHAR(100),
		REICHWEITE DECIMAL(19 , 2),
		ROSTFLACHE DECIMAL(19 , 2),
		SITZPLATZEKL1 INTEGER,
		SITZPLATZEKL2 INTEGER,
		SITZPLATZEKL3 INTEGER,
		SITZPLATZEKL4 INTEGER,
		TRIEBKOPF INTEGER,
		UBERHITZERFLACHE DECIMAL(19 , 2),
		VERDAMPFUNG DECIMAL(19 , 2),
		WASSERVORRAT DECIMAL(19 , 2),
		ZYLINDER INTEGER,
		ACHSFOLG_ID BIGINT NOT NULL,
		ANTRIEB_ID BIGINT NOT NULL,
		BAHNVERWALTUNG_ID BIGINT NOT NULL,
		GATTUNG_ID BIGINT NOT NULL,
		UNTER_KATEGORIE_ID BIGINT NOT NULL
	);

CREATE TABLE GATTUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE ZUG_CONSIST (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		POSITION INTEGER NOT NULL,
		ARTIKEL_ID BIGINT NOT NULL,
		ZUG_ID BIGINT NOT NULL
	);

CREATE TABLE PROTOKOLL (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE ACHSFOLG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE DECODER_CV (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		WERT INTEGER,
		CV_ID BIGINT NOT NULL,
		DECODER_ID BIGINT NOT NULL
	);

CREATE TABLE PRODUKT_TEIL (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ANZAHL INTEGER NOT NULL,
		PRODUKT_ID BIGINT NOT NULL,
		TEIL_ID BIGINT NOT NULL
	);

CREATE TABLE STEUERUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE DECODER_TYP (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ANLEITUNGEN VARCHAR(512),
		BESTELL_NR VARCHAR(255),
		BEZEICHNUNG VARCHAR(100),
		FAHRSTUFE INTEGER,
		I_MAX DECIMAL(6 , 2),
		KONFIGURATION VARCHAR(15) NOT NULL,
		SOUND BOOLEAN NOT NULL,
		STECKER VARCHAR(10) NOT NULL,
		HERSTELLER_ID BIGINT NOT NULL,
		PROTOKOLL_ID BIGINT NOT NULL
	);

CREATE TABLE ANTRIEB (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE DECODER (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		DECODER_ID VARCHAR(6) NOT NULL,
		FAHRSTUFE INTEGER,
		STATUS INTEGER,
		DECODER_TYP_ID BIGINT NOT NULL,
		PROTOKOLL_ID BIGINT NOT NULL
	);

CREATE TABLE flyway_schema_history (
		installed_rank INTEGER NOT NULL,
		version VARCHAR(50),
		description VARCHAR(200) NOT NULL,
		type VARCHAR(20) NOT NULL,
		script VARCHAR(1000) NOT NULL,
		checksum INTEGER,
		installed_by VARCHAR(100) NOT NULL,
		installed_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
		execution_time INTEGER NOT NULL,
		success BOOLEAN NOT NULL
	);

CREATE TABLE DECODER_ADRESS (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ADRESS INTEGER NOT NULL,
		ADRESS_TYP VARCHAR(10) NOT NULL,
		INDEX INTEGER NOT NULL,
		DECODER_ID BIGINT NOT NULL
	);

CREATE TABLE UNTER_KATEGORIE (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50),
		KATEGORIE_ID BIGINT NOT NULL
	);

CREATE TABLE ANDERUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ANDERUNG_ID INTEGER NOT NULL,
		ANDERUNGSDATUM DATE,
		ANDERUNGS_TYP VARCHAR(255) NOT NULL,
		ANMERKUNG VARCHAR(255),
		BEZEICHNUNG VARCHAR(100),
		STUCK INTEGER,
		ARTIKEL_ID BIGINT NOT NULL
	);

CREATE TABLE LICHT (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE BAHNVERWALTUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE DECODER_FUNKTION (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		DECODER_ID BIGINT NOT NULL,
		FUNKTION_ID BIGINT NOT NULL
	);

CREATE TABLE MOTOR_TYP (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE ARTIKEL (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ABBILDUNG VARCHAR(255),
		ANMERKUNG VARCHAR(100),
		ARTIKEL_ID VARCHAR(6) NOT NULL,
		BELADUNG VARCHAR(100),
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		KAUFDATUM DATE,
		PREIS DECIMAL(6 , 2),
		STATUS VARCHAR(255) NOT NULL,
		STUCK INTEGER NOT NULL,
		VERBLEIBENDE INTEGER NOT NULL,
		DECODER_ID BIGINT,
		KUPPLUNG_ID BIGINT,
		LICHT_ID BIGINT,
		MOTOR_TYP_ID BIGINT,
		PRODUKT_ID BIGINT NOT NULL,
		STEUERUNG_ID BIGINT,
		WAHRUNG_ID BIGINT
	);

CREATE TABLE KUPPLUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE MASSSTAB (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE USER_ROLES (
		USER_ID INTEGER NOT NULL,
		ROLES VARCHAR(255)
	);

CREATE TABLE AUFBAU (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE SONDER_MODELL (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE UNIQUE INDEX PRIMARY_KEY_9 ON DECODER_TYP_CV (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6D ON WAHRUNG (ID ASC);

CREATE INDEX PRODUKT_IX1 ON PRODUKT (HERSTELLER_ID ASC);

CREATE INDEX PRODUKT_IX14 ON PRODUKT (STEUERUNG_ID ASC);

CREATE INDEX DECODERADRESS_FK1_INDEX_7 ON DECODER_ADRESS (DECODER_ID ASC);

CREATE INDEX ZUGCONSIST_IX2 ON ZUG_CONSIST (ARTIKEL_ID ASC);

CREATE INDEX VORBILD_IX4 ON VORBILD (ACHSFOLG_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_7 ON AUFBAU (ID ASC);

CREATE UNIQUE INDEX DECODERTYPADRESS_IX1_INDEX_F ON DECODER_TYP_ADRESS (DECODER_TYP_ID ASC, INDEX ASC);

CREATE UNIQUE INDEX UK_74UP4CVT5VIMFY09M7OVFMXIF_INDEX_2 ON LAND (NAME ASC);

CREATE UNIQUE INDEX UK_JLGPBHQY7S4L0RB348P7XL44E_INDEX_3 ON MASSSTAB (NAME ASC);

CREATE INDEX UNTERKATEGORIE_IX2 ON UNTER_KATEGORIE (KATEGORIE_ID ASC);

CREATE UNIQUE INDEX DECODERTYP_UC1_INDEX_C ON DECODER_TYP (HERSTELLER_ID ASC, BESTELL_NR ASC);

CREATE UNIQUE INDEX UK_ORDEVYWLK5437FT6BXP996JPE_INDEX_8 ON DECODER (DECODER_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F6 ON DECODER_TYP_ADRESS (ID ASC);

CREATE INDEX DECODERFUNKTION_FK1_INDEX_C ON DECODER_FUNKTION (DECODER_ID ASC);

CREATE INDEX DECODERFUNKTION_FK2_INDEX_C ON DECODER_FUNKTION (FUNKTION_ID ASC);

CREATE INDEX ARTIKEL_IX6 ON ARTIKEL (KUPPLUNG_ID ASC);

CREATE INDEX DECODERTYP_IX2 ON DECODER_TYP (PROTOKOLL_ID ASC);

CREATE INDEX PRODUKT_IX15 ON PRODUKT (DECODER_TYP_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B ON ACHSFOLG (ID ASC);

CREATE INDEX FK55ITPPKW3I07DO3H7QOCLQD4K_INDEX_C ON USER_ROLES (USER_ID ASC);

CREATE INDEX ZUGCONSIST_IX1 ON ZUG_CONSIST (ZUG_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_FF ON ARTIKEL (ID ASC);

CREATE INDEX PRODUKT_IX16 ON PRODUKT (MOTOR_TYP_ID ASC);

CREATE INDEX ANDERUNG_IX1 ON ANDERUNG (ARTIKEL_ID ASC);

CREATE INDEX ARTIKEL_IX7 ON ARTIKEL (DECODER_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D ON DECODER_CV (ID ASC);

CREATE INDEX DECODERTYPADRESS_IX3 ON DECODER_TYP_ADRESS (INDEX ASC);

CREATE UNIQUE INDEX UK_FGHH9XT5LBA3704OF5P0BOPG2_INDEX_A ON KATEGORIE (NAME ASC);

CREATE INDEX ARTIKEL_IX5 ON ARTIKEL (LICHT_ID ASC);

CREATE INDEX DECODERTYPADRESS_IX2 ON DECODER_TYP_ADRESS (DECODER_TYP_ID ASC);

CREATE INDEX ARTIKEL_IX4 ON ARTIKEL (MOTOR_TYP_ID ASC);

CREATE INDEX DECODERCV_FK2_INDEX_D ON DECODER_CV (CV_ID ASC);

CREATE UNIQUE INDEX UK_9KE2194X83UFBNAG389FC9AEG_INDEX_1 ON GATTUNG (NAME ASC);

CREATE INDEX PRODUKT_IX7 ON PRODUKT (SPURWEITE_ID ASC);

CREATE INDEX ARTIKEL_IX3 ON ARTIKEL (STEUERUNG_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_3F ON MASSSTAB (ID ASC);

CREATE UNIQUE INDEX UK_PXSAO93KTNQOOB2U03NDNBMEC_INDEX_8 ON PROTOKOLL (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_2E ON ZUG_TYP (ID ASC);

CREATE INDEX PRODUKTTEIL_IX2 ON PRODUKT_TEIL (PRODUKT_ID ASC);

CREATE INDEX VORBILD_IX2 ON VORBILD (UNTER_KATEGORIE_ID ASC);

CREATE UNIQUE INDEX UNTERKATEGORIE_IX1_INDEX_F ON UNTER_KATEGORIE (KATEGORIE_ID ASC, NAME ASC);

CREATE INDEX PRODUKT_IX11 ON PRODUKT (LICHT_ID ASC);

CREATE UNIQUE INDEX VORBILD_IX1_INDEX_5 ON VORBILD (GATTUNG_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_15 ON ZUG (ID ASC);

CREATE INDEX DECODERTYPCV_IX3 ON DECODER_TYP_CV (CV ASC);

CREATE INDEX DECODER_IX3 ON DECODER (PROTOKOLL_ID ASC);

CREATE INDEX VORBILD_IX3 ON VORBILD (ANTRIEB_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_83 ON ZUG_CONSIST (ID ASC);

CREATE INDEX DECODERTYP_IX1 ON DECODER_TYP (HERSTELLER_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_27 ON USER (ID ASC);

CREATE UNIQUE INDEX DECODERFUNKTION_IX1_INDEX_C ON DECODER_FUNKTION (DECODER_ID ASC, FUNKTION_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6 ON flyway_schema_history (installed_rank ASC);

CREATE UNIQUE INDEX DECODERADRESS_IX1_INDEX_7 ON DECODER_ADRESS (DECODER_ID ASC, INDEX ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_FF1 ON STEUERUNG (ID ASC);

CREATE UNIQUE INDEX DECODERTYPFUNKTION_IX1_INDEX_7 ON DECODER_TYP_FUNKTION (DECODER_TYP_ID ASC, REIHE ASC, FUNKTION ASC);

CREATE UNIQUE INDEX USER_IX1_INDEX_2 ON USER (EMAIL ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1 ON GATTUNG (ID ASC);

CREATE UNIQUE INDEX UK_E58QJC2BD88UN3BJCRAW0NOVA_INDEX_A ON HERSTELLER (NAME ASC);

CREATE UNIQUE INDEX UK_N66IG0OYOMQ45JCL34LUBVILY_INDEX_8 ON MOTOR_TYP (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6F ON PRODUKT_TEIL (ID ASC);

CREATE INDEX PRODUKT_IX6 ON PRODUKT (MASSSTAB_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_CD ON DECODER_FUNKTION (ID ASC);

CREATE INDEX ARTIKEL_IX1 ON ARTIKEL (PRODUKT_ID ASC);

CREATE UNIQUE INDEX UK_8G0TJPCECYX7PNU04FXBFVE4T_INDEX_3 ON EPOCH (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_4 ON LICHT (ID ASC);

CREATE UNIQUE INDEX ANDERUNG_UC1_INDEX_F ON ANDERUNG (ARTIKEL_ID ASC, ANDERUNG_ID ASC);

CREATE UNIQUE INDEX UK_PI24NCTFCDA9UWT8I8P8J7388_INDEX_F ON ARTIKEL (ARTIKEL_ID ASC);

CREATE INDEX VORBILD_FK3_INDEX_5 ON VORBILD (BAHNVERWALTUNG_ID ASC);

CREATE UNIQUE INDEX UK_5AXPTMX387UMYA26EGWT76CH0_INDEX_F ON ANTRIEB (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_18 ON PRODUKT (ID ASC);

CREATE INDEX PRODUKT_IX9 ON PRODUKT (SONDERMODELL_ID ASC);

CREATE INDEX PRODUKT_IX5 ON PRODUKT (ACHSFOLG_ID ASC);

CREATE UNIQUE INDEX UK_R4FFBFLR2V4QMWQJXY84D7NUA_INDEX_C ON BAHNVERWALTUNG (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A ON HERSTELLER (ID ASC);

CREATE UNIQUE INDEX UK_FY8U67U46V5HPRXWGKQQWB9C3_INDEX_B ON ACHSFOLG (NAME ASC);

CREATE UNIQUE INDEX DECODERTYPCV_IX1_INDEX_9 ON DECODER_TYP_CV (DECODER_TYP_ID ASC, CV ASC);

CREATE INDEX ANDERUNG_IX2 ON ANDERUNG (ANDERUNG_ID ASC);

CREATE UNIQUE INDEX UK_5U32DDL5AEF15B8B1YSDNX9M6_INDEX_F ON STEUERUNG (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_50 ON VORBILD (ID ASC);

CREATE INDEX PRODUKTTEIL_IX3 ON PRODUKT_TEIL (TEIL_ID ASC);

CREATE UNIQUE INDEX DECODERCV_IX1_INDEX_D ON DECODER_CV (DECODER_ID ASC, CV_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F8 ON ANTRIEB (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_5 ON SONDER_MODELL (ID ASC);

CREATE INDEX PRODUKT_IX2 ON PRODUKT (EPOCH_ID ASC);

CREATE INDEX PRODUKT_IX13 ON PRODUKT (VORBILD_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8E ON MOTOR_TYP (ID ASC);

CREATE INDEX ARTIKEL_IX2 ON ARTIKEL (WAHRUNG_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_2 ON LAND (ID ASC);

CREATE UNIQUE INDEX UK_RJYSOLH7ON8XHRLII99I9X9XK_INDEX_8 ON KUPPLUNG (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_FB ON UNTER_KATEGORIE (ID ASC);

CREATE INDEX PRODUKT_IX12 ON PRODUKT (KUPPLUNG_ID ASC);

CREATE UNIQUE INDEX ZUGCONSIST_UC1_INDEX_8 ON ZUG_CONSIST (ZUG_ID ASC, POSITION ASC);

CREATE INDEX DECODERTYPCV_IX2 ON DECODER_TYP_CV (DECODER_TYP_ID ASC);

CREATE INDEX FKD7C3AGPRCPARNMED569N76EIV_INDEX_2 ON LAND (WAHRUNG_ID ASC);

CREATE UNIQUE INDEX UK_JDYFX82XKNXYAMXCUOQ9BFOMA_INDEX_1 ON ZUG (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8C ON KUPPLUNG (ID ASC);

CREATE UNIQUE INDEX UK_EUKGDBSRH32KNTT88WS56HWMK_INDEX_6 ON WAHRUNG (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_72 ON DECODER_ADRESS (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F ON ANDERUNG (ID ASC);

CREATE UNIQUE INDEX PRODUKTTEIL_IX1_INDEX_6 ON PRODUKT_TEIL (PRODUKT_ID ASC, TEIL_ID ASC);

CREATE INDEX DECODERCV_FK1_INDEX_D ON DECODER_CV (DECODER_ID ASC);

CREATE UNIQUE INDEX UK_JL307IH43DRNQD394SE5YB52R_INDEX_A ON SPURWEITE (NAME ASC);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success ASC);

CREATE UNIQUE INDEX UK_IXSD3RJL6DQ24DW9F50XLMFAF_INDEX_5 ON SONDER_MODELL (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_3 ON EPOCH (ID ASC);

CREATE UNIQUE INDEX UK_R4VR916URFVY092FNM2AEGEPE_INDEX_4 ON LICHT (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_82 ON PROTOKOLL (ID ASC);

CREATE INDEX PRODUKT_IX10 ON PRODUKT (AUFBAU_ID ASC);

CREATE INDEX PRODUKT_IX8 ON PRODUKT (UNTER_KATEGORIE_ID ASC);

CREATE UNIQUE INDEX UK_Q500PA6UM871VYFR0HGWAPU2Q_INDEX_7 ON AUFBAU (NAME ASC);

CREATE UNIQUE INDEX PRODUKT_UC1_INDEX_1 ON PRODUKT (HERSTELLER_ID ASC, BESTELL_NR ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A9 ON SPURWEITE (ID ASC);

CREATE INDEX DECODER_IX2 ON DECODER (DECODER_TYP_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C ON BAHNVERWALTUNG (ID ASC);

CREATE INDEX ZUG_IX2 ON ZUG (ZUG_TYP_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_729 ON DECODER_TYP_FUNKTION (ID ASC);

CREATE UNIQUE INDEX UK_MBCHHJFUEGIF7BQUQ5J6TKAL3_INDEX_2 ON ZUG_TYP (NAME ASC);

CREATE INDEX DECODERTYPFUNKTION_IX2 ON DECODER_TYP_FUNKTION (DECODER_TYP_ID ASC);

CREATE INDEX PRODUKT_IX4 ON PRODUKT (BAHNVERWALTUNG_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8 ON DECODER (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A5 ON KATEGORIE (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C8 ON DECODER_TYP (ID ASC);

CREATE INDEX PRODUKT_IX3 ON PRODUKT (GATTUNG_ID ASC);

ALTER TABLE MOTOR_TYP ADD CONSTRAINT CONSTRAINT_8E PRIMARY KEY (ID);

ALTER TABLE LICHT ADD CONSTRAINT PRIMARY_KEY_4 UNIQUE (ID);

ALTER TABLE DECODER_TYP_FUNKTION ADD CONSTRAINT CONSTRAINT_729 PRIMARY KEY (ID);

ALTER TABLE ZUG ADD CONSTRAINT PRIMARY_KEY_15 UNIQUE (ID);

ALTER TABLE AUFBAU ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY (ID);

ALTER TABLE ZUG_CONSIST ADD CONSTRAINT CONSTRAINT_83 PRIMARY KEY (ID);

ALTER TABLE ACHSFOLG ADD CONSTRAINT CONSTRAINT_B PRIMARY KEY (ID);

ALTER TABLE PRODUKT_TEIL ADD CONSTRAINT CONSTRAINT_6 PRIMARY KEY (ID);

ALTER TABLE EPOCH ADD CONSTRAINT PRIMARY_KEY_3 UNIQUE (ID);

ALTER TABLE SONDER_MODELL ADD CONSTRAINT PRIMARY_KEY_5 UNIQUE (ID);

ALTER TABLE ANTRIEB ADD CONSTRAINT CONSTRAINT_F8 PRIMARY KEY (ID);

ALTER TABLE SPURWEITE ADD CONSTRAINT CONSTRAINT_A9 PRIMARY KEY (ID);

ALTER TABLE HERSTELLER ADD CONSTRAINT PRIMARY_KEY_A UNIQUE (ID);

ALTER TABLE ACHSFOLG ADD CONSTRAINT PRIMARY_KEY_B UNIQUE (ID);

ALTER TABLE ZUG ADD CONSTRAINT CONSTRAINT_15 PRIMARY KEY (ID);

ALTER TABLE ANDERUNG ADD CONSTRAINT CONSTRAINT_F PRIMARY KEY (ID);

ALTER TABLE PROTOKOLL ADD CONSTRAINT PRIMARY_KEY_82 UNIQUE (ID);

ALTER TABLE DECODER_ADRESS ADD CONSTRAINT CONSTRAINT_72 PRIMARY KEY (ID);

ALTER TABLE SPURWEITE ADD CONSTRAINT PRIMARY_KEY_A9 UNIQUE (ID);

ALTER TABLE VORBILD ADD CONSTRAINT PRIMARY_KEY_50 UNIQUE (ID);

ALTER TABLE WAHRUNG ADD CONSTRAINT CONSTRAINT_6D PRIMARY KEY (ID);

ALTER TABLE MASSSTAB ADD CONSTRAINT PRIMARY_KEY_3F UNIQUE (ID);

ALTER TABLE LAND ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID);

ALTER TABLE BAHNVERWALTUNG ADD CONSTRAINT CONSTRAINT_C PRIMARY KEY (ID);

ALTER TABLE AUFBAU ADD CONSTRAINT PRIMARY_KEY_7 UNIQUE (ID);

ALTER TABLE DECODER_TYP_FUNKTION ADD CONSTRAINT PRIMARY_KEY_729 UNIQUE (ID);

ALTER TABLE ZUG_TYP ADD CONSTRAINT CONSTRAINT_2E PRIMARY KEY (ID);

ALTER TABLE EPOCH ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID);

ALTER TABLE PROTOKOLL ADD CONSTRAINT CONSTRAINT_82 PRIMARY KEY (ID);

ALTER TABLE flyway_schema_history ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);

ALTER TABLE BAHNVERWALTUNG ADD CONSTRAINT PRIMARY_KEY_C UNIQUE (ID);

ALTER TABLE DECODER_TYP_ADRESS ADD CONSTRAINT CONSTRAINT_F6 PRIMARY KEY (ID);

ALTER TABLE UNTER_KATEGORIE ADD CONSTRAINT CONSTRAINT_FB PRIMARY KEY (ID);

ALTER TABLE HERSTELLER ADD CONSTRAINT CONSTRAINT_A PRIMARY KEY (ID);

ALTER TABLE SONDER_MODELL ADD CONSTRAINT CONSTRAINT_5 PRIMARY KEY (ID);

ALTER TABLE USER ADD CONSTRAINT PRIMARY_KEY_27 UNIQUE (ID);

ALTER TABLE ZUG_TYP ADD CONSTRAINT PRIMARY_KEY_2E UNIQUE (ID);

ALTER TABLE DECODER_TYP ADD CONSTRAINT PRIMARY_KEY_C8 UNIQUE (ID);

ALTER TABLE GATTUNG ADD CONSTRAINT PRIMARY_KEY_1 UNIQUE (ID);

ALTER TABLE KATEGORIE ADD CONSTRAINT CONSTRAINT_A5 PRIMARY KEY (ID);

ALTER TABLE UNTER_KATEGORIE ADD CONSTRAINT PRIMARY_KEY_FB UNIQUE (ID);

ALTER TABLE STEUERUNG ADD CONSTRAINT PRIMARY_KEY_FF1 UNIQUE (ID);

ALTER TABLE KUPPLUNG ADD CONSTRAINT PRIMARY_KEY_8C UNIQUE (ID);

ALTER TABLE ARTIKEL ADD CONSTRAINT PRIMARY_KEY_FF UNIQUE (ID);

ALTER TABLE USER ADD CONSTRAINT CONSTRAINT_27 PRIMARY KEY (ID);

ALTER TABLE PRODUKT ADD CONSTRAINT CONSTRAINT_18 PRIMARY KEY (ID);

ALTER TABLE ANTRIEB ADD CONSTRAINT PRIMARY_KEY_F8 UNIQUE (ID);

ALTER TABLE GATTUNG ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY (ID);

ALTER TABLE DECODER_CV ADD CONSTRAINT CONSTRAINT_D PRIMARY KEY (ID);

ALTER TABLE LICHT ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID);

ALTER TABLE DECODER_FUNKTION ADD CONSTRAINT CONSTRAINT_CD PRIMARY KEY (ID);

ALTER TABLE PRODUKT ADD CONSTRAINT PRIMARY_KEY_18 UNIQUE (ID);

ALTER TABLE DECODER ADD CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID);

ALTER TABLE DECODER_TYP ADD CONSTRAINT CONSTRAINT_C8 PRIMARY KEY (ID);

ALTER TABLE DECODER_TYP_CV ADD CONSTRAINT CONSTRAINT_9 PRIMARY KEY (ID);

ALTER TABLE MASSSTAB ADD CONSTRAINT CONSTRAINT_3F PRIMARY KEY (ID);

ALTER TABLE VORBILD ADD CONSTRAINT CONSTRAINT_50 PRIMARY KEY (ID);

ALTER TABLE KATEGORIE ADD CONSTRAINT PRIMARY_KEY_A5 UNIQUE (ID);

ALTER TABLE DECODER ADD CONSTRAINT PRIMARY_KEY_8 UNIQUE (ID);

ALTER TABLE ARTIKEL ADD CONSTRAINT CONSTRAINT_FF PRIMARY KEY (ID);

ALTER TABLE MOTOR_TYP ADD CONSTRAINT PRIMARY_KEY_8E UNIQUE (ID);

ALTER TABLE STEUERUNG ADD CONSTRAINT CONSTRAINT_FF1 PRIMARY KEY (ID);

ALTER TABLE WAHRUNG ADD CONSTRAINT PRIMARY_KEY_6D UNIQUE (ID);

ALTER TABLE KUPPLUNG ADD CONSTRAINT CONSTRAINT_8C PRIMARY KEY (ID);

ALTER TABLE DECODER_TYP_CV ADD CONSTRAINT PRIMARY_KEY_9 UNIQUE (ID);

ALTER TABLE ANDERUNG ADD CONSTRAINT ANDERUNG_FK1 FOREIGN KEY (ARTIKEL_ID)
	REFERENCES ARTIKEL (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_TYP_FUNKTION ADD CONSTRAINT DECODERTYPFUNKTION_FK1 FOREIGN KEY (DECODER_TYP_ID)
	REFERENCES DECODER_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_TYP_ADRESS ADD CONSTRAINT DECODERTYPADRESS_FK1 FOREIGN KEY (DECODER_TYP_ID)
	REFERENCES DECODER_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_CV ADD CONSTRAINT DECODERCV_FK1 FOREIGN KEY (DECODER_ID)
	REFERENCES DECODER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE VORBILD ADD CONSTRAINT VORBILD_FK3 FOREIGN KEY (BAHNVERWALTUNG_ID)
	REFERENCES BAHNVERWALTUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_FUNKTION ADD CONSTRAINT DECODERFUNKTION_FK2 FOREIGN KEY (FUNKTION_ID)
	REFERENCES DECODER_TYP_FUNKTION (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK4 FOREIGN KEY (ACHSFOLG_ID)
	REFERENCES ACHSFOLG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER ADD CONSTRAINT DECODER_FK2 FOREIGN KEY (PROTOKOLL_ID)
	REFERENCES PROTOKOLL (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK1 FOREIGN KEY (PRODUKT_ID)
	REFERENCES PRODUKT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE USER_ROLES ADD CONSTRAINT FK55ITPPKW3I07DO3H7QOCLQD4K FOREIGN KEY (USER_ID)
	REFERENCES USER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE UNTER_KATEGORIE ADD CONSTRAINT UNTERKATEGORIE_FK1 FOREIGN KEY (KATEGORIE_ID)
	REFERENCES KATEGORIE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK7 FOREIGN KEY (UNTER_KATEGORIE_ID)
	REFERENCES UNTER_KATEGORIE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_ADRESS ADD CONSTRAINT DECODERADRESS_FK1 FOREIGN KEY (DECODER_ID)
	REFERENCES DECODER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK8 FOREIGN KEY (SONDERMODELL_ID)
	REFERENCES SONDER_MODELL (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ZUG ADD CONSTRAINT ZUG_FK1 FOREIGN KEY (ZUG_TYP_ID)
	REFERENCES ZUG_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK5 FOREIGN KEY (LICHT_ID)
	REFERENCES LICHT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK13 FOREIGN KEY (STEUERUNG_ID)
	REFERENCES STEUERUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK2 FOREIGN KEY (WAHRUNG_ID)
	REFERENCES WAHRUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ZUG_CONSIST ADD CONSTRAINT ZUGCONSIST_FK1 FOREIGN KEY (ZUG_ID)
	REFERENCES ZUG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK11 FOREIGN KEY (KUPPLUNG_ID)
	REFERENCES KUPPLUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT_TEIL ADD CONSTRAINT PRODUKTTEIL_FK2 FOREIGN KEY (TEIL_ID)
	REFERENCES PRODUKT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK16 FOREIGN KEY (HERSTELLER_ID)
	REFERENCES HERSTELLER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK15 FOREIGN KEY (MOTOR_TYP_ID)
	REFERENCES MOTOR_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK6 FOREIGN KEY (SPURWEITE_ID)
	REFERENCES SPURWEITE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_TYP ADD CONSTRAINT DECODERTYP_FK2 FOREIGN KEY (HERSTELLER_ID)
	REFERENCES HERSTELLER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE VORBILD ADD CONSTRAINT VORBILD_FK5 FOREIGN KEY (ACHSFOLG_ID)
	REFERENCES ACHSFOLG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE VORBILD ADD CONSTRAINT VORBILD_FK2 FOREIGN KEY (UNTER_KATEGORIE_ID)
	REFERENCES UNTER_KATEGORIE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK1 FOREIGN KEY (EPOCH_ID)
	REFERENCES EPOCH (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK7 FOREIGN KEY (DECODER_ID)
	REFERENCES DECODER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK9 FOREIGN KEY (AUFBAU_ID)
	REFERENCES AUFBAU (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK3 FOREIGN KEY (STEUERUNG_ID)
	REFERENCES STEUERUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK12 FOREIGN KEY (VORBILD_ID)
	REFERENCES VORBILD (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK4 FOREIGN KEY (MOTOR_TYP_ID)
	REFERENCES MOTOR_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK5 FOREIGN KEY (MASSSTAB_ID)
	REFERENCES MASSSTAB (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK2 FOREIGN KEY (GATTUNG_ID)
	REFERENCES GATTUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT_TEIL ADD CONSTRAINT PRODUKTTEIL_FK1 FOREIGN KEY (PRODUKT_ID)
	REFERENCES PRODUKT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_TYP_CV ADD CONSTRAINT DECODERTYPCV_FK1 FOREIGN KEY (DECODER_TYP_ID)
	REFERENCES DECODER_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE VORBILD ADD CONSTRAINT VORBILD_FK1 FOREIGN KEY (GATTUNG_ID)
	REFERENCES GATTUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_FUNKTION ADD CONSTRAINT DECODERFUNKTION_FK1 FOREIGN KEY (DECODER_ID)
	REFERENCES DECODER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_CV ADD CONSTRAINT DECODERCV_FK2 FOREIGN KEY (CV_ID)
	REFERENCES DECODER_TYP_CV (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK3 FOREIGN KEY (BAHNVERWALTUNG_ID)
	REFERENCES BAHNVERWALTUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK10 FOREIGN KEY (LICHT_ID)
	REFERENCES LICHT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ZUG_CONSIST ADD CONSTRAINT ZUGCONSIST_FK2 FOREIGN KEY (ARTIKEL_ID)
	REFERENCES ARTIKEL (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_TYP ADD CONSTRAINT DECODERTYP_FK3 FOREIGN KEY (PROTOKOLL_ID)
	REFERENCES PROTOKOLL (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK6 FOREIGN KEY (KUPPLUNG_ID)
	REFERENCES KUPPLUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK14 FOREIGN KEY (DECODER_TYP_ID)
	REFERENCES DECODER_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER ADD CONSTRAINT DECODER_FK1 FOREIGN KEY (DECODER_TYP_ID)
	REFERENCES DECODER_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE LAND ADD CONSTRAINT FKD7C3AGPRCPARNMED569N76EIV FOREIGN KEY (WAHRUNG_ID)
	REFERENCES WAHRUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE VORBILD ADD CONSTRAINT VORBILD_FK4 FOREIGN KEY (ANTRIEB_ID)
	REFERENCES ANTRIEB (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

