--<ScriptOptions statementTerminator=";"/>

CREATE TABLE PERSON (
		ID INTEGER NOT NULL,
		CONFIRMATION_TOKEN VARCHAR(255),
		CREDENTIALS_EXPIRED BOOLEAN,
		EMAIL VARCHAR(255) NOT NULL,
		ENABLED BOOLEAN,
		EXPIRED BOOLEAN,
		FIRST_NAME VARCHAR(255) NOT NULL,
		LAST_NAME VARCHAR(255) NOT NULL,
		LOCKED BOOLEAN,
		RESET_TOKEN VARCHAR(255)
	);

CREATE TABLE DECODER_TYP_ADRESS (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		WERKSEINSTELLUNG INTEGER,
		ADRESS_TYP INTEGER NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		INDEX INTEGER NOT NULL,
		SPAN INTEGER NOT NULL,
		DECODER_TYP_ID BIGINT NOT NULL
	);

CREATE TABLE DECODER_TYP_FUNKTION (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100),
		FUNKTION VARCHAR(4),
		PROGRAMMABLE BOOLEAN NOT NULL,
		REIHE INTEGER NOT NULL,
		DECODER_TYP_ID BIGINT NOT NULL
	);

CREATE TABLE VORBILD (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ABBILDUNG VARCHAR(255),
		ANFAHRZUGKRAFT DECIMAL(19 , 2),
		ANZAHL INTEGER,
		AUFBAU VARCHAR(100),
		AUSSERDIENST DATE,
		BAUZEIT DATE,
		BETREIBSNUMMER VARCHAR(100),
		BEZEICHNUNG VARCHAR(100),
		DIENSTGEWICHT DECIMAL(19 , 2),
		DM_LAUFRAD_HINTEN DECIMAL(19 , 2),
		DM_LAUFRAD_VORN DECIMAL(19 , 2),
		DM_TREIBRAD DECIMAL(19 , 2),
		DM_ZYLINDER DECIMAL(19 , 2),
		DREHGESTELL_BAUART VARCHAR(100),
		FAHRMOTOREN INTEGER,
		GESCHWINDIGKEIT INTEGER,
		HERSTELLER VARCHAR(100),
		KAPAZITAT DECIMAL(19 , 2),
		KESSELUBERDRUCK DECIMAL(19 , 2),
		KLASSE INTEGER,
		KOLBENHUB DECIMAL(19 , 2),
		LANGE DECIMAL(19 , 2),
		LEISTUNG DECIMAL(19 , 2),
		LEISTUNGSUBERTRAGUNG VARCHAR(255),
		MITTELWAGEN INTEGER,
		MOTORBAUART VARCHAR(100),
		REICHWEITE DECIMAL(19 , 2),
		ROSTFLACHE DECIMAL(19 , 2),
		SITZPLATZEKL1 INTEGER,
		SITZPLATZEKL2 INTEGER,
		SITZPLATZEKL3 INTEGER,
		SITZPLATZEKL4 INTEGER,
		TRIEBKOPF INTEGER,
		UBERHITZERFLACHE DECIMAL(19 , 2),
		VERDAMPFUNG DECIMAL(19 , 2),
		WASSERVORRAT DECIMAL(19 , 2),
		ZYLINDER INTEGER,
		ACHSFOLG_ID BIGINT NOT NULL,
		ANTRIEB_ID BIGINT NOT NULL,
		BAHNVERWALTUNG_ID BIGINT NOT NULL,
		GATTUNG_ID BIGINT NOT NULL,
		UNTER_KATEGORIE_ID BIGINT NOT NULL
	);

CREATE TABLE PRODUKT_TEIL (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ANZAHL INTEGER NOT NULL,
		PRODUKT_ID BIGINT NOT NULL,
		TEIL_ID BIGINT NOT NULL
	);

CREATE TABLE KUPPLUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL,
		ABBILDUNG VARCHAR(255)
	);

CREATE TABLE flyway_schema_history (
		installed_rank INTEGER NOT NULL,
		version VARCHAR(50),
		description VARCHAR(200) NOT NULL,
		type VARCHAR(20) NOT NULL,
		script VARCHAR(1000) NOT NULL,
		checksum INTEGER,
		installed_by VARCHAR(100) NOT NULL,
		installed_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
		execution_time INTEGER NOT NULL,
		success BOOLEAN NOT NULL
	);

CREATE TABLE GATTUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE EPOCH (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE DECODER_ADRESS (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ADRESS INTEGER NOT NULL,
		DECODER_ID BIGINT NOT NULL,
		ADRESS_ID BIGINT NOT NULL
	);

CREATE TABLE DECODER (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		DECODER_ID VARCHAR(6) NOT NULL,
		FAHRSTUFE INTEGER,
		STATUS VARCHAR(255),
		DECODER_TYP_ID BIGINT NOT NULL,
		PROTOKOLL_ID BIGINT NOT NULL
	);

CREATE TABLE KATEGORIE (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE MOTOR_TYP (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE DECODER_FUNKTION (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		DECODER_ID BIGINT NOT NULL,
		FUNKTION_ID BIGINT NOT NULL
	);

CREATE TABLE ZUG_CONSIST (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		POSITION INTEGER NOT NULL,
		ARTIKEL_ID BIGINT NOT NULL,
		ZUG_ID BIGINT NOT NULL
	);

CREATE TABLE BAHNVERWALTUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL,
		LAND VARCHAR(2)
	);

CREATE TABLE AUFBAU (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL,
		ABBILDUNG VARCHAR(255)
	);

CREATE TABLE LICHT (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL,
		ABBILDUNG VARCHAR(255)
	);

CREATE TABLE DECODER_TYP_CV (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100),
		CV INTEGER NOT NULL,
		MAXIMAL INTEGER,
		MINIMAL INTEGER,
		WERKSEINSTELLUNG INTEGER,
		DECODER_TYP_ID BIGINT NOT NULL
	);

CREATE TABLE ACHSFOLG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE PRODUKT (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ABBILDUNG VARCHAR(255),
		ANLEITUNGEN VARCHAR(512),
		ANMERKUNG VARCHAR(100),
		BAUZEIT DATE,
		BESTELL_NR VARCHAR(50),
		BETREIBSNUMMER VARCHAR(100),
		BEZEICHNUNG VARCHAR(100),
		EXPLOSIONSZEICHNUNG VARCHAR(512),
		LANGE DECIMAL(6 , 2),
		ACHSFOLG_ID BIGINT,
		AUFBAU_ID BIGINT,
		BAHNVERWALTUNG_ID BIGINT,
		DECODER_TYP_ID BIGINT,
		EPOCH_ID BIGINT,
		GATTUNG_ID BIGINT,
		HERSTELLER_ID BIGINT NOT NULL,
		KUPPLUNG_ID BIGINT,
		LICHT_ID BIGINT,
		MASSSTAB_ID BIGINT NOT NULL,
		MOTOR_TYP_ID BIGINT,
		SONDERMODELL_ID BIGINT,
		SPURWEITE_ID BIGINT NOT NULL,
		STEUERUNG_ID BIGINT,
		UNTER_KATEGORIE_ID BIGINT NOT NULL,
		VORBILD_ID BIGINT
	);

CREATE TABLE ZUG_TYP (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE SONDERMODELL (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE ANTRIEB (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE UNTER_KATEGORIE (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50),
		KATEGORIE_ID BIGINT NOT NULL
	);

CREATE TABLE ARTIKEL (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ABBILDUNG VARCHAR(255),
		ANMERKUNG VARCHAR(100),
		ARTIKEL_ID VARCHAR(6) NOT NULL,
		BELADUNG VARCHAR(100),
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		KAUFDATUM DATE,
		PREIS DECIMAL(6 , 2),
		STATUS VARCHAR(255) NOT NULL,
		STUCK INTEGER NOT NULL,
		VERBLEIBENDE INTEGER NOT NULL,
		WAHRUNG VARCHAR(3),
		DECODER_ID BIGINT,
		KUPPLUNG_ID BIGINT,
		LICHT_ID BIGINT,
		MOTOR_TYP_ID BIGINT,
		PRODUKT_ID BIGINT NOT NULL,
		STEUERUNG_ID BIGINT
	);

CREATE TABLE ANDERUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ANDERUNG_ID INTEGER NOT NULL,
		ANDERUNGSDATUM DATE,
		ANDERUNGS_TYP VARCHAR(255) NOT NULL,
		ANMERKUNG VARCHAR(255),
		BEZEICHNUNG VARCHAR(100),
		STUCK INTEGER,
		ARTIKEL_ID BIGINT NOT NULL
	);

CREATE TABLE DECODER_CV (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		WERT INTEGER,
		CV_ID BIGINT NOT NULL,
		DECODER_ID BIGINT NOT NULL
	);

CREATE TABLE PERSON_ROLES (
		PERSON_ID INTEGER NOT NULL,
		ROLES VARCHAR(255)
	);

CREATE TABLE DECODER_TYP (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		ANLEITUNGEN VARCHAR(512),
		BESTELL_NR VARCHAR(50),
		BEZEICHNUNG VARCHAR(100),
		FAHRSTUFE INTEGER,
		I_MAX DECIMAL(6 , 2),
		KONFIGURATION VARCHAR(15) NOT NULL,
		SOUND BOOLEAN NOT NULL,
		STECKER VARCHAR(10) NOT NULL,
		HERSTELLER_ID BIGINT NOT NULL,
		PROTOKOLL_ID BIGINT NOT NULL
	);

CREATE TABLE MASSSTAB (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE ZUG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL,
		ZUG_TYP_ID BIGINT NOT NULL
	);

CREATE TABLE STEUERUNG (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE PROTOKOLL (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE SPURWEITE (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL
	);

CREATE TABLE HERSTELLER (
		ID BIGINT NOT NULL,
		DELETED BOOLEAN NOT NULL,
		BEZEICHNUNG VARCHAR(100) NOT NULL,
		NAME VARCHAR(50) NOT NULL,
		TELEFON VARCHAR(20),
		LAND VARCHAR(2),
		URL VARCHAR(255)
	);

CREATE INDEX PRODUKT_IX16 ON PRODUKT (MOTOR_TYP_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F ON ANDERUNG (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_2 ON ZUG_TYP (ID ASC);

CREATE INDEX DECODERTYPCV_IX1 ON DECODER_TYP_CV (DECODER_TYP_ID ASC);

CREATE INDEX PRODUKT_IX6 ON PRODUKT (MASSSTAB_ID ASC);

CREATE UNIQUE INDEX VORBILD_UC1_INDEX_5 ON VORBILD (GATTUNG_ID ASC);

CREATE INDEX DECODERTYPADRESS_IX2 ON DECODER_TYP_ADRESS (INDEX ASC);

CREATE INDEX PRODUKT_IX13 ON PRODUKT (VORBILD_ID ASC);

CREATE INDEX DECODERTYP_IX1 ON DECODER_TYP (HERSTELLER_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8 ON DECODER (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_FF ON ARTIKEL (ID ASC);

CREATE INDEX VORBILD_IX1 ON VORBILD (UNTER_KATEGORIE_ID ASC);

CREATE INDEX DECODERCV_FK1_INDEX_D ON DECODER_CV (DECODER_ID ASC);

CREATE INDEX PRODUKT_IX15 ON PRODUKT (DECODER_TYP_ID ASC);

CREATE UNIQUE INDEX KATEGORIE_UC1_INDEX_A ON KATEGORIE (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_729 ON DECODER_TYP_FUNKTION (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8C7 ON PERSON (ID ASC);

CREATE INDEX ZUG_IX1 ON ZUG (ZUG_TYP_ID ASC);

CREATE INDEX UNTERKATEGORIE_IX1 ON UNTER_KATEGORIE (KATEGORIE_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_18 ON PRODUKT (ID ASC);

CREATE INDEX VORBILD_FK3_INDEX_5 ON VORBILD (BAHNVERWALTUNG_ID ASC);

CREATE UNIQUE INDEX DECODERCV_UC1_INDEX_D ON DECODER_CV (DECODER_ID ASC, CV_ID ASC);

CREATE INDEX DECODERCV_FK2_INDEX_D ON DECODER_CV (CV_ID ASC);

CREATE INDEX DECODERTYPFUNKTION_IX1 ON DECODER_TYP_FUNKTION (DECODER_TYP_ID ASC);

CREATE INDEX ARTIKEL_IX7 ON ARTIKEL (DECODER_ID ASC);

CREATE INDEX PRODUKTTEIL_IX2 ON PRODUKT_TEIL (TEIL_ID ASC);

CREATE UNIQUE INDEX PROTOKOLL_UC1_INDEX_8 ON PROTOKOLL (NAME ASC);

CREATE UNIQUE INDEX ARTIKEL_UC1_INDEX_F ON ARTIKEL (ARTIKEL_ID ASC);

CREATE UNIQUE INDEX KUPPLUNG_UC1_INDEX_8 ON KUPPLUNG (NAME ASC);

CREATE UNIQUE INDEX MOTORTYP_UC1_INDEX_8 ON MOTOR_TYP (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_15 ON ZUG (ID ASC);

CREATE INDEX VORBILD_IX2 ON VORBILD (ANTRIEB_ID ASC);

CREATE INDEX PRODUKT_IX4 ON PRODUKT (BAHNVERWALTUNG_ID ASC);

CREATE INDEX DECODERFUNKTION_FK2_INDEX_C ON DECODER_FUNKTION (FUNKTION_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6 ON flyway_schema_history (installed_rank ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A5 ON KATEGORIE (ID ASC);

CREATE INDEX ARTIKEL_IX3 ON ARTIKEL (STEUERUNG_ID ASC);

CREATE UNIQUE INDEX ACHSFOLG_UC1_INDEX_B ON ACHSFOLG (NAME ASC);

CREATE UNIQUE INDEX GATTUNG_UC1_INDEX_1 ON GATTUNG (NAME ASC);

CREATE INDEX ZUGCONSIST_IX2 ON ZUG_CONSIST (ARTIKEL_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B ON ACHSFOLG (ID ASC);

CREATE INDEX DECODERTYPADRESS_IX1 ON DECODER_TYP_ADRESS (DECODER_TYP_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_7 ON AUFBAU (ID ASC);

CREATE INDEX ZUGCONSIST_IX1 ON ZUG_CONSIST (ZUG_ID ASC);

CREATE UNIQUE INDEX DECODERADRESS_UC1_INDEX_7 ON DECODER_ADRESS (DECODER_ID ASC, ADRESS_ID ASC);

CREATE INDEX DECODER_IX1 ON DECODER (DECODER_TYP_ID ASC);

CREATE UNIQUE INDEX BAHNVERWALTUNG_UC1_INDEX_C ON BAHNVERWALTUNG (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8E ON MOTOR_TYP (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_83 ON ZUG_CONSIST (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1 ON GATTUNG (ID ASC);

CREATE INDEX VORBILD_IX3 ON VORBILD (ACHSFOLG_ID ASC);

CREATE INDEX ARTIKEL_IX6 ON ARTIKEL (KUPPLUNG_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_CD ON DECODER_FUNKTION (ID ASC);

CREATE UNIQUE INDEX LICHT_UC1_INDEX_4 ON LICHT (NAME ASC);

CREATE INDEX PRODUKT_IX2 ON PRODUKT (EPOCH_ID ASC);

CREATE UNIQUE INDEX AUFBAU_UC1_INDEX_7 ON AUFBAU (NAME ASC);

CREATE INDEX ARTIKEL_IX5 ON ARTIKEL (LICHT_ID ASC);

CREATE INDEX PRODUKT_IX10 ON PRODUKT (AUFBAU_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_4 ON LICHT (ID ASC);

CREATE UNIQUE INDEX DECODERFUNKTION_UC1_INDEX_C ON DECODER_FUNKTION (DECODER_ID ASC, FUNKTION_ID ASC);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success ASC);

CREATE UNIQUE INDEX PRODUKT_UC1_INDEX_1 ON PRODUKT (HERSTELLER_ID ASC, BESTELL_NR ASC);

CREATE UNIQUE INDEX ZUGTYP_UC1_INDEX_2 ON ZUG_TYP (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A ON HERSTELLER (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6F ON PRODUKT_TEIL (ID ASC);

CREATE UNIQUE INDEX PERSON_UC1_INDEX_8 ON PERSON (EMAIL ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_FF1 ON STEUERUNG (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_82 ON PROTOKOLL (ID ASC);

CREATE UNIQUE INDEX EPOCH_UC1_INDEX_3 ON EPOCH (NAME ASC);

CREATE UNIQUE INDEX DECODERTYP_UC1_INDEX_C ON DECODER_TYP (HERSTELLER_ID ASC, BESTELL_NR ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_9 ON DECODER_TYP_CV (ID ASC);

CREATE UNIQUE INDEX STEUERUNG_UC1_INDEX_F ON STEUERUNG (NAME ASC);

CREATE INDEX PRODUKTTEIL_IX1 ON PRODUKT_TEIL (PRODUKT_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C ON BAHNVERWALTUNG (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D9 ON SONDERMODELL (ID ASC);

CREATE INDEX DECODERTYPCV_IX2 ON DECODER_TYP_CV (CV ASC);

CREATE INDEX DECODERADRESS_FK1_INDEX_7 ON DECODER_ADRESS (DECODER_ID ASC);

CREATE INDEX ARTIKEL_IX4 ON ARTIKEL (MOTOR_TYP_ID ASC);

CREATE INDEX PRODUKT_IX11 ON PRODUKT (LICHT_ID ASC);

CREATE UNIQUE INDEX UK_ORDEVYWLK5437FT6BXP996JPE_INDEX_8 ON DECODER (DECODER_ID ASC);

CREATE UNIQUE INDEX DECODERTYPCV_UC1_INDEX_9 ON DECODER_TYP_CV (DECODER_TYP_ID ASC, CV ASC);

CREATE UNIQUE INDEX ZUGCONSIST_UC1_INDEX_8 ON ZUG_CONSIST (ZUG_ID ASC, POSITION ASC);

CREATE INDEX PRODUKT_IX8 ON PRODUKT (UNTER_KATEGORIE_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F6 ON DECODER_TYP_ADRESS (ID ASC);

CREATE UNIQUE INDEX DECODERTYPADRESS_UC1_INDEX_F ON DECODER_TYP_ADRESS (DECODER_TYP_ID ASC, INDEX ASC);

CREATE UNIQUE INDEX ZUG_UC1_INDEX_1 ON ZUG (NAME ASC);

CREATE INDEX PRODUKT_IX1 ON PRODUKT (HERSTELLER_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_3F ON MASSSTAB (ID ASC);

CREATE INDEX ANDERUNG_IX1 ON ANDERUNG (ARTIKEL_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A9 ON SPURWEITE (ID ASC);

CREATE INDEX PRODUKT_IX3 ON PRODUKT (GATTUNG_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D ON DECODER_CV (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_3 ON EPOCH (ID ASC);

CREATE INDEX ARTIKEL_IX1 ON ARTIKEL (PRODUKT_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8C ON KUPPLUNG (ID ASC);

CREATE INDEX ANDERUNG_IX2 ON ANDERUNG (ANDERUNG_ID ASC);

CREATE UNIQUE INDEX DECODERTYPFUNKTION_UC1_INDEX_7 ON DECODER_TYP_FUNKTION (DECODER_TYP_ID ASC, REIHE ASC, FUNKTION ASC);

CREATE UNIQUE INDEX UNTERKATEGORIE_UC1_INDEX_F ON UNTER_KATEGORIE (KATEGORIE_ID ASC, NAME ASC);

CREATE UNIQUE INDEX ANDERUNG_UC1_INDEX_F ON ANDERUNG (ARTIKEL_ID ASC, ANDERUNG_ID ASC);

CREATE UNIQUE INDEX PRODUKTTEIL_UC1_INDEX_6 ON PRODUKT_TEIL (PRODUKT_ID ASC, TEIL_ID ASC);

CREATE UNIQUE INDEX MASSSTAB_UC1_INDEX_3 ON MASSSTAB (NAME ASC);

CREATE UNIQUE INDEX SPURWEITE_UC1_INDEX_A ON SPURWEITE (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_5 ON VORBILD (ID ASC);

CREATE INDEX DECODER_IX2 ON DECODER (PROTOKOLL_ID ASC);

CREATE INDEX PRODUKT_IX5 ON PRODUKT (ACHSFOLG_ID ASC);

CREATE INDEX FKS955LUJ19XYJWI3S1OMO1PGH4_INDEX_A ON PERSON_ROLES (PERSON_ID ASC);

CREATE INDEX PRODUKT_IX7 ON PRODUKT (SPURWEITE_ID ASC);

CREATE INDEX PRODUKT_IX12 ON PRODUKT (KUPPLUNG_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C8 ON DECODER_TYP (ID ASC);

CREATE INDEX PRODUKT_IX14 ON PRODUKT (STEUERUNG_ID ASC);

CREATE UNIQUE INDEX ANTRIEB_UC1_INDEX_F ON ANTRIEB (NAME ASC);

CREATE INDEX DECODERFUNKTION_FK1_INDEX_C ON DECODER_FUNKTION (DECODER_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F8 ON ANTRIEB (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_FB ON UNTER_KATEGORIE (ID ASC);

CREATE INDEX PRODUKT_IX9 ON PRODUKT (SONDERMODELL_ID ASC);

CREATE UNIQUE INDEX HERSTELLER_UC1_INDEX_A ON HERSTELLER (NAME ASC);

CREATE INDEX DECODERTYP_IX2 ON DECODER_TYP (PROTOKOLL_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_72 ON DECODER_ADRESS (ID ASC);

CREATE UNIQUE INDEX SONDERMODELL_UC1_INDEX_D ON SONDERMODELL (NAME ASC);

CREATE INDEX DECODERADRESS_FK2_INDEX_7 ON DECODER_ADRESS (ADRESS_ID ASC);

ALTER TABLE STEUERUNG ADD CONSTRAINT CONSTRAINT_FF1 PRIMARY KEY (ID);

ALTER TABLE DECODER_TYP ADD CONSTRAINT PRIMARY_KEY_C8 UNIQUE (ID);

ALTER TABLE VORBILD ADD CONSTRAINT CONSTRAINT_5 PRIMARY KEY (ID);

ALTER TABLE LICHT ADD CONSTRAINT PRIMARY_KEY_4 UNIQUE (ID);

ALTER TABLE MOTOR_TYP ADD CONSTRAINT PRIMARY_KEY_8E UNIQUE (ID);

ALTER TABLE AUFBAU ADD CONSTRAINT PRIMARY_KEY_7 UNIQUE (ID);

ALTER TABLE GATTUNG ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY (ID);

ALTER TABLE DECODER_TYP ADD CONSTRAINT CONSTRAINT_C8 PRIMARY KEY (ID);

ALTER TABLE PRODUKT ADD CONSTRAINT PRIMARY_KEY_18 UNIQUE (ID);

ALTER TABLE KATEGORIE ADD CONSTRAINT CONSTRAINT_A5 PRIMARY KEY (ID);

ALTER TABLE UNTER_KATEGORIE ADD CONSTRAINT CONSTRAINT_FB PRIMARY KEY (ID);

ALTER TABLE BAHNVERWALTUNG ADD CONSTRAINT PRIMARY_KEY_C UNIQUE (ID);

ALTER TABLE GATTUNG ADD CONSTRAINT PRIMARY_KEY_1 UNIQUE (ID);

ALTER TABLE DECODER_FUNKTION ADD CONSTRAINT CONSTRAINT_CD PRIMARY KEY (ID);

ALTER TABLE PROTOKOLL ADD CONSTRAINT CONSTRAINT_82 PRIMARY KEY (ID);

ALTER TABLE STEUERUNG ADD CONSTRAINT PRIMARY_KEY_FF1 UNIQUE (ID);

ALTER TABLE LICHT ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID);

ALTER TABLE DECODER_TYP_CV ADD CONSTRAINT CONSTRAINT_9 PRIMARY KEY (ID);

ALTER TABLE MASSSTAB ADD CONSTRAINT PRIMARY_KEY_3F UNIQUE (ID);

ALTER TABLE SPURWEITE ADD CONSTRAINT CONSTRAINT_A9 PRIMARY KEY (ID);

ALTER TABLE ZUG_CONSIST ADD CONSTRAINT CONSTRAINT_83 PRIMARY KEY (ID);

ALTER TABLE EPOCH ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID);

ALTER TABLE KUPPLUNG ADD CONSTRAINT CONSTRAINT_8C PRIMARY KEY (ID);

ALTER TABLE SONDERMODELL ADD CONSTRAINT PRIMARY_KEY_D9 UNIQUE (ID);

ALTER TABLE PERSON ADD CONSTRAINT CONSTRAINT_8C7 PRIMARY KEY (ID);

ALTER TABLE ANTRIEB ADD CONSTRAINT CONSTRAINT_F8 PRIMARY KEY (ID);

ALTER TABLE ACHSFOLG ADD CONSTRAINT PRIMARY_KEY_B UNIQUE (ID);

ALTER TABLE DECODER_ADRESS ADD CONSTRAINT CONSTRAINT_72 PRIMARY KEY (ID);

ALTER TABLE flyway_schema_history ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);

ALTER TABLE HERSTELLER ADD CONSTRAINT CONSTRAINT_A PRIMARY KEY (ID);

ALTER TABLE BAHNVERWALTUNG ADD CONSTRAINT CONSTRAINT_C PRIMARY KEY (ID);

ALTER TABLE DECODER_TYP_CV ADD CONSTRAINT PRIMARY_KEY_9 UNIQUE (ID);

ALTER TABLE KATEGORIE ADD CONSTRAINT PRIMARY_KEY_A5 UNIQUE (ID);

ALTER TABLE SPURWEITE ADD CONSTRAINT PRIMARY_KEY_A9 UNIQUE (ID);

ALTER TABLE HERSTELLER ADD CONSTRAINT PRIMARY_KEY_A UNIQUE (ID);

ALTER TABLE MASSSTAB ADD CONSTRAINT CONSTRAINT_3F PRIMARY KEY (ID);

ALTER TABLE MOTOR_TYP ADD CONSTRAINT CONSTRAINT_8E PRIMARY KEY (ID);

ALTER TABLE ACHSFOLG ADD CONSTRAINT CONSTRAINT_B PRIMARY KEY (ID);

ALTER TABLE ARTIKEL ADD CONSTRAINT PRIMARY_KEY_FF UNIQUE (ID);

ALTER TABLE PRODUKT_TEIL ADD CONSTRAINT CONSTRAINT_6 PRIMARY KEY (ID);

ALTER TABLE PROTOKOLL ADD CONSTRAINT PRIMARY_KEY_82 UNIQUE (ID);

ALTER TABLE DECODER_TYP_ADRESS ADD CONSTRAINT CONSTRAINT_F6 PRIMARY KEY (ID);

ALTER TABLE DECODER_TYP_FUNKTION ADD CONSTRAINT PRIMARY_KEY_729 UNIQUE (ID);

ALTER TABLE ZUG ADD CONSTRAINT PRIMARY_KEY_15 UNIQUE (ID);

ALTER TABLE DECODER_TYP_FUNKTION ADD CONSTRAINT CONSTRAINT_729 PRIMARY KEY (ID);

ALTER TABLE UNTER_KATEGORIE ADD CONSTRAINT PRIMARY_KEY_FB UNIQUE (ID);

ALTER TABLE DECODER ADD CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID);

ALTER TABLE PRODUKT ADD CONSTRAINT CONSTRAINT_18 PRIMARY KEY (ID);

ALTER TABLE DECODER_CV ADD CONSTRAINT CONSTRAINT_D PRIMARY KEY (ID);

ALTER TABLE PERSON ADD CONSTRAINT PRIMARY_KEY_8C7 UNIQUE (ID);

ALTER TABLE KUPPLUNG ADD CONSTRAINT PRIMARY_KEY_8C UNIQUE (ID);

ALTER TABLE ANTRIEB ADD CONSTRAINT PRIMARY_KEY_F8 UNIQUE (ID);

ALTER TABLE ANDERUNG ADD CONSTRAINT CONSTRAINT_F PRIMARY KEY (ID);

ALTER TABLE ZUG_TYP ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID);

ALTER TABLE DECODER_TYP_ADRESS ADD CONSTRAINT PRIMARY_KEY_F6 UNIQUE (ID);

ALTER TABLE ARTIKEL ADD CONSTRAINT CONSTRAINT_FF PRIMARY KEY (ID);

ALTER TABLE EPOCH ADD CONSTRAINT PRIMARY_KEY_3 UNIQUE (ID);

ALTER TABLE ZUG_TYP ADD CONSTRAINT PRIMARY_KEY_2 UNIQUE (ID);

ALTER TABLE SONDERMODELL ADD CONSTRAINT CONSTRAINT_D9 PRIMARY KEY (ID);

ALTER TABLE VORBILD ADD CONSTRAINT PRIMARY_KEY_5 UNIQUE (ID);

ALTER TABLE AUFBAU ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY (ID);

ALTER TABLE ZUG ADD CONSTRAINT CONSTRAINT_15 PRIMARY KEY (ID);

ALTER TABLE DECODER ADD CONSTRAINT PRIMARY_KEY_8 UNIQUE (ID);

ALTER TABLE DECODER_CV ADD CONSTRAINT DECODERCV_FK1 FOREIGN KEY (DECODER_ID)
	REFERENCES DECODER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK6 FOREIGN KEY (KUPPLUNG_ID)
	REFERENCES KUPPLUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_CV ADD CONSTRAINT DECODERCV_FK2 FOREIGN KEY (CV_ID)
	REFERENCES DECODER_TYP_CV (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_FUNKTION ADD CONSTRAINT DECODERFUNKTION_FK2 FOREIGN KEY (FUNKTION_ID)
	REFERENCES DECODER_TYP_FUNKTION (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK7 FOREIGN KEY (DECODER_ID)
	REFERENCES DECODER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK3 FOREIGN KEY (STEUERUNG_ID)
	REFERENCES STEUERUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_TYP_ADRESS ADD CONSTRAINT DECODERTYPADRESS_FK1 FOREIGN KEY (DECODER_TYP_ID)
	REFERENCES DECODER_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK12 FOREIGN KEY (VORBILD_ID)
	REFERENCES VORBILD (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_TYP_CV ADD CONSTRAINT DECODERTYPCV_FK1 FOREIGN KEY (DECODER_TYP_ID)
	REFERENCES DECODER_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT_TEIL ADD CONSTRAINT PRODUKTTEIL_FK1 FOREIGN KEY (PRODUKT_ID)
	REFERENCES PRODUKT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK11 FOREIGN KEY (KUPPLUNG_ID)
	REFERENCES KUPPLUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER ADD CONSTRAINT DECODER_FK2 FOREIGN KEY (PROTOKOLL_ID)
	REFERENCES PROTOKOLL (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ZUG_CONSIST ADD CONSTRAINT ZUGCONSIST_FK2 FOREIGN KEY (ARTIKEL_ID)
	REFERENCES ARTIKEL (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK1 FOREIGN KEY (PRODUKT_ID)
	REFERENCES PRODUKT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK1 FOREIGN KEY (EPOCH_ID)
	REFERENCES EPOCH (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ZUG ADD CONSTRAINT ZUG_FK1 FOREIGN KEY (ZUG_TYP_ID)
	REFERENCES ZUG_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PERSON_ROLES ADD CONSTRAINT FKS955LUJ19XYJWI3S1OMO1PGH4 FOREIGN KEY (PERSON_ID)
	REFERENCES PERSON (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE VORBILD ADD CONSTRAINT VORBILD_FK5 FOREIGN KEY (ACHSFOLG_ID)
	REFERENCES ACHSFOLG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK13 FOREIGN KEY (STEUERUNG_ID)
	REFERENCES STEUERUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK15 FOREIGN KEY (MOTOR_TYP_ID)
	REFERENCES MOTOR_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK3 FOREIGN KEY (BAHNVERWALTUNG_ID)
	REFERENCES BAHNVERWALTUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER ADD CONSTRAINT DECODER_FK1 FOREIGN KEY (DECODER_TYP_ID)
	REFERENCES DECODER_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK9 FOREIGN KEY (AUFBAU_ID)
	REFERENCES AUFBAU (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_ADRESS ADD CONSTRAINT DECODERADRESS_FK1 FOREIGN KEY (DECODER_ID)
	REFERENCES DECODER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_TYP ADD CONSTRAINT DECODERTYP_FK2 FOREIGN KEY (HERSTELLER_ID)
	REFERENCES HERSTELLER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK4 FOREIGN KEY (MOTOR_TYP_ID)
	REFERENCES MOTOR_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ZUG_CONSIST ADD CONSTRAINT ZUGCONSIST_FK1 FOREIGN KEY (ZUG_ID)
	REFERENCES ZUG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE UNTER_KATEGORIE ADD CONSTRAINT UNTERKATEGORIE_FK1 FOREIGN KEY (KATEGORIE_ID)
	REFERENCES KATEGORIE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_TYP_FUNKTION ADD CONSTRAINT DECODERTYPFUNKTION_FK1 FOREIGN KEY (DECODER_TYP_ID)
	REFERENCES DECODER_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ANDERUNG ADD CONSTRAINT ANDERUNG_FK1 FOREIGN KEY (ARTIKEL_ID)
	REFERENCES ARTIKEL (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK2 FOREIGN KEY (GATTUNG_ID)
	REFERENCES GATTUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE VORBILD ADD CONSTRAINT VORBILD_FK3 FOREIGN KEY (BAHNVERWALTUNG_ID)
	REFERENCES BAHNVERWALTUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK8 FOREIGN KEY (SONDERMODELL_ID)
	REFERENCES SONDERMODELL (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE VORBILD ADD CONSTRAINT VORBILD_FK4 FOREIGN KEY (ANTRIEB_ID)
	REFERENCES ANTRIEB (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK14 FOREIGN KEY (DECODER_TYP_ID)
	REFERENCES DECODER_TYP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK6 FOREIGN KEY (SPURWEITE_ID)
	REFERENCES SPURWEITE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ARTIKEL ADD CONSTRAINT ARTIKEL_FK5 FOREIGN KEY (LICHT_ID)
	REFERENCES LICHT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK5 FOREIGN KEY (MASSSTAB_ID)
	REFERENCES MASSSTAB (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE VORBILD ADD CONSTRAINT VORBILD_FK2 FOREIGN KEY (UNTER_KATEGORIE_ID)
	REFERENCES UNTER_KATEGORIE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_TYP ADD CONSTRAINT DECODERTYP_FK3 FOREIGN KEY (PROTOKOLL_ID)
	REFERENCES PROTOKOLL (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK7 FOREIGN KEY (UNTER_KATEGORIE_ID)
	REFERENCES UNTER_KATEGORIE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK4 FOREIGN KEY (ACHSFOLG_ID)
	REFERENCES ACHSFOLG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK10 FOREIGN KEY (LICHT_ID)
	REFERENCES LICHT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_ADRESS ADD CONSTRAINT DECODERADRESS_FK2 FOREIGN KEY (ADRESS_ID)
	REFERENCES DECODER_TYP_ADRESS (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE DECODER_FUNKTION ADD CONSTRAINT DECODERFUNKTION_FK1 FOREIGN KEY (DECODER_ID)
	REFERENCES DECODER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT ADD CONSTRAINT PRODUKT_FK16 FOREIGN KEY (HERSTELLER_ID)
	REFERENCES HERSTELLER (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PRODUKT_TEIL ADD CONSTRAINT PRODUKTTEIL_FK2 FOREIGN KEY (TEIL_ID)
	REFERENCES PRODUKT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE VORBILD ADD CONSTRAINT VORBILD_FK1 FOREIGN KEY (GATTUNG_ID)
	REFERENCES GATTUNG (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

