--<ScriptOptions statementTerminator=";"/>

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK15;

ALTER TABLE IF EXISTS VORBILD DROP CONSTRAINT IF EXISTS VORBILD_FK5;

ALTER TABLE IF EXISTS VORBILD DROP CONSTRAINT IF EXISTS VORBILD_FK1;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK8;

ALTER TABLE IF EXISTS DECODER_TYP_ADRESS DROP CONSTRAINT IF EXISTS DECODERTYPADRESS_FK1;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK12;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK13;

ALTER TABLE IF EXISTS DECODER_TYP_FUNKTION DROP CONSTRAINT IF EXISTS DECODERTYPFUNKTION_FK1;

ALTER TABLE IF EXISTS ZUG_CONSIST DROP CONSTRAINT IF EXISTS ZUGCONSIST_FK1;

ALTER TABLE IF EXISTS DECODER DROP CONSTRAINT IF EXISTS DECODER_FK2;

ALTER TABLE IF EXISTS ARTIKEL DROP CONSTRAINT IF EXISTS ARTIKEL_FK7;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK9;

ALTER TABLE IF EXISTS DECODER_TYP DROP CONSTRAINT IF EXISTS DECODERTYP_FK2;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK6;

ALTER TABLE IF EXISTS DECODER_ADRESS DROP CONSTRAINT IF EXISTS DECODERADRESS_FK2;

ALTER TABLE IF EXISTS VORBILD DROP CONSTRAINT IF EXISTS VORBILD_FK3;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK14;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK11;

ALTER TABLE IF EXISTS ZUG DROP CONSTRAINT IF EXISTS ZUG_FK1;

ALTER TABLE IF EXISTS DECODER_TYP_CV DROP CONSTRAINT IF EXISTS DECODERTYPCV_FK1;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK1;

ALTER TABLE IF EXISTS USER_ROLES DROP CONSTRAINT IF EXISTS FK55ITPPKW3I07DO3H7QOCLQD4K;

ALTER TABLE IF EXISTS DECODER DROP CONSTRAINT IF EXISTS DECODER_FK1;

ALTER TABLE IF EXISTS DECODER_CV DROP CONSTRAINT IF EXISTS DECODERCV_FK2;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK5;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK16;

ALTER TABLE IF EXISTS ARTIKEL DROP CONSTRAINT IF EXISTS ARTIKEL_FK1;

ALTER TABLE IF EXISTS ARTIKEL DROP CONSTRAINT IF EXISTS ARTIKEL_FK4;

ALTER TABLE IF EXISTS DECODER_FUNKTION DROP CONSTRAINT IF EXISTS DECODERFUNKTION_FK1;

ALTER TABLE IF EXISTS DECODER_ADRESS DROP CONSTRAINT IF EXISTS DECODERADRESS_FK1;

ALTER TABLE IF EXISTS VORBILD DROP CONSTRAINT IF EXISTS VORBILD_FK2;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK7;

ALTER TABLE IF EXISTS DECODER_CV DROP CONSTRAINT IF EXISTS DECODERCV_FK1;

ALTER TABLE IF EXISTS ANDERUNG DROP CONSTRAINT IF EXISTS ANDERUNG_FK1;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK10;

ALTER TABLE IF EXISTS ARTIKEL DROP CONSTRAINT IF EXISTS ARTIKEL_FK3;

ALTER TABLE IF EXISTS ARTIKEL DROP CONSTRAINT IF EXISTS ARTIKEL_FK5;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK4;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK2;

ALTER TABLE IF EXISTS ZUG_CONSIST DROP CONSTRAINT IF EXISTS ZUGCONSIST_FK2;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRODUKT_FK3;

ALTER TABLE IF EXISTS ARTIKEL DROP CONSTRAINT IF EXISTS ARTIKEL_FK6;

ALTER TABLE IF EXISTS DECODER_TYP DROP CONSTRAINT IF EXISTS DECODERTYP_FK3;

ALTER TABLE IF EXISTS PRODUKT_TEIL DROP CONSTRAINT IF EXISTS PRODUKTTEIL_FK2;

ALTER TABLE IF EXISTS PRODUKT_TEIL DROP CONSTRAINT IF EXISTS PRODUKTTEIL_FK1;

ALTER TABLE IF EXISTS VORBILD DROP CONSTRAINT IF EXISTS VORBILD_FK4;

ALTER TABLE IF EXISTS DECODER_FUNKTION DROP CONSTRAINT IF EXISTS DECODERFUNKTION_FK2;

ALTER TABLE IF EXISTS UNTER_KATEGORIE DROP CONSTRAINT IF EXISTS UNTERKATEGORIE_FK1;

ALTER TABLE IF EXISTS DECODER_FUNKTION DROP CONSTRAINT IF EXISTS CONSTRAINT_CD;

ALTER TABLE IF EXISTS MASSSTAB DROP CONSTRAINT IF EXISTS CONSTRAINT_3F;

ALTER TABLE IF EXISTS KUPPLUNG DROP CONSTRAINT IF EXISTS PRIMARY_KEY_8C;

ALTER TABLE IF EXISTS ANTRIEB DROP CONSTRAINT IF EXISTS PRIMARY_KEY_F8;

ALTER TABLE IF EXISTS SONDER_MODEL DROP CONSTRAINT IF EXISTS CONSTRAINT_D9;

ALTER TABLE IF EXISTS LICHT DROP CONSTRAINT IF EXISTS CONSTRAINT_4;

ALTER TABLE IF EXISTS ANDERUNG DROP CONSTRAINT IF EXISTS CONSTRAINT_F;

ALTER TABLE IF EXISTS ZUG_TYP DROP CONSTRAINT IF EXISTS CONSTRAINT_2E;

ALTER TABLE IF EXISTS flyway_schema_history DROP CONSTRAINT IF EXISTS flyway_schema_history_pk;

ALTER TABLE IF EXISTS KATEGORIE DROP CONSTRAINT IF EXISTS PRIMARY_KEY_A5;

ALTER TABLE IF EXISTS AUFBAU DROP CONSTRAINT IF EXISTS CONSTRAINT_7;

ALTER TABLE IF EXISTS STEUERUNG DROP CONSTRAINT IF EXISTS CONSTRAINT_FF1;

ALTER TABLE IF EXISTS ZUG DROP CONSTRAINT IF EXISTS PRIMARY_KEY_15;

ALTER TABLE IF EXISTS DECODER_TYP_ADRESS DROP CONSTRAINT IF EXISTS PRIMARY_KEY_F6;

ALTER TABLE IF EXISTS EPOCH DROP CONSTRAINT IF EXISTS CONSTRAINT_3;

ALTER TABLE IF EXISTS MASSSTAB DROP CONSTRAINT IF EXISTS PRIMARY_KEY_3F;

ALTER TABLE IF EXISTS KUPPLUNG DROP CONSTRAINT IF EXISTS CONSTRAINT_8C;

ALTER TABLE IF EXISTS SONDER_MODEL DROP CONSTRAINT IF EXISTS PRIMARY_KEY_D9;

ALTER TABLE IF EXISTS VORBILD DROP CONSTRAINT IF EXISTS CONSTRAINT_5;

ALTER TABLE IF EXISTS BAHNVERWALTUNG DROP CONSTRAINT IF EXISTS CONSTRAINT_C;

ALTER TABLE IF EXISTS GATTUNG DROP CONSTRAINT IF EXISTS CONSTRAINT_1;

ALTER TABLE IF EXISTS DECODER DROP CONSTRAINT IF EXISTS PRIMARY_KEY_8;

ALTER TABLE IF EXISTS MOTOR_TYP DROP CONSTRAINT IF EXISTS CONSTRAINT_8E;

ALTER TABLE IF EXISTS ZUG DROP CONSTRAINT IF EXISTS CONSTRAINT_15;

ALTER TABLE IF EXISTS SPURWEITE DROP CONSTRAINT IF EXISTS CONSTRAINT_A9;

ALTER TABLE IF EXISTS ACHSFOLG DROP CONSTRAINT IF EXISTS PRIMARY_KEY_B;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS CONSTRAINT_18;

ALTER TABLE IF EXISTS ARTIKEL DROP CONSTRAINT IF EXISTS PRIMARY_KEY_FF;

ALTER TABLE IF EXISTS PROTOKOLL DROP CONSTRAINT IF EXISTS PRIMARY_KEY_82;

ALTER TABLE IF EXISTS DECODER_TYP_CV DROP CONSTRAINT IF EXISTS PRIMARY_KEY_9;

ALTER TABLE IF EXISTS DECODER_TYP_CV DROP CONSTRAINT IF EXISTS CONSTRAINT_9;

ALTER TABLE IF EXISTS DECODER_CV DROP CONSTRAINT IF EXISTS CONSTRAINT_D;

ALTER TABLE IF EXISTS DECODER_TYP_ADRESS DROP CONSTRAINT IF EXISTS CONSTRAINT_F6;

ALTER TABLE IF EXISTS DECODER_ADRESS DROP CONSTRAINT IF EXISTS CONSTRAINT_72;

ALTER TABLE IF EXISTS BAHNVERWALTUNG DROP CONSTRAINT IF EXISTS PRIMARY_KEY_C;

ALTER TABLE IF EXISTS ACHSFOLG DROP CONSTRAINT IF EXISTS CONSTRAINT_B;

ALTER TABLE IF EXISTS PRODUKT DROP CONSTRAINT IF EXISTS PRIMARY_KEY_18;

ALTER TABLE IF EXISTS MOTOR_TYP DROP CONSTRAINT IF EXISTS PRIMARY_KEY_8E;

ALTER TABLE IF EXISTS PROTOKOLL DROP CONSTRAINT IF EXISTS CONSTRAINT_82;

ALTER TABLE IF EXISTS ZUG_TYP DROP CONSTRAINT IF EXISTS PRIMARY_KEY_2E;

ALTER TABLE IF EXISTS EPOCH DROP CONSTRAINT IF EXISTS PRIMARY_KEY_3;

ALTER TABLE IF EXISTS UNTER_KATEGORIE DROP CONSTRAINT IF EXISTS CONSTRAINT_FB;

ALTER TABLE IF EXISTS ZUG_CONSIST DROP CONSTRAINT IF EXISTS CONSTRAINT_83;

ALTER TABLE IF EXISTS SPURWEITE DROP CONSTRAINT IF EXISTS PRIMARY_KEY_A9;

ALTER TABLE IF EXISTS USER DROP CONSTRAINT IF EXISTS PRIMARY_KEY_2;

ALTER TABLE IF EXISTS PRODUKT_TEIL DROP CONSTRAINT IF EXISTS CONSTRAINT_6;

ALTER TABLE IF EXISTS KATEGORIE DROP CONSTRAINT IF EXISTS CONSTRAINT_A5;

ALTER TABLE IF EXISTS HERSTELLER DROP CONSTRAINT IF EXISTS CONSTRAINT_A;

ALTER TABLE IF EXISTS STEUERUNG DROP CONSTRAINT IF EXISTS PRIMARY_KEY_FF1;

ALTER TABLE IF EXISTS ARTIKEL DROP CONSTRAINT IF EXISTS CONSTRAINT_FF;

ALTER TABLE IF EXISTS USER DROP CONSTRAINT IF EXISTS CONSTRAINT_2;

ALTER TABLE IF EXISTS VORBILD DROP CONSTRAINT IF EXISTS PRIMARY_KEY_5;

ALTER TABLE IF EXISTS DECODER_TYP DROP CONSTRAINT IF EXISTS CONSTRAINT_C8;

ALTER TABLE IF EXISTS LICHT DROP CONSTRAINT IF EXISTS PRIMARY_KEY_4;

ALTER TABLE IF EXISTS UNTER_KATEGORIE DROP CONSTRAINT IF EXISTS PRIMARY_KEY_FB;

ALTER TABLE IF EXISTS ANTRIEB DROP CONSTRAINT IF EXISTS CONSTRAINT_F8;

ALTER TABLE IF EXISTS DECODER_TYP DROP CONSTRAINT IF EXISTS PRIMARY_KEY_C8;

ALTER TABLE IF EXISTS AUFBAU DROP CONSTRAINT IF EXISTS PRIMARY_KEY_7;

ALTER TABLE IF EXISTS GATTUNG DROP CONSTRAINT IF EXISTS PRIMARY_KEY_1;

ALTER TABLE IF EXISTS DECODER_TYP_FUNKTION DROP CONSTRAINT IF EXISTS CONSTRAINT_729;

ALTER TABLE IF EXISTS DECODER_TYP_FUNKTION DROP CONSTRAINT IF EXISTS PRIMARY_KEY_729;

ALTER TABLE IF EXISTS DECODER DROP CONSTRAINT IF EXISTS CONSTRAINT_8;

ALTER TABLE IF EXISTS HERSTELLER DROP CONSTRAINT IF EXISTS PRIMARY_KEY_A;

DROP INDEX IF EXISTS  PRODUKT_IX9;

DROP INDEX IF EXISTS  PRIMARY_KEY_D;

DROP INDEX IF EXISTS  PRIMARY_KEY_2E;

DROP INDEX IF EXISTS  PROTOKOLL_UC1_INDEX_8;

DROP INDEX IF EXISTS  EPOCH_UC1_INDEX_3;

DROP INDEX IF EXISTS  PRIMARY_KEY_15;

DROP INDEX IF EXISTS  VORBILD_FK3_INDEX_5;

DROP INDEX IF EXISTS  PRIMARY_KEY_18;

DROP INDEX IF EXISTS  PRIMARY_KEY_F;

DROP INDEX IF EXISTS  UK_ORDEVYWLK5437FT6BXP996JPE_INDEX_8;

DROP INDEX IF EXISTS  DECODERTYP_IX2;

DROP INDEX IF EXISTS  PRODUKT_IX2;

DROP INDEX IF EXISTS  ANTRIEB_UC1_INDEX_F;

DROP INDEX IF EXISTS  HERSTELLER_UC1_INDEX_A;

DROP INDEX IF EXISTS  PRIMARY_KEY_8C;

DROP INDEX IF EXISTS  PRIMARY_KEY_F8;

DROP INDEX IF EXISTS  DECODERTYPCV_UC1_INDEX_9;

DROP INDEX IF EXISTS  USER_UC1_INDEX_2;

DROP INDEX IF EXISTS  PRODUKT_IX4;

DROP INDEX IF EXISTS  PRODUKT_IX8;

DROP INDEX IF EXISTS  PRIMARY_KEY_A5;

DROP INDEX IF EXISTS  PRIMARY_KEY_F6;

DROP INDEX IF EXISTS  PRODUKT_IX10;

DROP INDEX IF EXISTS  PRODUKT_IX1;

DROP INDEX IF EXISTS  DECODERADRESS_UC1_INDEX_7;

DROP INDEX IF EXISTS  PRODUKT_IX13;

DROP INDEX IF EXISTS  STEUERUNG_UC1_INDEX_F;

DROP INDEX IF EXISTS  DECODERCV_UC1_INDEX_D;

DROP INDEX IF EXISTS  KUPPLUNG_UC1_INDEX_8;

DROP INDEX IF EXISTS  PRIMARY_KEY_83;

DROP INDEX IF EXISTS  ZUGCONSIST_IX1;

DROP INDEX IF EXISTS  DECODER_IX1;

DROP INDEX IF EXISTS  PRIMARY_KEY_1;

DROP INDEX IF EXISTS  PRIMARY_KEY_3F;

DROP INDEX IF EXISTS  ZUGCONSIST_IX2;

DROP INDEX IF EXISTS  DECODERFUNKTION_FK2_INDEX_C;

DROP INDEX IF EXISTS  DECODER_IX2;

DROP INDEX IF EXISTS  PRIMARY_KEY_6;

DROP INDEX IF EXISTS  PRIMARY_KEY_3;

DROP INDEX IF EXISTS  ZUG_UC1_INDEX_1;

DROP INDEX IF EXISTS  ARTIKEL_IX5;

DROP INDEX IF EXISTS  PRODUKTTEIL_IX2;

DROP INDEX IF EXISTS  PRIMARY_KEY_FF1;

DROP INDEX IF EXISTS  DECODERCV_FK2_INDEX_D;

DROP INDEX IF EXISTS  ANDERUNG_IX2;

DROP INDEX IF EXISTS  PRODUKT_IX12;

DROP INDEX IF EXISTS  PRODUKT_IX14;

DROP INDEX IF EXISTS  PRODUKT_IX16;

DROP INDEX IF EXISTS  PRODUKT_IX5;

DROP INDEX IF EXISTS  PRODUKT_IX7;

DROP INDEX IF EXISTS  DECODERTYPADRESS_IX2;

DROP INDEX IF EXISTS  PRIMARY_KEY_72;

DROP INDEX IF EXISTS  PRIMARY_KEY_C8;

DROP INDEX IF EXISTS  PRIMARY_KEY_FF;

DROP INDEX IF EXISTS  PRODUKT_IX15;

DROP INDEX IF EXISTS  PRIMARY_KEY_B;

DROP INDEX IF EXISTS  PRIMARY_KEY_5;

DROP INDEX IF EXISTS  ZUG_IX1;

DROP INDEX IF EXISTS  KATEGORIE_UC1_INDEX_A;

DROP INDEX IF EXISTS  PRIMARY_KEY_FB;

DROP INDEX IF EXISTS  PRIMARY_KEY_CD;

DROP INDEX IF EXISTS  DECODERTYPFUNKTION_IX1;

DROP INDEX IF EXISTS  DECODERTYP_IX1;

DROP INDEX IF EXISTS  DECODERTYPADRESS_UC1_INDEX_F;

DROP INDEX IF EXISTS  PRIMARY_KEY_82;

DROP INDEX IF EXISTS  ZUGTYP_UC1_INDEX_2;

DROP INDEX IF EXISTS  PRODUKT_IX3;

DROP INDEX IF EXISTS  VORBILD_IX2;

DROP INDEX IF EXISTS  PRIMARY_KEY_C;

DROP INDEX IF EXISTS  ARTIKEL_IX7;

DROP INDEX IF EXISTS  flyway_schema_history_s_idx;

DROP INDEX IF EXISTS  PRIMARY_KEY_9;

DROP INDEX IF EXISTS  UNTERKATEGORIE_UC1_INDEX_F;

DROP INDEX IF EXISTS  PRIMARY_KEY_7;

DROP INDEX IF EXISTS  FK55ITPPKW3I07DO3H7QOCLQD4K_INDEX_C;

DROP INDEX IF EXISTS  VORBILD_UC1_INDEX_5;

DROP INDEX IF EXISTS  MASSSTAB_UC1_INDEX_3;

DROP INDEX IF EXISTS  ANDERUNG_UC1_INDEX_F;

DROP INDEX IF EXISTS  PRIMARY_KEY_A;

DROP INDEX IF EXISTS  ACHSFOLG_UC1_INDEX_B;

DROP INDEX IF EXISTS  PRODUKTTEIL_IX1;

DROP INDEX IF EXISTS  ARTIKEL_IX4;

DROP INDEX IF EXISTS  ARTIKEL_UC1_INDEX_F;

DROP INDEX IF EXISTS  PRIMARY_KEY_A9;

DROP INDEX IF EXISTS  ZUGCONSIST_UC1_INDEX_8;

DROP INDEX IF EXISTS  ARTIKEL_IX3;

DROP INDEX IF EXISTS  LICHT_UC1_INDEX_4;

DROP INDEX IF EXISTS  DECODERADRESS_FK1_INDEX_7;

DROP INDEX IF EXISTS  GATTUNG_UC1_INDEX_1;

DROP INDEX IF EXISTS  DECODERFUNKTION_UC1_INDEX_C;

DROP INDEX IF EXISTS  DECODERCV_FK1_INDEX_D;

DROP INDEX IF EXISTS  PRIMARY_KEY_4;

DROP INDEX IF EXISTS  PRIMARY_KEY_6F;

DROP INDEX IF EXISTS  PRIMARY_KEY_D9;

DROP INDEX IF EXISTS  DECODERTYPFUNKTION_UC1_INDEX_7;

DROP INDEX IF EXISTS  PRODUKT_UC1_INDEX_1;

DROP INDEX IF EXISTS  VORBILD_IX3;

DROP INDEX IF EXISTS  DECODERTYPCV_IX1;

DROP INDEX IF EXISTS  MOTORTYP_UC1_INDEX_8;

DROP INDEX IF EXISTS  AUFBAU_UC1_INDEX_7;

DROP INDEX IF EXISTS  PRIMARY_KEY_8E;

DROP INDEX IF EXISTS  DECODERTYP_UC1_INDEX_C;

DROP INDEX IF EXISTS  ARTIKEL_IX1;

DROP INDEX IF EXISTS  PRODUKTTEIL_UC1_INDEX_6;

DROP INDEX IF EXISTS  ANDERUNG_IX1;

DROP INDEX IF EXISTS  DECODERFUNKTION_FK1_INDEX_C;

DROP INDEX IF EXISTS  PRODUKT_IX6;

DROP INDEX IF EXISTS  SPURWEITE_UC1_INDEX_A;

DROP INDEX IF EXISTS  VORBILD_IX1;

DROP INDEX IF EXISTS  PRIMARY_KEY_2;

DROP INDEX IF EXISTS  PRIMARY_KEY_729;

DROP INDEX IF EXISTS  DECODERTYPCV_IX2;

DROP INDEX IF EXISTS  ARTIKEL_IX6;

DROP INDEX IF EXISTS  PRIMARY_KEY_8;

DROP INDEX IF EXISTS  UNTERKATEGORIE_IX1;

DROP INDEX IF EXISTS  DECODERADRESS_FK2_INDEX_7;

DROP INDEX IF EXISTS  SONDERMODEL_UC1_INDEX_D;

DROP INDEX IF EXISTS  DECODERTYPADRESS_IX1;

DROP INDEX IF EXISTS  BAHNVERWALTUNG_UC1_INDEX_C;

DROP INDEX IF EXISTS  PRODUKT_IX11;

DROP TABLE IF EXISTS  ANDERUNG;

DROP TABLE IF EXISTS  HERSTELLER;

DROP TABLE IF EXISTS  DECODER_FUNKTION;

DROP TABLE IF EXISTS  PRODUKT;

DROP TABLE IF EXISTS  ACHSFOLG;

DROP TABLE IF EXISTS  ZUG_TYP;

DROP TABLE IF EXISTS  SONDER_MODEL;

DROP TABLE IF EXISTS  KUPPLUNG;

DROP TABLE IF EXISTS  DECODER_CV;

DROP TABLE IF EXISTS  STEUERUNG;

DROP TABLE IF EXISTS  DECODER_TYP_ADRESS;

DROP TABLE IF EXISTS  ZUG;

DROP TABLE IF EXISTS  SPURWEITE;

DROP TABLE IF EXISTS  PRODUKT_TEIL;

DROP TABLE IF EXISTS  DECODER;

DROP TABLE IF EXISTS  BAHNVERWALTUNG;

DROP TABLE IF EXISTS  ZUG_CONSIST;

DROP TABLE IF EXISTS  MASSSTAB;

DROP TABLE IF EXISTS  USER;

DROP TABLE IF EXISTS  UNTER_KATEGORIE;

DROP TABLE IF EXISTS  LICHT;

DROP TABLE IF EXISTS  MOTOR_TYP;

DROP TABLE IF EXISTS  KATEGORIE;

DROP TABLE IF EXISTS  DECODER_TYP_CV;

DROP TABLE IF EXISTS  ANTRIEB;

DROP TABLE IF EXISTS  GATTUNG;

DROP TABLE IF EXISTS  PROTOKOLL;

DROP TABLE IF EXISTS  VORBILD;

DROP TABLE IF EXISTS  EPOCH;

DROP TABLE IF EXISTS  DECODER_TYP_FUNKTION;

DROP TABLE IF EXISTS  USER_ROLES;

DROP TABLE IF EXISTS  DECODER_TYP;

DROP TABLE IF EXISTS  flyway_schema_history;

DROP TABLE IF EXISTS  DECODER_ADRESS;

DROP TABLE IF EXISTS  AUFBAU;

DROP TABLE IF EXISTS  ARTIKEL;

DROP SEQUENCE IF EXISTS hibernate_sequence;
