--<ScriptOptions statementTerminator=";"/>

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK4;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK3;

ALTER TABLE VORBILD DROP CONSTRAINT VORBILD_FK1;

ALTER TABLE DECODER_TYP_FUNKTION DROP CONSTRAINT DECODERTYPFUNKTION_FK1;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK11;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK3;

ALTER TABLE DECODER_ADRESS DROP CONSTRAINT DECODERADRESS_FK2;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK9;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK6;

ALTER TABLE PRODUKT_TEIL DROP CONSTRAINT PRODUKTTEIL_FK1;

ALTER TABLE VORBILD DROP CONSTRAINT VORBILD_FK5;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK4;

ALTER TABLE DECODER_CV DROP CONSTRAINT DECODERCV_FK1;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK16;

ALTER TABLE VORBILD DROP CONSTRAINT VORBILD_FK4;

ALTER TABLE DECODER_FUNKTION DROP CONSTRAINT DECODERFUNKTION_FK1;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK1;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK10;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK1;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK7;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK5;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK5;

ALTER TABLE PRODUKT_TEIL DROP CONSTRAINT PRODUKTTEIL_FK2;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK15;

ALTER TABLE DECODER_CV DROP CONSTRAINT DECODERCV_FK2;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK6;

ALTER TABLE VORBILD DROP CONSTRAINT VORBILD_FK2;

ALTER TABLE DECODER_FUNKTION DROP CONSTRAINT DECODERFUNKTION_FK2;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK14;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK8;

ALTER TABLE UNTER_KATEGORIE DROP CONSTRAINT UNTERKATEGORIE_FK1;

ALTER TABLE DECODER_TYP DROP CONSTRAINT DECODERTYP_FK2;

ALTER TABLE ZUG_CONSIST DROP CONSTRAINT ZUGCONSIST_FK1;

ALTER TABLE ARTIKEL DROP CONSTRAINT ARTIKEL_FK7;

ALTER TABLE DECODER_TYP_ADRESS DROP CONSTRAINT DECODERTYPADRESS_FK1;

ALTER TABLE DECODER_ADRESS DROP CONSTRAINT DECODERADRESS_FK1;

ALTER TABLE VORBILD DROP CONSTRAINT VORBILD_FK3;

ALTER TABLE ZUG DROP CONSTRAINT ZUG_FK1;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK2;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK13;

ALTER TABLE DECODER_TYP DROP CONSTRAINT DECODERTYP_FK3;

ALTER TABLE DECODER_TYP_CV DROP CONSTRAINT DECODERTYPCV_FK1;

ALTER TABLE DECODER DROP CONSTRAINT DECODER_FK1;

ALTER TABLE ANDERUNG DROP CONSTRAINT ANDERUNG_FK1;

ALTER TABLE PRODUKT DROP CONSTRAINT PRODUKT_FK12;

ALTER TABLE ZUG_CONSIST DROP CONSTRAINT ZUGCONSIST_FK2;

ALTER TABLE USER_ROLES DROP CONSTRAINT FK55ITPPKW3I07DO3H7QOCLQD4K;

ALTER TABLE DECODER DROP CONSTRAINT DECODER_FK2;

ALTER TABLE AUFBAU DROP CONSTRAINT CONSTRAINT_7;

ALTER TABLE PRODUKT_TEIL DROP CONSTRAINT CONSTRAINT_6;

ALTER TABLE ACHSFOLG DROP CONSTRAINT CONSTRAINT_B;

ALTER TABLE DECODER DROP CONSTRAINT CONSTRAINT_8;

ALTER TABLE EPOCH DROP CONSTRAINT PRIMARY_KEY_3;

ALTER TABLE HERSTELLER DROP CONSTRAINT CONSTRAINT_A;

ALTER TABLE KATEGORIE DROP CONSTRAINT CONSTRAINT_A5;

ALTER TABLE SONDER_MODEL DROP CONSTRAINT PRIMARY_KEY_D9;

ALTER TABLE DECODER_ADRESS DROP CONSTRAINT CONSTRAINT_72;

ALTER TABLE ANTRIEB DROP CONSTRAINT PRIMARY_KEY_F8;

ALTER TABLE ARTIKEL DROP CONSTRAINT PRIMARY_KEY_FF;

ALTER TABLE UNTER_KATEGORIE DROP CONSTRAINT CONSTRAINT_FB;

ALTER TABLE STEUERUNG DROP CONSTRAINT PRIMARY_KEY_FF1;

ALTER TABLE MASSSTAB DROP CONSTRAINT PRIMARY_KEY_3F;

ALTER TABLE KUPPLUNG DROP CONSTRAINT CONSTRAINT_8C;

ALTER TABLE SPURWEITE DROP CONSTRAINT CONSTRAINT_A9;

ALTER TABLE BAHNVERWALTUNG DROP CONSTRAINT CONSTRAINT_C;

ALTER TABLE LICHT DROP CONSTRAINT CONSTRAINT_4;

ALTER TABLE GATTUNG DROP CONSTRAINT CONSTRAINT_1;

ALTER TABLE EPOCH DROP CONSTRAINT CONSTRAINT_3;

ALTER TABLE MASSSTAB DROP CONSTRAINT CONSTRAINT_3F;

ALTER TABLE flyway_schema_history DROP CONSTRAINT flyway_schema_history_pk;

ALTER TABLE DECODER_TYP DROP CONSTRAINT CONSTRAINT_C8;

ALTER TABLE SONDER_MODEL DROP CONSTRAINT CONSTRAINT_D9;

ALTER TABLE HERSTELLER DROP CONSTRAINT PRIMARY_KEY_A;

ALTER TABLE ZUG_TYP DROP CONSTRAINT CONSTRAINT_2E;

ALTER TABLE DECODER_CV DROP CONSTRAINT CONSTRAINT_D;

ALTER TABLE SPURWEITE DROP CONSTRAINT PRIMARY_KEY_A9;

ALTER TABLE VORBILD DROP CONSTRAINT CONSTRAINT_5;

ALTER TABLE PRODUKT DROP CONSTRAINT PRIMARY_KEY_18;

ALTER TABLE USER DROP CONSTRAINT PRIMARY_KEY_2;

ALTER TABLE PRODUKT DROP CONSTRAINT CONSTRAINT_18;

ALTER TABLE ZUG_CONSIST DROP CONSTRAINT CONSTRAINT_83;

ALTER TABLE BAHNVERWALTUNG DROP CONSTRAINT PRIMARY_KEY_C;

ALTER TABLE AUFBAU DROP CONSTRAINT PRIMARY_KEY_7;

ALTER TABLE DECODER_FUNKTION DROP CONSTRAINT CONSTRAINT_CD;

ALTER TABLE DECODER_TYP_ADRESS DROP CONSTRAINT CONSTRAINT_F6;

ALTER TABLE ACHSFOLG DROP CONSTRAINT PRIMARY_KEY_B;

ALTER TABLE DECODER_TYP_ADRESS DROP CONSTRAINT PRIMARY_KEY_F6;

ALTER TABLE ARTIKEL DROP CONSTRAINT CONSTRAINT_FF;

ALTER TABLE ANDERUNG DROP CONSTRAINT CONSTRAINT_F;

ALTER TABLE DECODER_TYP_FUNKTION DROP CONSTRAINT PRIMARY_KEY_729;

ALTER TABLE LICHT DROP CONSTRAINT PRIMARY_KEY_4;

ALTER TABLE DECODER_TYP_CV DROP CONSTRAINT CONSTRAINT_9;

ALTER TABLE UNTER_KATEGORIE DROP CONSTRAINT PRIMARY_KEY_FB;

ALTER TABLE GATTUNG DROP CONSTRAINT PRIMARY_KEY_1;

ALTER TABLE ZUG DROP CONSTRAINT CONSTRAINT_15;

ALTER TABLE DECODER DROP CONSTRAINT PRIMARY_KEY_8;

ALTER TABLE KUPPLUNG DROP CONSTRAINT PRIMARY_KEY_8C;

ALTER TABLE DECODER_TYP_FUNKTION DROP CONSTRAINT CONSTRAINT_729;

ALTER TABLE PROTOKOLL DROP CONSTRAINT CONSTRAINT_82;

ALTER TABLE ANTRIEB DROP CONSTRAINT CONSTRAINT_F8;

ALTER TABLE MOTOR_TYP DROP CONSTRAINT CONSTRAINT_8E;

ALTER TABLE STEUERUNG DROP CONSTRAINT CONSTRAINT_FF1;

ALTER TABLE USER DROP CONSTRAINT CONSTRAINT_2;

ALTER TABLE KATEGORIE DROP CONSTRAINT PRIMARY_KEY_A5;

ALTER TABLE DECODER_TYP_CV DROP CONSTRAINT PRIMARY_KEY_9;

ALTER TABLE PROTOKOLL DROP CONSTRAINT PRIMARY_KEY_82;

ALTER TABLE ZUG_TYP DROP CONSTRAINT PRIMARY_KEY_2E;

ALTER TABLE ZUG DROP CONSTRAINT PRIMARY_KEY_15;

ALTER TABLE VORBILD DROP CONSTRAINT PRIMARY_KEY_5;

ALTER TABLE DECODER_TYP DROP CONSTRAINT PRIMARY_KEY_C8;

ALTER TABLE MOTOR_TYP DROP CONSTRAINT PRIMARY_KEY_8E;

DROP INDEX PRIMARY_KEY_A9;

DROP INDEX UNTERKATEGORIE_IX1;

DROP INDEX DECODERADRESS_UC1_INDEX_7;

DROP INDEX GATTUNG_UC1_INDEX_1;

DROP INDEX PRIMARY_KEY_7;

DROP INDEX PRIMARY_KEY_15;

DROP INDEX KUPPLUNG_UC1_INDEX_8;

DROP INDEX ARTIKEL_IX7;

DROP INDEX PRODUKT_IX2;

DROP INDEX PRODUKT_IX8;

DROP INDEX VORBILD_IX2;

DROP INDEX PRIMARY_KEY_729;

DROP INDEX ZUG_UC1_INDEX_1;

DROP INDEX DECODERTYPADRESS_IX1;

DROP INDEX USER_UC1_INDEX_2;

DROP INDEX PRODUKT_IX16;

DROP INDEX DECODERTYPFUNKTION_IX1;

DROP INDEX DECODERTYPCV_UC1_INDEX_9;

DROP INDEX VORBILD_IX3;

DROP INDEX PRIMARY_KEY_C8;

DROP INDEX DECODERFUNKTION_UC1_INDEX_C;

DROP INDEX KATEGORIE_UC1_INDEX_A;

DROP INDEX PRIMARY_KEY_83;

DROP INDEX DECODERCV_FK2_INDEX_D;

DROP INDEX DECODERTYPADRESS_IX2;

DROP INDEX DECODERCV_UC1_INDEX_D;

DROP INDEX DECODERCV_FK1_INDEX_D;

DROP INDEX VORBILD_FK3_INDEX_5;

DROP INDEX HERSTELLER_UC1_INDEX_A;

DROP INDEX PRIMARY_KEY_FF1;

DROP INDEX ARTIKEL_IX5;

DROP INDEX PRIMARY_KEY_FB;

DROP INDEX DECODERTYP_IX2;

DROP INDEX PRIMARY_KEY_72;

DROP INDEX PRODUKT_IX6;

DROP INDEX PRIMARY_KEY_1;

DROP INDEX PRIMARY_KEY_6;

DROP INDEX PRIMARY_KEY_9;

DROP INDEX ZUGCONSIST_IX2;

DROP INDEX SPURWEITE_UC1_INDEX_A;

DROP INDEX LICHT_UC1_INDEX_4;

DROP INDEX ZUGCONSIST_IX1;

DROP INDEX PRODUKT_IX10;

DROP INDEX VORBILD_UC1_INDEX_5;

DROP INDEX ARTIKEL_IX3;

DROP INDEX PRIMARY_KEY_2;

DROP INDEX PRIMARY_KEY_F6;

DROP INDEX PRIMARY_KEY_A;

DROP INDEX MASSSTAB_UC1_INDEX_3;

DROP INDEX PRODUKT_IX14;

DROP INDEX PRIMARY_KEY_D9;

DROP INDEX PRODUKT_IX11;

DROP INDEX SONDERMODEL_UC1_INDEX_D;

DROP INDEX PRIMARY_KEY_A5;

DROP INDEX AUFBAU_UC1_INDEX_7;

DROP INDEX PRODUKT_IX13;

DROP INDEX PRODUKT_IX9;

DROP INDEX PRIMARY_KEY_8E;

DROP INDEX ANTRIEB_UC1_INDEX_F;

DROP INDEX ARTIKEL_IX4;

DROP INDEX PRODUKT_IX4;

DROP INDEX ZUG_IX1;

DROP INDEX ANDERUNG_IX1;

DROP INDEX BAHNVERWALTUNG_UC1_INDEX_C;

DROP INDEX PRODUKTTEIL_IX2;

DROP INDEX PRIMARY_KEY_FF;

DROP INDEX PRODUKT_IX15;

DROP INDEX PRIMARY_KEY_F;

DROP INDEX DECODER_IX2;

DROP INDEX PRIMARY_KEY_6F;

DROP INDEX ANDERUNG_IX2;

DROP INDEX DECODERTYPCV_IX2;

DROP INDEX PRIMARY_KEY_8;

DROP INDEX VORBILD_IX1;

DROP INDEX PRIMARY_KEY_CD;

DROP INDEX DECODER_IX1;

DROP INDEX PRIMARY_KEY_82;

DROP INDEX UNTERKATEGORIE_UC1_INDEX_F;

DROP INDEX PRIMARY_KEY_2E;

DROP INDEX PRIMARY_KEY_F8;

DROP INDEX PRIMARY_KEY_4;

DROP INDEX DECODERTYPADRESS_UC1_INDEX_F;

DROP INDEX DECODERTYP_IX1;

DROP INDEX PRIMARY_KEY_8C;

DROP INDEX PROTOKOLL_UC1_INDEX_8;

DROP INDEX PRODUKTTEIL_UC1_INDEX_6;

DROP INDEX flyway_schema_history_s_idx;

DROP INDEX PRODUKT_UC1_INDEX_1;

DROP INDEX DECODERFUNKTION_FK2_INDEX_C;

DROP INDEX DECODERTYPFUNKTION_UC1_INDEX_7;

DROP INDEX ARTIKEL_IX1;

DROP INDEX EPOCH_UC1_INDEX_3;

DROP INDEX ZUGTYP_UC1_INDEX_2;

DROP INDEX PRODUKT_IX3;

DROP INDEX FK55ITPPKW3I07DO3H7QOCLQD4K_INDEX_C;

DROP INDEX MOTORTYP_UC1_INDEX_8;

DROP INDEX PRIMARY_KEY_3F;

DROP INDEX PRODUKT_IX1;

DROP INDEX PRODUKT_IX7;

DROP INDEX PRIMARY_KEY_B;

DROP INDEX ARTIKEL_IX6;

DROP INDEX ANDERUNG_UC1_INDEX_F;

DROP INDEX PRIMARY_KEY_3;

DROP INDEX ZUGCONSIST_UC1_INDEX_8;

DROP INDEX DECODERFUNKTION_FK1_INDEX_C;

DROP INDEX PRODUKT_IX5;

DROP INDEX PRIMARY_KEY_5;

DROP INDEX PRIMARY_KEY_C;

DROP INDEX DECODERADRESS_FK2_INDEX_7;

DROP INDEX PRODUKTTEIL_IX1;

DROP INDEX ACHSFOLG_UC1_INDEX_B;

DROP INDEX DECODERADRESS_FK1_INDEX_7;

DROP INDEX STEUERUNG_UC1_INDEX_F;

DROP INDEX PRIMARY_KEY_D;

DROP INDEX PRIMARY_KEY_18;

DROP INDEX PRODUKT_IX12;

DROP INDEX DECODERTYP_UC1_INDEX_C;

DROP INDEX UK_ORDEVYWLK5437FT6BXP996JPE_INDEX_8;

DROP INDEX ARTIKEL_UC1_INDEX_F;

DROP INDEX DECODERTYPCV_IX1;

DROP TABLE flyway_schema_history;

DROP TABLE EPOCH;

DROP TABLE MOTOR_TYP;

DROP TABLE USER_ROLES;

DROP TABLE ACHSFOLG;

DROP TABLE AUFBAU;

DROP TABLE DECODER;

DROP TABLE SPURWEITE;

DROP TABLE DECODER_TYP;

DROP TABLE ZUG;

DROP TABLE KATEGORIE;

DROP TABLE VORBILD;

DROP TABLE DECODER_TYP_FUNKTION;

DROP TABLE HERSTELLER;

DROP TABLE DECODER_FUNKTION;

DROP TABLE PROTOKOLL;

DROP TABLE MASSSTAB;

DROP TABLE ANTRIEB;

DROP TABLE ARTIKEL;

DROP TABLE DECODER_TYP_CV;

DROP TABLE STEUERUNG;

DROP TABLE UNTER_KATEGORIE;

DROP TABLE USER;

DROP TABLE BAHNVERWALTUNG;

DROP TABLE ZUG_TYP;

DROP TABLE DECODER_ADRESS;

DROP TABLE ZUG_CONSIST;

DROP TABLE ANDERUNG;

DROP TABLE SONDER_MODEL;

DROP TABLE PRODUKT_TEIL;

DROP TABLE GATTUNG;

DROP TABLE DECODER_CV;

DROP TABLE KUPPLUNG;

DROP TABLE PRODUKT;

DROP TABLE LICHT;

DROP TABLE DECODER_TYP_ADRESS;

