drop table anderung if exists
drop table artikel if exists
drop table decoderAdress if exists;
drop table decoderCV if exists;
drop table decoderFunktion if exists;
drop table produktTeil if exists;
drop table produkt if exists
drop table vorbild if exists;
drop table decoder if exists
drop table decoderTypAdress if exists;
drop table decoderTypCV if exists;
drop table decoderTypFunktion if exists;
drop table achsfolg if exists
drop table antrieb if exists
drop table aufbau if exists
drop table bahnverwaltung if exists
drop table hersteller if exists;
drop table epoch if exists;
drop table gattung if exists;
drop table decoderTyp if exists
drop table kupplung if exists;
drop table licht if exists;
drop table massstab if exists;
drop table motorTyp if exists;
drop table protokoll if exists;
drop table sonderModell if exists;
drop table spurweite if exists;
drop table steuerung if exists;
drop table unterKategorie if exists;
drop table kategorie if exists
drop table wahrung if exists;
drop table land if exists;
drop table zug if exists;
drop table zugConsist if exists;
drop table zugTyp if exists;
drop sequence if exists hibernate_sequence;
COMMIT;