

INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 94);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 95);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 96);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 97);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 98);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 99);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 100);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 101);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 102);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 103);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 104);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 105);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 106);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 107);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 108);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 109);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 110);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 463);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 464);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 465);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 466);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 467);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 468);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 469);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 470);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 471);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 472);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 473);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 474);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 475);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 476);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 477);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 478);
INSERT INTO motorTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 479);
