INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'AB3YGE : AB3yg', 'AB3YGE', 215);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ADümh 101', 'ADUMH101', 216);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ARDümz 106', 'ARDUMZ106', 217);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Apümh 121', 'APUMH121', 218);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Avmz 206', 'AVMZ206', 219);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Avümh 111', 'AVUMH111', 220);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Aüm 203', 'AUM203', 221);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'B3yg', 'B3YGE', 222);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'B4yg', 'B4YGE', 223);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BA 115', 'BA115', 224);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BD3yg', 'BD3YGE', 225);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 03', 'BR03', 226);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 03.10', 'BR03.10', 227);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 103', 'BR103', 228);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 111', 'BR111', 229);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 151', 'BR151', 230);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 211', 'BR211', 231);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 216', 'BR216', 232);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 220', 'BR220', 233);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 230', 'BR230', 234);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 24', 'BR24', 235);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 260', 'BR260', 236);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 321', 'BR321', 237);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 45', 'BR45', 238);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 50', 'BR50', 239);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 53', 'BR53', 240);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 601', 'BR601', 241);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 64', 'BR64', 242);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 701', 'BR701', 243);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 81', 'BR81', 244);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 85', 'BR85', 245);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 86', 'BR86', 246);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 89.0', 'BR89.0', 247);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 96', 'BR96', 248);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 98.3', 'BR98.3', 249);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BT 10', 'BT10', 250);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BTmm 51', 'BTMM51', 251);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bi 18t', 'BI18T', 252);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bi', 'BI', 253);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'DByg 546', 'DBYG546', 254);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'DHG 700C', 'DHG700C', 255);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ELD4', 'ELD4', 256);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ET 403', 'ET403', 257);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ET 91', 'ET91', 258);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'El-u 061', 'ELU061', 259);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'F7', 'F7', 260);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'G 10', 'G10', 261);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Gl', 'GL', 262);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Gmhs 53', 'GMHS53', 263);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Gr 20', 'GR20', 264);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Gs 210', 'GS210', 265);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'H 10', 'H10', 266);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ICR-A10', 'ICRA10', 267);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ICR-B10', 'ICRB10', 268);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ibdlps 383', 'IBDLPS383', 269);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ichqrs 377', 'ICHQRS377', 270);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Kbs 443', 'KBS443', 271);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Kklm 505', 'KKLM505', 272);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Laae 540', 'LAAE540', 273);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Mannschaftswagen 376', 'MANNSCHAFT376', 274);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'NS 6400', 'NS6400', 275);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'OOtz 50', 'OOTZ50', 276);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Om „Breslau“', 'OM', 277);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Om 12', 'OM12', 278);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Otmm 70', 'OTMM70', 279);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pw 90 HzL', 'PW90HZL', 280);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pwg Pr 14', 'PWGPR14', 281);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pwgs 41', 'PWGS41', 282);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pwi 28', 'PWI28', 283);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pwi Wü 13', 'PWIWU13', 284);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'R 02', 'R02', 285);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rlmmps 651', 'RLMMPS651', 286);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rlmms 58', 'RLMMS58', 287);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rlmms', 'RLMMS', 288);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rlmmso 56', 'RLMMSO56', 289);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rs 684', 'RS684', 290);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'SSH 71', 'SSH71', 291);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'SSym „Köln“', 'SSYM', 292);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Samms 709', 'SAMMS709', 293);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Schotterwagen 166', 'SCHOTTERWAGEN166', 294);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Sm 24', 'SM24', 295);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Tehs 50', 'TEHS50', 296);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Tko 02', 'TKO02', 297);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ucs', 'UCS', 298);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'V 200', 'V200', 299);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'V 80', 'V80', 300);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'VS 98', 'VS98', 301);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'VT 75', 'VT75', 302);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'VT 95', 'VT95', 303);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'VT 98', 'VT98', 304);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Viehtransport', 'VIEH', 305);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'WGmh 824', 'WGMH824', 306);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'WRmz 135', 'WRMZ135', 307);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'WRümh 131', 'WRUMH131', 308);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'X05 „Erfurt“', 'X05', 309);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Zces', 'ZCES', 310);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'üm 312', 'UM312', 311);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'üm 313', 'UM313', 312);