INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'C-Sinus', 'CSINUS', 'static/motorTyp/CSINUS/abbildung.png', 463);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'C-Sinus Kompakt', 'KSINUS', 'static/motorTyp/KSINUS/abbildung.png', 464);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Trommelkollektor', 'DCM', 'static/motorTyp/DCM/abbildung.png', 465);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Drehstrom', 'DREHSTROM', 'static/motorTyp/DREHSTROM/abbildung.png', 466);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Glockenanker', 'GLOCKENANKER', 'static/motorTyp/GLOCKENANKER/abbildung.png', 467);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, '5-Stern (DCM)', 'HLM', 'static/motorTyp/HLM/abbildung.png', 468);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, '5-Stern (MS1-7z)', 'HLMMS1-7', 'static/motorTyp/HLMMS1-7/abbildung.png', 469);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, '5-Stern (MS1-8z)', 'HLMMS1-8', 'static/motorTyp/HLMMS1-8/abbildung.png', 470);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, '5-Stern (MS2-7z)', 'HLMMS2-7', 'static/motorTyp/HLMMS2-7/abbildung.png', 471);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, '5-Stern (MS2-8z)', 'HLMMS2-8', 'static/motorTyp/HLMMS2-8/abbildung.png', 472);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, '5-Stern (SFCM)', 'HLMS', 'static/motorTyp/HLMS/abbildung.png', 473);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Scheibenkollektor (MS1-7z)', 'LFCMMS1-7', 'static/motorTyp/LFCMMS1-7/abbildung.png', 474);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Scheibenkollektor (MS1-8z)', 'LFCMMS1-8', 'static/motorTyp/LFCMMS1-8/abbildung.png', 475);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Scheibenkollektor (MS2-7z)', 'LFCMMS2-7', 'static/motorTyp/LFCMMS2-7/abbildung.png', 476);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Scheibenkollektor (MS2-8z)', 'LFCMMS2-8', 'static/motorTyp/LFCMMS2-8/abbildung.png', 477);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'SoftDriveSinus', 'SDSINUS', 'static/motorTyp/SDSINUS/abbildung.png', 478);
INSERT INTO motor_typ (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Scheibenkollektor (klein)', 'SFCM', 'static/motorTyp/SFCM/abbildung.png', 479);
ALTER TABLE motor_typ ALTER COLUMN id RESTART WITH 480;