INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '0 : 1:45 32mm', '0', 398);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '0e : 1:45 16,5mm', '0E', 399);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '0i : 1:45 12mm', '0I', 400);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '0m : 1:45 22,5mm', '0M', 401);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '0p : 1:45 9mm', '0P', 402);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '1\" : 1:12 121mm', '1IN', 403);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '1 : 1:32 45mm', '1', 404);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '1e : 1:32 22,5mm', '1E', 405);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '1i : 1:32 16,5mm', '1I', 406);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '1m : 1:32 32mm', '1M', 407);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '13 : 1:32 28,6mm', '1N3', 408);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, '1p : 1:32 12mm', '1P', 409);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'F : 1:20.32 70.64mm', 'F', 410);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Fn3 : 1:20.32 45mm', 'FN3', 411);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'H0 : 1:87 16,5mm', 'H0', 412);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'H0e : 1:87 9mm', 'H0E', 413);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'H0i : 1:87 6,5mm (H0f)', 'H0I', 414);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'H0m : 1:87 12mm', 'H0M', 415);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'H0p : 1:87 4,5mm', 'H0P', 416);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'HOn2 : 1:87.1 7mm', 'HON2', 417);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'II : 1:22.5 63,5mm', 'II', 418);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'IIe : 1:22.5 32mm', 'IIE', 419);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Iii (NEM) : 1:22.5 22,5mm', 'III-NEM', 420);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'III : 1:16 89mm', 'III', 421);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'IIIe : 1:16 45mm', 'IIIE', 422);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'IIIi (NMRA) : 1:16 32mm (3/4\")', 'IIII-NMRA', 423);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'IIIm : 1:16 63,5mm', 'IIIM', 424);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'IIIp : 1:16 22,5mm', 'IIIP', 425);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'IIm : 1:22.5 45mm', 'IIM', 426);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'IIp : 1:22.5 16,5mm', 'IIP', 427);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'N : 1:160 9mm', 'N', 428);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ne : 1:160 4,5mm (Nn2)', 'NE', 429);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nm : 1:160 6,5mm (Nn3)', 'NM', 430);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'O : 1:48 31.75mm', 'O', 431);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'On2 : 1:48 12,7mm', 'ON2', 432);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'On3 : 1:48 19,4mm ', 'ON3', 433);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'On30 : 1:48 16,5mm', 'ON30', 434);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'OO : 1:76.2 19,05mm', 'OO', 435);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'S : 1:64 22,5mm', 'S', 436);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Se : 1:64 12mm', 'SE', 437);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Si : 1:64 9mm', 'SI', 438);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Sm : 1:64 16,5mm', 'SM', 439);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Sn3 : 1:64 14,3mm', 'SN3', 440);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Sp : 1:64 6,5mm', 'SP', 441);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'TT : 1:120 12mm', 'TT', 442);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'TTe : 1:120 6,5mm', 'TTE', 443);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'TTi : 1:120 4,5mm', 'TTI', 444);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'TTm : 1:120 9mm', 'TTM', 445);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'V : 1:11 127mm', 'V', 446);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ve : 1:11 63,5mm', 'VE', 447);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Vi : 1:11 45mm', 'VI', 448);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'VII : 1:8 184mm', 'VII', 449);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'VIIe : 1:8 89mm', 'VIIE', 450);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'VIIi : 1:8 63,5mm', 'VIII', 451);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'VIIm : 1:8 127mm', 'VIIM', 452);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'VIIp : 1:8 45mm', 'VIIP', 453);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Vm : 1:11 89mm', 'VM', 454);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Vp : 1:11 32mm', 'VP', 455);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'X : 1:5.5 260mm', 'X', 456);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Xe : 1:5.5 127mm', 'XE', 457);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Xi : 1:5.5 89mm', 'XI', 458);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Xm : 1:5.5 184mm', 'XM', 459);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Xp : 1:5.5 63,5mm', 'XP', 460);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Z : 1:220 6,5mm', 'Z', 461);
INSERT INTO massstab (deleted, bezeichnung, name, id) VALUES (FALSE, 'Zm : 1:220 4,5mm', 'ZM', 462);
ALTER TABLE massstab ALTER COLUMN id RESTART WITH 463;