
---------- DATA.SQL
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1 t:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 319};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 320};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 321};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 322};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 323};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 324};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 325};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 326};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 327};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 328};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 329};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 330};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 331};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 332};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 333};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 334};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 335};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 336};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 337};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 338};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 339};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 340};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 341};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 342};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 343};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 344};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 345};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '(1''C)D 3''2''T35', 3: '1CD32T35', 4: 1};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C 1'' h2t', 3: '1C1H2T', 4: 2};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''C h2 3T16', 3: '1CH23T16', 4: 3};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''D 1'' h2t', 3: '1D1H2T', 4: 4};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E 1'' h3 2''3''T28', 3: '1E1H323T28', 4: 5};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E h2 2''2T26 KAB5', 3: '1EH222T26KAB5', 4: 6};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '1''E1'' h2t', 3: '1E1H2T', 4: 7};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C 1'' h3 2''2''T26', 3: '2C1H322T26', 4: 8};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' 2''2''T26', 3: '2C122T26', 4: 9};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '2''C1'' h3 2''2''T40', 3: '2C1H322T40', 4: 10};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'A1 dm', 3: 'A1DM', 4: 11};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'AA dm', 3: 'AADM', 4: 12};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B drn', 3: 'BDRN', 4: 13};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B h2t', 3: 'BH2T', 4: 14};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 3: 'B2DH22222BDH', 4: 15};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' de', 3: 'BBDE', 4: 16};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B'' dh', 3: 'BBDH', 4: 17};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'B''B''', 3: 'BB', 4: 18};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''2'' e', 3: 'BO2E', 4: 19};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+2''2''+Bo''Bo''', 3: 'BOBO22BOBO', 4: 20};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 3: 'BOBOBOBOBOBOBOBO', 4: 21};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C dh', 3: 'CDH', 4: 22};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C h2t', 3: 'CH2T', 4: 23};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C''C'' dh', 3: 'CCDH', 4: 24};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co'' w6gf', 3: 'COCOW6GF', 4: 25};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Co''Co''', 3: 'COCO', 4: 26};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D h2t', 3: 'DH2T', 4: 27};
/*SQL l:73 #:1*/insert into achsfolg (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'D''D h4vt', 3: 'DDH4VT', 4: 28};
