
---------- DATA.SQL
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 304, 5: 310};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 306, 5: 311};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 306, 5: 312};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 306, 5: 313};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 306, 5: 314};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 306, 5: 315};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 307, 5: 316};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 309, 5: 317};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australien', 3: 'AU', 4: 673, 5: 679};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Belgien', 3: 'BE', 4: 675, 5: 680};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschland', 3: 'DE', 4: 675, 5: 681};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Frankreich', 3: 'FR', 4: 675, 5: 682};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Italien', 3: 'IT', 4: 675, 5: 683};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Niederland', 3: 'NL', 4: 675, 5: 684};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 3: 'UK', 4: 676, 5: 685};
/*SQL l:84 #:1*/insert into land (deleted, bezeichnung, name, wahrung_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Vereinigte Staaten', 3: 'US', 4: 678, 5: 686};
