
---------- DATA.SQL
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 117};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 118};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 119};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 120};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 121};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 122};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 123};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 124};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 125};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin'), 3: 'MM', 4: 486};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Insider'), 3: 'INSIDER', 4: 487};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Handler Initiative'), 3: 'MHI', 4: 488};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 3: 'JAHRES', 4: 489};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 3: 'KC', 4: 490};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Einmalige Serien', 3: 'EINMALIGE', 4: 491};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Museumswagen', 3: 'MUSEUM', 4: 492};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Weihnachtswagen', 3: 'WEIHNACHT', 4: 493};
/*SQL l:77 #:1*/insert into sonderModell (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SonderModell', 3: 'SONDER', 4: 494};
