INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Avago Technologies', 'AVAGO', 'US', NULL, 'https://www.broadcom.com/', NULL, 313);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, '4MFOR', '4MFOR', 'DE', '+49 (0) 71 61 608-0', 'https://www.maerklin.de/', NULL, 314);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Artitec', 'ARTITEC', 'NL', NULL, 'http://www.artitec.nl', NULL, 315);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Auhagen', 'AUHAGEN', 'DE', NULL, 'https://auhagen.de/', NULL, 316);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Bochmann und Kochendörfer', 'BK', 'DE', NULL, NULL, NULL, 317);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Brawa', 'BRAWA', 'DE', NULL, 'https://www.brawa.de/', NULL, 318);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Busch Model', 'BUSCH', 'DE', NULL, 'https://www.busch-model.info/', NULL, 319);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'DCC Supplies', 'DCC', 'UK', NULL, 'https://www.dccsupplies.com/', NULL, 320);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Deluxe Materials', 'DELUXE', 'UK', NULL, 'https://deluxematerials.co.uk/', NULL, 321);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Digital-Bahn', 'DIGITALBAHN', 'DE', NULL, 'https://www.digital-bahn.de/', NULL, 322);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Digitrains Ltd', 'DIGITRAINS', 'UK', NULL, 'https://www.digitrains.co.uk/', NULL, 323);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Diotec Semiconductor AG', 'DIOTEC', 'DE', NULL, 'https://diotec.com/en/home.html', NULL, 324);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Erbert Signale', 'ERBERT', 'DE', NULL, 'http://www.erbert-signale.de/', NULL, 325);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Electronic Solutions Ulm', 'ESU', 'DE', NULL, 'http://www.esu.eu/', NULL, 326);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Evergreen Scale Models', 'EVERGREEN', 'US', NULL, 'https://evergreenscalemodels.com/', NULL, 327);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Fairchild Semiconductors', 'FAIRCHILD', 'US', NULL, NULL, NULL, 328);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Faller', 'FALLER', 'DE', NULL, 'https://www.faller.de/', NULL, 329);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Fleischmann', 'FLEISCHMANN', 'DE', NULL, 'https://www.fleischmann.de/', NULL, 330);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Gaßner Beschriftungen', 'GASSNER', 'DE', NULL, 'https://www.gassner-beschriftungen.de/', NULL, 331);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Gauge Master', 'GAUGEMASTER', 'UK', NULL, 'http://www.gaugemaster.com/index.html', NULL, 332);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Heico Modell', 'HEICO', 'DE', NULL, 'http://www.heico-modell.de/', NULL, 333);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Herkat', 'HERKAT', 'DE', NULL, 'http://www.herkat.de/', NULL, 334);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Herpa', 'HERPA', 'DE', NULL, 'https://www.herpa.de/', NULL, 335);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Humbrol', 'HUMBROL', 'UK', NULL, 'https://www.humbrol.com/uk-en/', NULL, 336);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Jordan Modellbau', 'JORDAN', 'DE', NULL, 'http://www.jordan-modellbau.de/', NULL, 337);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Kibri', 'KIBRI', 'DE', NULL, 'https://viessmann-modell.com/', NULL, 338);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Kingbright', 'KINGBRIGHT', 'TW', NULL, 'https://kingbright-europe.de/', NULL, 339);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'KK Produkcja', 'KKPMO', 'PL', NULL, 'http://www.kkpmo.com/', NULL, 340);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'KNIPEX', 'KNIPEX', 'DE', NULL, 'https://www.knipex.com/nc/en/home/', NULL, 341);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Kühn Digital', 'KUHN', 'DE', NULL, 'http://www.kuehn-digital.de/', NULL, 342);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Liliput', 'LILIPUT', 'DE', NULL, 'http://liliput.de/', NULL, 343);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Lima', 'LIMA', 'IT', NULL, 'https://www.hornby.com/', NULL, 344);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Littfinski Daten Technik', 'LDT', 'DE', NULL, 'https://www.ldt-infocenter.com/', NULL, 345);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'LUX-Modellbau', 'LUX', 'DE', NULL, 'https://www.lux-modellbau.de/', NULL, 346);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Maquett', 'MAQUETT', 'NL', NULL, 'https://www.maquett.nl/', NULL, 347);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Märklin', 'MARKLIN', 'DE', '+49 (0) 71 61 608-0', 'https://www.maerklin.de/', NULL, 348);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Mehano', 'MEHANO', 'SI', NULL, 'http://www.mehano.si/', NULL, 349);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Merten', 'MERTEN', 'DE', NULL, 'https://www.preiser.de/', NULL, 350);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Noch', 'NOCH', 'DE', NULL, 'https://www.noch.de/', NULL, 351);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Omron', 'OMRON', 'JP', NULL, 'https://www.omron.com/', NULL, 352);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'POLA', 'POLA', 'DE', NULL, 'https://www.faller.de/', NULL, 353);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Preiser', 'PREISER', 'DE', NULL, 'https://www.preiser.de/', NULL, 354);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Proses', 'PROSES', 'UK', NULL, 'https://proses.com/prestashop/', NULL, 355);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Ratio', 'RATIO', 'UK', NULL, 'https://peco-uk.com/pages/ratio', NULL, 356);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Red Line', 'REDLINE', 'US', NULL, 'http://www.redline.com/', NULL, 357);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Revell', 'REVELL', 'DE', NULL, 'https://www.revell.de/', NULL, 358);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Rivarossi', 'RIVAROSSI', 'IT', NULL, 'https://www.hornby.com/uk-en/shop/brands/rivarossi-h0-1-87.html', NULL, 359);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Roco', 'ROCO', 'AT', NULL, 'https://www.roco.cc/en/home/index.html', NULL, 360);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Schuco', 'SCHUCO', 'DE', NULL, 'https://www.schuco.de/', NULL, 361);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Seuthe Dampf', 'SEUTHE', 'DE', NULL, 'http://seuthe-dampf.de/', NULL, 362);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Taiwan Semiconductor', 'TAIWAN', 'TW', NULL, 'https://www.tsmc.com/english/default.htm', NULL, 363);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Tamiya', 'TAMIYA', 'JP', NULL, 'https://tamiya.com', NULL, 364);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Tams Elektronik', 'TAMS', 'DE', NULL, 'https://tams-online.de/de_DE', NULL, 365);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Tower Pro', 'TOWERPRO', 'TW', NULL, 'http://www.towerpro.com.tw/', NULL, 366);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Trix', 'TRIX', 'DE', '+49 (0) 71 61 608-0', 'https://www.trix.de/', NULL, 367);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'TruOpto', 'TRUOPTO', 'TW', NULL, 'https://www.rapidonline.com/brands/truopto', NULL, 368);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Uhlenbrock', 'UHLENBROCK', 'DE', NULL, 'https://www.uhlenbrock.de/', NULL, 369);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, '', 'UNBEKANT', NULL, NULL, NULL, NULL, 370);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Viessmann Modell', 'VIESSMANN', 'DE', NULL, 'https://viessmann-modell.com/', NULL, 371);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Walthers', 'WALTHERS', 'US', NULL, 'https://www.faller.de/', NULL, 372);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Weinert Modellbau', 'WEINERT', 'DE', NULL, 'https://weinert-modellbau.de/', NULL, 373);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Wiking', 'WIKING', 'DE', NULL, 'https://wiking.de/', NULL, 374);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Woodland Scenics', 'WOODLAND', 'US', NULL, 'https://woodlandscenics.woodlandscenics.com/', NULL, 375);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, abbildung, id) VALUES (FALSE, 'Zimo', 'ZIMO', 'AT', NULL, 'http://www.zimo.at', NULL, 376);
ALTER TABLE hersteller ALTER COLUMN id RESTART WITH 377;