

INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 304, 310);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 306, 311);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 306, 312);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 306, 313);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 306, 314);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 306, 315);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 307, 316);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 309, 317);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Australien', 'AU', 673, 679);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Belgien', 'BE', 675, 680);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Deutschland', 'DE', 675, 681);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Frankreich', 'FR', 675, 682);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Italien', 'IT', 675, 683);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Niederland', 'NL', 675, 684);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, STRINGDECODE('Vereinigtes K\\u00f6nigreich'), 'UK', 676, 685);
INSERT INTO land (deleted, bezeichnung, name, wahrung_id, id) VALUES (FALSE, 'Vereinigte Staaten', 'US', 678, 686);
