INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'AB3yg', 'AB3YGE', 215);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ADümh 101', 'ADUMH-101', 216);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ARDümz 106', 'ARDUMZ-106', 217);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Apümh 121', 'APUMH-121', 218);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Avmz 206', 'AVMZ-206', 219);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Avümh 111', 'AVUMH-111', 220);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Aüm 203', 'AUM-203', 221);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'B3yg', 'B3YGE', 222);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'B4yg', 'B4YGE', 223);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BA 115', 'BA-115', 224);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BD3yg', 'BD3YGE', 225);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 03', 'BR-03', 226);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 03.10', 'BR-03.10', 227);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 103', 'BR-103', 228);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 111', 'BR-111', 229);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 151', 'BR-151', 230);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 211', 'BR-211', 231);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 216', 'BR-216', 232);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 220', 'BR-220', 233);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 230', 'BR-230', 234);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 24', 'BR-24', 235);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 260', 'BR-260', 236);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 321', 'BR-321', 237);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 45', 'BR-45', 238);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 50', 'BR-50', 239);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 53', 'BR-53', 240);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 601', 'BR-601', 241);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 64', 'BR-64', 242);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 701', 'BR-701', 243);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 81', 'BR-81', 244);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 85', 'BR-85', 245);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 86', 'BR-86', 246);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 89.0', 'BR-89.0', 247);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 96', 'BR-96', 248);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BR 98.3', 'BR-98.3', 249);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BT 10', 'BT-10', 250);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'BTmm 51', 'BTMM-51', 251);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bi 18t', 'BI-18T', 252);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bi', 'BI', 253);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'DByg 546', 'DBYG-546', 254);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'DHG 700C', 'DHG-700C', 255);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ELD4', 'ELD4', 256);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ET 403', 'ET-403', 257);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ET 91', 'ET-91', 258);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'El-u 061', 'EL-U-061', 259);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'F7', 'F7', 260);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'G 10', 'G-10', 261);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Gl', 'GL', 262);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Gmhs 53', 'GMHS-53', 263);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Gr 20', 'GR-20', 264);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Gs 210', 'GS-210', 265);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'H 10', 'H-10', 266);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ICR-A10', 'ICR-A10', 267);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ICR-B10', 'ICR-B10', 268);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ibdlps 383', 'IBDLPS-383', 269);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ichqrs 377', 'ICHQRS-377', 270);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Kbs 443', 'KBS-443', 271);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Kklm 505', 'KKLM-505', 272);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Laae 540', 'LAAE-540', 273);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Mannschaftswagen 376', 'MANNSCHAFTSWAGEN-376', 274);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'NS 6400', 'NS-6400', 275);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'OOtz 50', 'OOTZ-50', 276);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Om „Breslau“', 'OM-BRESLAU', 277);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Om 12', 'OM-12', 278);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Otmm 70', 'OTMM-70', 279);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pw 90 HzL', 'PW-90-HZL', 280);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pwg Pr 14', 'PWG-PR-14', 281);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pwgs 41', 'PWGS-41', 282);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pwi 28', 'PWI-28', 283);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pwi Wü 13', 'PWI-WU-13', 284);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'R 02', 'R-02', 285);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rlmmps 651', 'RLMMPS-651', 286);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rlmms 58', 'RLMMS-58', 287);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rlmms', 'RLMMS', 288);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rlmmso 56', 'RLMMSO-56', 289);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rs 684', 'RS-684', 290);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'SSH 71', 'SSH-71', 291);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'SSym „Köln“', 'SSYM-KOLN', 292);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Samms 709', 'SAMMS-709', 293);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Schotterwagen 166', 'SCHOTTERWAGEN-166', 294);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Sm 24', 'SM-24', 295);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Tehs 50', 'TEHS50', 296);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Tko 02', 'TKO02', 297);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ucs', 'UCS', 298);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'V 200', 'V-200', 299);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'V 80', 'V-80', 300);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'VS 98', 'VS-98', 301);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'VT 75', 'VT-75', 302);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'VT 95', 'VT-95', 303);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'VT 98', 'VT-98', 304);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Viehtransport', 'VIEHTRANSPORT', 305);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'WGmh 824', 'WGMH-824', 306);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'WRmz 135', 'WRMZ-135', 307);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'WRümh 131', 'WRUMH-131', 308);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'X05 „Erfurt“', 'X05-ERFURT', 309);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Zces', 'ZCES', 310);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'üm 312', 'UM-312', 311);
INSERT INTO gattung (deleted, bezeichnung, name, id) VALUES (FALSE, 'üm 313', 'UM-313', 312);
ALTER TABLE gattung ALTER COLUMN id RESTART WITH 313;