

INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 117);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 118);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 119);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 120);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 121);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 122);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 123);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 124);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 125);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin'), 'MM', 486);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Insider'), 'INSIDER', 487);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Handler Initiative'), 'MHI', 488);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Magazin Jahreswagen'), 'JAHRES', 489);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Kids Club Jahreswagen'), 'KC', 490);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
INSERT INTO sonderModell (deleted, bezeichnung, name, id) VALUES (FALSE, 'SonderModell', 'SONDER', 494);
