INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Licht', 687, 'K0', FALSE, 1, 692);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Step', 687, 'K1', FALSE, 1, 693);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Turn', 687, 'K2', FALSE, 1, 694);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Richtung', 687, 'K3', FALSE, 1, 695);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 1', 687, 'K4', FALSE, 1, 696);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 2', 687, 'K5', FALSE, 1, 697);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 3', 687, 'K6', FALSE, 1, 698);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 3', 687, 'K7', FALSE, 1, 699);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 4', 687, 'K8', FALSE, 1, 700);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 5', 687, 'K9', FALSE, 1, 701);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 6', 687, 'K10', FALSE, 1, 702);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 7', 687, 'K11', FALSE, 1, 703);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 8', 687, 'K12', FALSE, 1, 704);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 9', 687, 'K13', FALSE, 1, 705);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 10', 687, 'K14', FALSE, 1, 706);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spoke 11', 687, 'K15', FALSE, 1, 707);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 0', 708, 'F0', FALSE, 1, 724);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 0', 725, 'F0', FALSE, 1, 741);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 0', 742, 'F0', FALSE, 1, 766);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 1', 742, 'F1', FALSE, 1, 767);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 2', 742, 'F2', FALSE, 1, 768);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 3', 742, 'F3', FALSE, 1, 769);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 4', 742, 'F4', FALSE, 1, 770);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 5', 742, 'F5', FALSE, 1, 771);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 6', 742, 'F6', FALSE, 1, 772);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 7', 742, 'F7', FALSE, 1, 773);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 8', 742, 'F8', FALSE, 1, 774);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 9', 742, 'F9', FALSE, 1, 775);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 10', 742, 'F10', FALSE, 1, 776);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 11', 742, 'F11', FALSE, 1, 777);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 12', 742, 'F12', FALSE, 1, 778);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 13', 742, 'F13', FALSE, 1, 779);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 14', 742, 'F14', FALSE, 1, 780);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 15', 742, 'F15', FALSE, 1, 781);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 0', 782, 'F0', FALSE, 1, 806);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 1', 782, 'F1', FALSE, 1, 807);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 2', 782, 'F2', FALSE, 1, 808);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 3', 782, 'F3', FALSE, 1, 809);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 4', 782, 'F4', FALSE, 1, 810);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 5', 782, 'F5', FALSE, 1, 811);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 6', 782, 'F6', FALSE, 1, 812);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 7', 782, 'F7', FALSE, 1, 813);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 8', 782, 'F8', FALSE, 1, 814);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 9', 782, 'F9', FALSE, 1, 815);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 10', 782, 'F10', FALSE, 1, 816);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 11', 782, 'F11', FALSE, 1, 817);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 12', 782, 'F12', FALSE, 1, 818);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 13', 782, 'F13', FALSE, 1, 819);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 14', 782, 'F14', FALSE, 1, 820);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 15', 782, 'F15', FALSE, 1, 821);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 0', 822, 'F0', FALSE, 1, 827);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 1', 822, 'F1', FALSE, 1, 828);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 2', 822, 'F2', FALSE, 1, 829);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 3', 822, 'F3', FALSE, 1, 830);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 4', 822, 'F4', FALSE, 1, 831);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 0', 832, 'F0', FALSE, 1, 837);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 1', 832, 'F1', FALSE, 1, 838);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 2', 832, 'F2', FALSE, 1, 839);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 3', 832, 'F3', FALSE, 1, 840);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 4', 832, 'F4', FALSE, 1, 841);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 1', 842, 'K1', FALSE, 1, 865);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 2', 842, 'K2', FALSE, 1, 866);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 3', 842, 'K3', FALSE, 1, 867);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 4', 842, 'K4', FALSE, 1, 868);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 1', 869, 'K1', FALSE, 1, 892);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 2', 869, 'K2', FALSE, 1, 893);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 3', 869, 'K3', FALSE, 1, 894);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Funktion 4', 869, 'K4', FALSE, 1, 895);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Servo 1', 896, 'S1', FALSE, 1, 916);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Servo 2', 896, 'S2', FALSE, 1, 917);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Servo 3', 896, 'S3', FALSE, 1, 918);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Servo 4', 896, 'S4', FALSE, 1, 919);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spitzensignal', 920, 'F0', FALSE, 1, 928);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Rauchgenerator', 920, 'F1', FALSE, 1, 929);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Lokpfeife', 920, 'F2', FALSE, 1, 930);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Fahrger\\u00e4usch'), 920, 'F3', FALSE, 1, 931);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 920, 'F4', FALSE, 1, 932);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Luftpumpe', 920, 'F5', FALSE, 1, 933);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Triebwerksbeleuchtung', 920, 'F6', FALSE, 1, 934);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bremsenquietschen aus', 920, 'F7', FALSE, 1, 935);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Rangierpfeife', 920, 'F8', FALSE, 1, 936);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Dampf ablassen', 920, 'F9', FALSE, 1, 937);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 938, 'F0', FALSE, 1, 941);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 942, 'F0', FALSE, 1, 945);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 946, 'F0', FALSE, 1, 949);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 950, 'F0', FALSE, 1, 953);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 954, 'F0', FALSE, 1, 957);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 958, 'F0', FALSE, 1, 961);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 962, 'F0', FALSE, 1, 965);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 966, 'F0', FALSE, 1, 969);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 970, 'F0', FALSE, 1, 973);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Kranhaus drehen', 974, 'F1', FALSE, 1, 978);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Kranausleger Heben heben', 974, 'F2', FALSE, 1, 979);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Haken heben', 974, 'F3', FALSE, 1, 980);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 981, 'F0', FALSE, 1, 987);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 995, 'F0', FALSE, 1, 1001);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 995, 'F4', FALSE, 1, 1002);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1003, 'F0', FALSE, 1, 1008);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Rauchgenerator', 1003, 'F1', FALSE, 1, 1009);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Lokpfeife', 1003, 'F2', FALSE, 1, 1010);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Dampftriebwerk', 1003, 'F3', FALSE, 1, 1011);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1003, 'F4', FALSE, 1, 1012);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Luftpumpe', 1003, 'F5', FALSE, 1, 1013);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Feuerschein - Feuerb\\u00fcchse'), 1003, 'F6', FALSE, 1, 1014);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bremsenquietschen', 1003, 'F7', FALSE, 1, 1015);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Rangierpfiff', 1003, 'F8', FALSE, 1, 1016);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Dampf ablassen', 1003, 'F9', FALSE, 1, 1017);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Kohleschaufeln', 1003, 'F10', FALSE, 1, 1018);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Sch\\u00fcttelrost'), 1003, 'F11', FALSE, 1, 1019);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1020, 'F0', FALSE, 1, 1024);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Schleuderrad Ger\\u00e4usch'), 1020, 'F1', FALSE, 1, 1025);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Schleuderrad', 1020, 'F2', FALSE, 1, 1026);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Pfeife', 1020, 'F3', FALSE, 1, 1027);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Signalstreckenlampen', 1020, 'F4', FALSE, 1, 1028);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1029, 'F0', FALSE, 1, 1034);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Maschinenraumbeleuchtung', 1029, 'F1', FALSE, 1, 1035);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Stromabnehmer vorn', 1029, 'F2', FALSE, 1, 1036);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Stromabnehmer hinten', 1029, 'F3', FALSE, 1, 1037);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1029, 'F4', FALSE, 1, 1038);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Kohleschaufe schlie\\u00dfen'), 1039, 'F0', FALSE, 1, 1044);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Laufgestell Motoren', 1039, 'F1', FALSE, 1, 1045);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('F\\u00fchrerhaus Beleuchtung'), 1039, 'F2', FALSE, 1, 1046);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Kohleschaufe Heben', 1039, 'F3', FALSE, 1, 1047);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('F\\u00fchrerhaus Drehen'), 1039, 'F4', FALSE, 1, 1048);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1049, 'F0', FALSE, 1, 1055);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Telex-Kupplung', 1049, 'F2', FALSE, 1, 1056);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1049, 'F4', FALSE, 1, 1057);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung / Innenbeleuchtung', 1058, 'F0', FALSE, 1, 1066);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Schlusslicht ausschalten', 1058, 'F1', FALSE, 1, 1067);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Dieselmotor und Bremse', 1058, 'F2', FALSE, 1, 1068);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Signalhorn', 1058, 'F3', FALSE, 1, 1069);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1058, 'F4', FALSE, 1, 1070);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bremsenquietschen', 1058, 'F5', FALSE, 1, 1071);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('T\\u00fcre Zu'), 1058, 'F6', FALSE, 1, 1072);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Glocke', 1058, 'F7', FALSE, 1, 1073);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Abfahrtspfiff', 1058, 'F8', FALSE, 1, 1074);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1075, 'F0', FALSE, 1, 1083);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Rauchgenerator', 1075, 'F1', FALSE, 1, 1084);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Betriebsger\\u00e4usch'), 1075, 'F2', FALSE, 1, 1085);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Pfeife', 1075, 'F3', FALSE, 1, 1086);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1075, 'F4', FALSE, 1, 1087);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Luftpumpe', 1075, 'F5', FALSE, 1, 1088);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Kohleschaufeln', 1075, 'F6', FALSE, 1, 1089);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Glocke', 1075, 'F7', FALSE, 1, 1090);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Dampf ablassen', 1075, 'F8', FALSE, 1, 1091);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bremsenquietschen', 1075, 'F9', FALSE, 1, 1092);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Sch\\u00fcttelrost'), 1075, 'F10', FALSE, 1, 1093);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1094, 'F0', FALSE, 1, 1102);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Betriebsger\\u00e4usch'), 1094, 'F2', FALSE, 1, 1103);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Signalhorn', 1094, 'F3', FALSE, 1, 1104);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1094, 'F4', FALSE, 1, 1105);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bremsenquietschen', 1094, 'F5', FALSE, 1, 1106);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Metalls\\u00e4ge'), 1094, 'F6', FALSE, 1, 1107);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('H\\u00e4mmern'), 1094, 'F7', FALSE, 1, 1108);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Winkelschleifer', 1094, 'F8', FALSE, 1, 1109);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Elektroschwei\\u00dfen'), 1094, 'F9', FALSE, 1, 1110);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Schleifbock', 1094, 'F10', FALSE, 1, 1111);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung / Innenbeleuchtung', 1112, 'F0', FALSE, 1, 1120);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bahnhofsansage', 1112, 'F2', FALSE, 1, 1121);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Signalhorn', 1112, 'F3', FALSE, 1, 1122);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1112, 'F4', FALSE, 1, 1123);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung / Schlusslicht', 1124, 'F0', FALSE, 1, 1132);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Schlusslicht ausschalten', 1124, 'F1', FALSE, 1, 1133);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Betriebsger\\u00e4usch'), 1124, 'F2', FALSE, 1, 1134);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Signalhorn', 1124, 'F3', FALSE, 1, 1135);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1124, 'F4', FALSE, 1, 1136);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Druckluft ablassen', 1124, 'F5', FALSE, 1, 1137);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bremsenquietschen', 1124, 'F6', FALSE, 1, 1138);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1139, 'F0', FALSE, 1, 1148);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Schlusslicht ausschalten', 1139, 'F1', FALSE, 1, 1149);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Betriebsger\\u00e4usch'), 1139, 'F2', FALSE, 1, 1150);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Horn', 1139, 'F3', FALSE, 1, 1151);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1139, 'F4', FALSE, 1, 1152);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Druckluft ablassen', 1139, 'F5', FALSE, 1, 1153);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bremsenquietschen', 1139, 'F6', FALSE, 1, 1154);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('F\\u00fchrerstandsbeleuchtung vorn'), 1139, 'F7', FALSE, 1, 1155);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('F\\u00fchrerstandsbeleuchtung hinten'), 1139, 'F8', FALSE, 1, 1156);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1157, 'F0', FALSE, 1, 1164);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Innenbeleuchtung', 1157, 'F1', FALSE, 1, 1165);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Begr\\u00fc\\u00dfungs-Ansage'), 1157, 'F2', FALSE, 1, 1166);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Pfeife', 1157, 'F3', FALSE, 1, 1167);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1157, 'F4', FALSE, 1, 1168);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Innenbeleuchtung dimmen', 1157, 'F5', FALSE, 1, 1169);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1170, 'F0', FALSE, 1, 1178);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Innenbeleuchtung', 1170, 'F1', FALSE, 1, 1179);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Betriebsger\\u00e4usch '), 1170, 'F2', FALSE, 1, 1180);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Horn', 1170, 'F3', FALSE, 1, 1181);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1170, 'F4', FALSE, 1, 1182);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bremsenquietschen', 1170, 'F5', FALSE, 1, 1183);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bahnhofsansage', 1170, 'F6', FALSE, 1, 1184);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('T\\u00fcre zu'), 1170, 'F7', FALSE, 1, 1185);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Schaffnerpfiff', 1170, 'F8', FALSE, 1, 1186);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Hilfsdiesel', 1170, 'F9', FALSE, 1, 1187);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('L\\u00fcfter'), 1170, 'F10', FALSE, 1, 1188);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Kompressor', 1170, 'F11', FALSE, 1, 1189);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('\\u00dcberdruckventil'), 1170, 'F12', FALSE, 1, 1190);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Druckluft ablassen', 1170, 'F13', FALSE, 1, 1191);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1192, 'F0', FALSE, 1, 1200);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Tischlampen', 1192, 'F1', FALSE, 1, 1201);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Betriebsger\\u00e4usch'), 1192, 'F2', FALSE, 1, 1202);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Horn', 1192, 'F3', FALSE, 1, 1203);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1192, 'F4', FALSE, 1, 1204);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bremsenquietschen', 1192, 'F5', FALSE, 1, 1205);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Schaffnerpfiff', 1192, 'F6', FALSE, 1, 1206);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('T\\u00fcren'), 1192, 'F7', FALSE, 1, 1207);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bahnhofsansage', 1192, 'F8', FALSE, 1, 1208);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Rangierpfiff', 1192, 'F9', FALSE, 1, 1209);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Innenbeleuchtung', 1210, 'F0', FALSE, 1, 1218);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Start / Stopp', 1210, 'F1', FALSE, 1, 1219);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Pause', 1210, 'F2', FALSE, 1, 1220);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ein Lied vor', 1210, 'F3', FALSE, 1, 1221);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('ein Lied zur\\u00fcck'), 1210, 'F4', FALSE, 1, 1222);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Lauter', 1210, 'F5', FALSE, 1, 1223);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Leiser', 1210, 'F6', FALSE, 1, 1224);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Lichtorgel an / aus', 1210, 'F7', FALSE, 1, 1225);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Barbeleuchtung an / aus', 1210, 'F8', FALSE, 1, 1226);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Strom f\\u00fchrende Kupplung'), 1210, 'F9', FALSE, 1, 1227);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Stroboskop', 1210, 'F10', FALSE, 1, 1228);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Umgebungsger\\u00e4usch 1'), 1210, 'F11', FALSE, 1, 1229);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Umgebungsger\\u00e4usch 2'), 1210, 'F12', FALSE, 1, 1230);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Betriebsger\\u00e4usch 1'), 1210, 'F13', FALSE, 1, 1231);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Betriebsger\\u00e4usch 2'), 1210, 'F14', FALSE, 1, 1232);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Betriebsger\\u00e4usch 3'), 1210, 'F15', FALSE, 1, 1233);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spitzensignal', 1234, 'F0', FALSE, 1, 1243);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Innenbeleuchtung', 1234, 'F1', FALSE, 1, 1244);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Fahrger\\u00e4usch'), 1234, 'F2', FALSE, 1, 1245);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Signalton', 1234, 'F3', FALSE, 1, 1246);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Direktsteuerung', 1234, 'F4', FALSE, 1, 1247);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bremsenquietschen aus', 1234, 'F5', FALSE, 1, 1248);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spitzensignal Lokseite 2', 1234, 'F6', FALSE, 1, 1249);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Schaffnerpfiff', 1234, 'F7', FALSE, 1, 1250);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Spitzensignal Lokseite 1', 1234, 'F8', FALSE, 1, 1251);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('T\\u00fcrenschlie\\u00dfen'), 1234, 'F9', FALSE, 1, 1252);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Schienensto\\u00df'), 1234, 'F10', FALSE, 1, 1253);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Bahnhofsansage', 1234, 'F11', FALSE, 1, 1254);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Dialog', 1234, 'F12', FALSE, 1, 1255);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Dialog', 1234, 'F13', FALSE, 1, 1256);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Dialog', 1234, 'F14', FALSE, 1, 1257);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Dialog ', 1234, 'F15', FALSE, 1, 1258);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Arbeitsb\\u00fchne heben'), 1259, 'F1', FALSE, 1, 1262);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Arbeitsb\\u00fchne schwenken'), 1259, 'F2', FALSE, 1, 1263);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Stromabnehmer', 1259, 'F3', FALSE, 1, 1264);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Initialisierung', 1259, 'F4', FALSE, 1, 1265);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1271, 'F0', FALSE, 1, 1278);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1271, 'F4', FALSE, 1, 1279);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1280, 'F0', FALSE, 1, 1284);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Pantograf', 1285, 'F2', FALSE, 1, 1293);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Ger\\u00e4usch einer Schaffner'), 1285, 'F3', FALSE, 1, 1294);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Me\\u00dfbereich'), 1295, 'F1', FALSE, 1, 1298);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Me\\u00dfbereich'), 1295, 'F2', FALSE, 1, 1299);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, STRINGDECODE('Ma\\u00dfeinheit'), 1295, 'F3', FALSE, 1, 1300);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Anzeigen', 1295, 'F4', FALSE, 1, 1301);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'Strinbeleuchtung', 1302, 'F0', FALSE, 1, 1307);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, reihe, id) VALUES (FALSE, 'ABV', 1302, 'F4', FALSE, 1, 1308);