

INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 8);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 9);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 10);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 11);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 12);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 13);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Relex Kupplung', 'RELEX', NULL, 377);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen mit Drehpunkt'), 'KK', NULL, 378);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Drehpunkt'), 'NEM', NULL, 379);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Kulissenf\\u00fchrung'), 'NEMKK', NULL, 380);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin-Kurzkupplungen in Norm-Aufnahme mit Stromf\\u00fcrhrender Kulissenf\\u00fchrung'), 'SFKK', NULL, 381);
INSERT INTO kupplung (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Telex Kupplung', 'TELEX', NULL, 382);
