

INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 304);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 305);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 306);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 307);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 308);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 309);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Australian Dollar', 'AUD', 2, 673);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Deutschemark', 'DEM', 2, 674);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Euro', 'EUR', 2, 675);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Pound Serling', 'GBP', 2, 676);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'Hong Kong Dollar', 'HKD', 2, 677);
INSERT INTO wahrung (deleted, bezeichnung, name, dezimal, id) VALUES (FALSE, 'US Dollar', 'USD', 2, 678);
