INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Christkindlesmarkt', 'CHRISTKINDLE', 496);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 491);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Eurotrain exclisiv', 'EUROTRAIN', 497);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, '1. FC Märklin Jahreswagen', 'FC', 495);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Idee+Spiel', 'IDEE+SPIEL', 498);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Märklin Insider', 'INSIDER', 487);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Märklin Magazin Jahreswagen', 'JAHRES', 489);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Märklin Kids Club Jahreswagen', 'KC', 490);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Märklin Handler Initiative', 'MHI', 488);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Märklin Magazin', 'MM', 486);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumswagen', 'MUSEUM', 492);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Sonder Model', 'SONDER', 494);
INSERT INTO sondermodell (deleted, bezeichnung, name, id) VALUES (FALSE, 'Weihnachtswagen', 'WEIHNACHT', 493);
ALTER TABLE sondermodell ALTER COLUMN id RESTART WITH 499;