
---------- DATA.SQL
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1417};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1423};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1422, 5: 1424};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('G\\u00fctterzug'), 3: 'GUTTERZUG', 4: 1418};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Nahvekerszug', 3: 'NAHVEKERS', 4: 1419};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Bahndienstzug', 3: 'BAHNDIENST', 4: 1420};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Interregiozug', 3: 'IR', 4: 1421};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Intercityzug', 3: 'IC', 4: 1422};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'TEE Zug', 3: 'TEE', 4: 1423};
/*SQL l:71 #:1*/insert into zugTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('Milit\\u00e4r Zug'), 3: 'MILITAR', 4: 1424};
/*SQL l:82 #:1*/insert into zug (deleted, bezeichnung, name, zugTyp_id, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('TEE \\u201eBavaria\\u201c'), 3: 'BAVARIA', 4: 1423, 5: 1425};
