INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Licht', 687, 'K0', TRUE, 692);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Step', 687, 'K1', TRUE, 693);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Turn', 687, 'K2', TRUE, 694);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Richtung', 687, 'K3', TRUE, 695);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 1', 687, 'K4', TRUE, 696);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 2', 687, 'K5', TRUE, 697);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 3', 687, 'K6', TRUE, 698);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 3', 687, 'K7', TRUE, 699);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 4', 687, 'K8', TRUE, 700);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 5', 687, 'K9', TRUE, 701);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 6', 687, 'K10', TRUE, 702);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 7', 687, 'K11', TRUE, 703);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 8', 687, 'K12', TRUE, 704);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 9', 687, 'K13', TRUE, 705);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 10', 687, 'K14', TRUE, 706);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spoke 11', 687, 'K15', TRUE, 707);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 0', 708, 'F0', TRUE, 724);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 1', 708, 'F1', TRUE, 1309);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 2', 708, 'F2', TRUE, 1310);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 3', 708, 'F3', TRUE, 1311);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 4', 708, 'F4', TRUE, 1312);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 5', 708, 'F5', TRUE, 1313);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 0', 725, 'F0', TRUE, 741);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 1', 725, 'F1', TRUE, 1314);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 2', 725, 'F2', TRUE, 1315);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 3', 725, 'F3', TRUE, 1316);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 4', 725, 'F4', TRUE, 1317);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 5', 725, 'F5', TRUE, 1318);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 0', 742, 'F0', TRUE, 766);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 1', 742, 'F1', TRUE, 767);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 2', 742, 'F2', TRUE, 768);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 3', 742, 'F3', TRUE, 769);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 4', 742, 'F4', TRUE, 770);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 5', 742, 'F5', TRUE, 771);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 6', 742, 'F6', TRUE, 772);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 7', 742, 'F7', TRUE, 773);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 8', 742, 'F8', TRUE, 774);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 9', 742, 'F9', TRUE, 775);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 10', 742, 'F10', TRUE, 776);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 11', 742, 'F11', TRUE, 777);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 12', 742, 'F12', TRUE, 778);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 13', 742, 'F13', TRUE, 779);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 14', 742, 'F14', TRUE, 780);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 15', 742, 'F15', TRUE, 781);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 0', 782, 'F0', TRUE, 806);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 1', 782, 'F1', TRUE, 807);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 2', 782, 'F2', TRUE, 808);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 3', 782, 'F3', TRUE, 809);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 4', 782, 'F4', TRUE, 810);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 5', 782, 'F5', TRUE, 811);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 6', 782, 'F6', TRUE, 812);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 7', 782, 'F7', TRUE, 813);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 8', 782, 'F8', TRUE, 814);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 9', 782, 'F9', TRUE, 815);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 10', 782, 'F10', TRUE, 816);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 11', 782, 'F11', TRUE, 817);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 12', 782, 'F12', TRUE, 818);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 13', 782, 'F13', TRUE, 819);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 14', 782, 'F14', TRUE, 820);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 15', 782, 'F15', TRUE, 821);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 0', 822, 'F0', TRUE, 827);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 1', 822, 'F1', TRUE, 828);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 2', 822, 'F2', TRUE, 829);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 3', 822, 'F3', TRUE, 830);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 4', 822, 'F4', TRUE, 831);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 5', 822, 'F5', TRUE, 1319);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 0', 832, 'F0', TRUE, 837);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 1', 832, 'F1', TRUE, 838);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 2', 832, 'F2', TRUE, 839);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 3', 832, 'F3', TRUE, 840);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 4', 832, 'F4', TRUE, 841);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 5', 832, 'F5', TRUE, 1320);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 1', 842, 'K1', TRUE, 865);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 2', 842, 'K2', TRUE, 866);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 3', 842, 'K3', TRUE, 867);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 4', 842, 'K4', TRUE, 868);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Servo 1', 842, 'S1', TRUE, 1321);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Servo 2', 842, 'S2', TRUE, 1322);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 1', 869, 'K1', TRUE, 892);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 2', 869, 'K2', TRUE, 893);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 3', 869, 'K3', TRUE, 894);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Funktion 4', 869, 'K4', TRUE, 895);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Servo 1', 869, 'S1', TRUE, 1323);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Servo 2', 869, 'S2', TRUE, 1324);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Servo 1', 896, 'S1', TRUE, 916);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Servo 2', 896, 'S2', TRUE, 917);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Servo 3', 896, 'S3', TRUE, 918);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Servo 4', 896, 'S4', TRUE, 919);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spitzensignal', 920, 'F0', FALSE, 928);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Rauchgenerator', 920, 'F1', FALSE, 929);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Lokpfeife', 920, 'F2', FALSE, 930);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Fahrgeräusch', 920, 'F3', FALSE, 931);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 920, 'F4', FALSE, 932);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Luftpumpe', 920, 'F5', FALSE, 933);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Triebwerksbeleuchtung', 920, 'F6', FALSE, 934);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bremsenquietschen aus', 920, 'F7', FALSE, 935);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Rangierpfeife', 920, 'F8', FALSE, 936);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Dampf ablassen', 920, 'F9', FALSE, 937);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 938, 'F0', FALSE, 941);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 942, 'F0', FALSE, 945);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 946, 'F0', FALSE, 949);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 950, 'F0', FALSE, 953);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 954, 'F0', FALSE, 957);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 958, 'F0', FALSE, 961);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 962, 'F0', FALSE, 965);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 966, 'F0', FALSE, 969);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 970, 'F0', FALSE, 973);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Direktsteuerung', 970, 'F4', FALSE, 1325);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Kranhaus drehen', 974, 'F1', FALSE, 978);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Kranausleger Heben heben', 974, 'F2', FALSE, 979);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Haken heben', 974, 'F3', FALSE, 980);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 981, 'F0', FALSE, 987);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 995, 'F0', FALSE, 1001);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 995, 'F4', FALSE, 1002);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1003, 'F0', FALSE, 1008);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Rauchgenerator', 1003, 'F1', FALSE, 1009);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Lokpfeife', 1003, 'F2', FALSE, 1010);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Dampftriebwerk', 1003, 'F3', FALSE, 1011);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1003, 'F4', FALSE, 1012);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Luftpumpe', 1003, 'F5', FALSE, 1013);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Feuerschein - Feuerbüchse', 1003, 'F6', FALSE, 1014);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bremsenquietschen', 1003, 'F7', FALSE, 1015);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Rangierpfiff', 1003, 'F8', FALSE, 1016);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Dampf ablassen', 1003, 'F9', FALSE, 1017);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Kohleschaufeln', 1003, 'F10', FALSE, 1018);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schüttelrost', 1003, 'F11', FALSE, 1019);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1020, 'F0', FALSE, 1024);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schleuderrad Geräusch', 1020, 'F1', FALSE, 1025);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schleuderrad', 1020, 'F2', FALSE, 1026);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Pfeife', 1020, 'F3', FALSE, 1027);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Signalstreckenlampen', 1020, 'F4', FALSE, 1028);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1029, 'F0', FALSE, 1034);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Maschinenraumbeleuchtung', 1029, 'F1', FALSE, 1035);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Stromabnehmer vorn', 1029, 'F2', FALSE, 1036);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Stromabnehmer hinten', 1029, 'F3', FALSE, 1037);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1029, 'F4', FALSE, 1038);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Kohleschaufe schließen', 1039, 'F0', FALSE, 1044);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Laufgestell Motoren', 1039, 'F1', FALSE, 1045);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Führerhaus Beleuchtung', 1039, 'F2', FALSE, 1046);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Kohleschaufe Heben', 1039, 'F3', FALSE, 1047);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Führerhaus Drehen', 1039, 'F4', FALSE, 1048);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1049, 'F0', FALSE, 1055);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Telex-Kupplung', 1049, 'F2', FALSE, 1056);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1049, 'F4', FALSE, 1057);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung / Innenbeleuchtung', 1058, 'F0', FALSE, 1066);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schlusslicht ausschalten', 1058, 'F1', FALSE, 1067);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Dieselmotor und Bremse', 1058, 'F2', FALSE, 1068);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Signalhorn', 1058, 'F3', FALSE, 1069);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1058, 'F4', FALSE, 1070);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bremsenquietschen', 1058, 'F5', FALSE, 1071);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Türe Zu', 1058, 'F6', FALSE, 1072);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Glocke', 1058, 'F7', FALSE, 1073);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Abfahrtspfiff', 1058, 'F8', FALSE, 1074);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1075, 'F0', FALSE, 1083);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Rauchgenerator', 1075, 'F1', FALSE, 1084);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Betriebsgeräusch', 1075, 'F2', FALSE, 1085);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Pfeife', 1075, 'F3', FALSE, 1086);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1075, 'F4', FALSE, 1087);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Luftpumpe', 1075, 'F5', FALSE, 1088);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Kohleschaufeln', 1075, 'F6', FALSE, 1089);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Glocke', 1075, 'F7', FALSE, 1090);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Dampf ablassen', 1075, 'F8', FALSE, 1091);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bremsenquietschen', 1075, 'F9', FALSE, 1092);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schüttelrost', 1075, 'F10', FALSE, 1093);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1094, 'F0', FALSE, 1102);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Betriebsgeräusch', 1094, 'F2', FALSE, 1103);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Signalhorn', 1094, 'F3', FALSE, 1104);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1094, 'F4', FALSE, 1105);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bremsenquietschen', 1094, 'F5', FALSE, 1106);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Metallsäge', 1094, 'F6', FALSE, 1107);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Hämmern', 1094, 'F7', FALSE, 1108);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Winkelschleifer', 1094, 'F8', FALSE, 1109);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Elektroschweißen', 1094, 'F9', FALSE, 1110);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schleifbock', 1094, 'F10', FALSE, 1111);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung / Innenbeleuchtung', 1112, 'F0', FALSE, 1120);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bahnhofsansage', 1112, 'F2', FALSE, 1121);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Signalhorn', 1112, 'F3', FALSE, 1122);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1112, 'F4', FALSE, 1123);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung / Schlusslicht', 1124, 'F0', FALSE, 1132);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schlusslicht ausschalten', 1124, 'F1', FALSE, 1133);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Betriebsgeräusch', 1124, 'F2', FALSE, 1134);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Signalhorn', 1124, 'F3', FALSE, 1135);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1124, 'F4', FALSE, 1136);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Druckluft ablassen', 1124, 'F5', FALSE, 1137);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bremsenquietschen', 1124, 'F6', FALSE, 1138);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1139, 'F0', FALSE, 1148);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schlusslicht ausschalten', 1139, 'F1', FALSE, 1149);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Betriebsgeräusch', 1139, 'F2', FALSE, 1150);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Horn', 1139, 'F3', FALSE, 1151);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1139, 'F4', FALSE, 1152);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Druckluft ablassen', 1139, 'F5', FALSE, 1153);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bremsenquietschen', 1139, 'F6', FALSE, 1154);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Führerstandsbeleuchtung vorn', 1139, 'F7', FALSE, 1155);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Führerstandsbeleuchtung hinten', 1139, 'F8', FALSE, 1156);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1157, 'F0', FALSE, 1164);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Innenbeleuchtung', 1157, 'F1', FALSE, 1165);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Begrüßungs-Ansage', 1157, 'F2', FALSE, 1166);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Pfeife', 1157, 'F3', FALSE, 1167);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1157, 'F4', FALSE, 1168);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Innenbeleuchtung dimmen', 1157, 'F5', FALSE, 1169);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1170, 'F0', FALSE, 1178);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Innenbeleuchtung', 1170, 'F1', FALSE, 1179);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Betriebsgeräusch ', 1170, 'F2', FALSE, 1180);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Horn', 1170, 'F3', FALSE, 1181);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1170, 'F4', FALSE, 1182);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bremsenquietschen', 1170, 'F5', FALSE, 1183);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bahnhofsansage', 1170, 'F6', FALSE, 1184);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Türe zu', 1170, 'F7', FALSE, 1185);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schaffnerpfiff', 1170, 'F8', FALSE, 1186);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Hilfsdiesel', 1170, 'F9', FALSE, 1187);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Lüfter', 1170, 'F10', FALSE, 1188);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Kompressor', 1170, 'F11', FALSE, 1189);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Überdruckventil', 1170, 'F12', FALSE, 1190);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Druckluft ablassen', 1170, 'F13', FALSE, 1191);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1192, 'F0', FALSE, 1200);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Tischlampen', 1192, 'F1', FALSE, 1201);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Betriebsgeräusch', 1192, 'F2', FALSE, 1202);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Horn', 1192, 'F3', FALSE, 1203);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1192, 'F4', FALSE, 1204);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bremsenquietschen', 1192, 'F5', FALSE, 1205);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schaffnerpfiff', 1192, 'F6', FALSE, 1206);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Türen', 1192, 'F7', FALSE, 1207);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bahnhofsansage', 1192, 'F8', FALSE, 1208);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Rangierpfiff', 1192, 'F9', FALSE, 1209);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Innenbeleuchtung', 1210, 'F0', FALSE, 1218);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Start / Stopp', 1210, 'F1', FALSE, 1219);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Pause', 1210, 'F2', FALSE, 1220);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ein Lied vor', 1210, 'F3', FALSE, 1221);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ein Lied zurück', 1210, 'F4', FALSE, 1222);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Lauter', 1210, 'F5', FALSE, 1223);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Leiser', 1210, 'F6', FALSE, 1224);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Lichtorgel an / aus', 1210, 'F7', FALSE, 1225);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Barbeleuchtung an / aus', 1210, 'F8', FALSE, 1226);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strom führende Kupplung', 1210, 'F9', FALSE, 1227);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Stroboskop', 1210, 'F10', FALSE, 1228);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Umgebungsgeräusch 1', 1210, 'F11', FALSE, 1229);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Umgebungsgeräusch 2', 1210, 'F12', FALSE, 1230);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Betriebsgeräusch 1', 1210, 'F13', FALSE, 1231);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Betriebsgeräusch 2', 1210, 'F14', FALSE, 1232);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Betriebsgeräusch 3', 1210, 'F15', FALSE, 1233);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spitzensignal', 1234, 'F0', FALSE, 1243);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Innenbeleuchtung', 1234, 'F1', FALSE, 1244);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Fahrgeräusch', 1234, 'F2', FALSE, 1245);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Signalton', 1234, 'F3', FALSE, 1246);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Direktsteuerung', 1234, 'F4', FALSE, 1247);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bremsenquietschen aus', 1234, 'F5', FALSE, 1248);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spitzensignal Lokseite 2', 1234, 'F6', FALSE, 1249);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schaffnerpfiff', 1234, 'F7', FALSE, 1250);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Spitzensignal Lokseite 1', 1234, 'F8', FALSE, 1251);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Türenschließen', 1234, 'F9', FALSE, 1252);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Schienenstoß', 1234, 'F10', FALSE, 1253);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Bahnhofsansage', 1234, 'F11', FALSE, 1254);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Dialog', 1234, 'F12', FALSE, 1255);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Dialog', 1234, 'F13', FALSE, 1256);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Dialog', 1234, 'F14', FALSE, 1257);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Dialog ', 1234, 'F15', FALSE, 1258);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Arbeitsbühne heben', 1259, 'F1', FALSE, 1262);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Arbeitsbühne schwenken', 1259, 'F2', FALSE, 1263);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Stromabnehmer', 1259, 'F3', FALSE, 1264);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Initialisierung', 1259, 'F4', FALSE, 1265);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1271, 'F0', FALSE, 1278);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1271, 'F4', FALSE, 1279);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1280, 'F0', FALSE, 1284);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Pantograf', 1285, 'F2', FALSE, 1293);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Geräusch einer Schaffner', 1285, 'F3', FALSE, 1294);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Meßbereich', 1295, 'F1', FALSE, 1298);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Meßbereich', 1295, 'F2', FALSE, 1299);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Maßeinheit', 1295, 'F3', FALSE, 1300);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Anzeigen', 1295, 'F4', FALSE, 1301);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'Strinbeleuchtung', 1302, 'F0', FALSE, 1307);
INSERT INTO decoder_typ_funktion (deleted, bezeichnung, decoder_typ_id, funktion, programmable, id) VALUES (FALSE, 'ABV', 1302, 'F4', FALSE, 1308);
ALTER TABLE decoder_typ_funktion ALTER COLUMN id RESTART WITH 1326;