INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Einfach-Spitzensignal vorne', 'L1V', NULL, 383);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Einfach-Spitzensignal mit der Fahrtrichtung wechselnd.', 'L1W', NULL, 384);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal vorne', 'L2V', NULL, 385);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal vorne und hinten', 'L2L2', NULL, 386);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal mit der Fahrtrichtung wechselnd', 'L2W', NULL, 387);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal vorne', 'L3V', NULL, 388);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal mit der Fahrtrichtung wechselnd', 'L3W', NULL, 389);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Vierlicht-Spitzensignal mit der Fahrtrichtung wechselnd', 'L4W', NULL, 390);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Ein rotes Schlusslicht', 'R1H', NULL, 391);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zwei rote Schlusslichter', 'R2H', NULL, 392);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal und zwei rote Schlusslichter mit der Fahrtrichtung wechselnd', 'L2R2W', NULL, 393);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und ein rotes Schlusslicht mit der Fahrtrichtung wechselnd', 'L3R1W', NULL, 394);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und zwei rote Schlusslichter mit der Fahrtrichtung wechselnd', 'L3R2W', NULL, 395);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und ein weißes Schlusslicht mit der Fahrtrichtung wechselnd', 'L3L1W', NULL, 396);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und zwei weißes Schlusslicht mit der Fahrtrichtung wechselnd', 'L3L2W', NULL, 397);
ALTER TABLE licht ALTER COLUMN id RESTART WITH 398;