
---------- DATA.SQL
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 111};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 112};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 113};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 114};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 115};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 116};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin DELTA'), 3: 'DELTA', 4: 480};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin fx'), 3: 'FX', 4: 481};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin mfx'), 3: 'MFX', 4: 482};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'DCC', 3: 'DCC', 4: 483};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola'), 3: 'MM', 4: 484};
/*SQL l:74 #:1*/insert into protokoll (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 3: 'WEICHE', 4: 485};
