

INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 111);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 112);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 113);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 114);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 115);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 116);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin DELTA'), 'DELTA', 480);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin fx'), 'FX', 481);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin mfx'), 'MFX', 482);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, 'DCC', 'DCC', 483);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola'), 'MM', 484);
INSERT INTO protokoll (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Motorola Weiche'), 'WEICHE', 485);
