INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '(1''C)D 3''2''T35', '1CD32T35', 1);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1''C 1'' h2t', '1C1H2T', 2);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1''C h2 3T16', '1CH23T16', 3);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1''D 1'' h2t', '1D1H2T', 4);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1''E 1'' h3 2''3''T28', '1E1H323T28', 5);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1''E h2 2''2T26 KAB5', '1EH222T26KAB5', 6);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1''E1'' h2t', '1E1H2T', 7);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '2''C 1'' h3 2''2''T26', '2C1H322T26', 8);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '2''C1'' 2''2''T26', '2C122T26', 9);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '2''C1'' h3 2''2''T40', '2C1H322T40', 10);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'A1 dm', 'A1DM', 11);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'AA dm', 'AADM', 12);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B drn', 'BDRN', 13);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B h2t', 'BH2T', 14);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B''2'' dh 2''2'' 2''2'' 2''B'' dh', 'B2DH22222BDH', 15);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B''B'' de', 'BBDE', 16);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B''B'' dh', 'BBDH', 17);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B''B''', 'BB', 18);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bo''2'' e', 'BO2E', 19);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bo''Bo''+2''2''+Bo''Bo''', 'BOBO22BOBO', 20);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bo''Bo''+Bo''Bo''+Bo''Bo''+Bo''Bo''', 'BOBOBOBOBOBOBOBO', 21);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'C dh', 'CDH', 22);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'C h2t', 'CH2T', 23);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'C''C'' dh', 'CCDH', 24);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'Co''Co'' w6gf', 'COCOW6GF', 25);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'Co''Co''', 'COCO', 26);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'D h2t', 'DH2T', 27);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'D''D h4vt', 'DDH4VT', 28);
ALTER TABLE achsfolg ALTER COLUMN id RESTART WITH 29;