INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Avago Technologies', 'AVAGO', 'US', NULL, 'https://www.broadcom.com/', 313);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, '4MFOR', '4MFOR', 'DE', '+49 (0) 71 61 608-0', 'https://www.maerklin.de/', 314);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Artitec', 'ARTITEC', 'NL', NULL, 'http://www.artitec.nl', 315);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Auhagen', 'AUHAGEN', 'DE', NULL, 'https://auhagen.de/', 316);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Bochmann und Kochendörfer', 'BK', 'DE', NULL, NULL, 317);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Brawa', 'BRAWA', 'DE', NULL, 'https://www.brawa.de/', 318);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Busch Model', 'BUSCH', 'DE', NULL, 'https://www.busch-model.info/', 319);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'DCC Supplies', 'DCC', 'UK', NULL, 'https://www.dccsupplies.com/', 320);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Deluxe Materials', 'DELUXE', 'UK', NULL, 'https://deluxematerials.co.uk/', 321);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Digital-Bahn', 'DIGITALBAHN', 'DE', NULL, 'https://www.digital-bahn.de/', 322);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Digitrains Ltd', 'DIGITRAINS', 'UK', NULL, 'https://www.digitrains.co.uk/', 323);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Diotec Semiconductor AG', 'DIOTEC', 'DE', NULL, 'https://diotec.com/en/home.html', 324);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Erbert Signale', 'ERBERT', 'DE', NULL, 'http://www.erbert-signale.de/', 325);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Electronic Solutions Ulm', 'ESU', 'DE', NULL, 'http://www.esu.eu/', 326);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Evergreen Scale Models', 'EVERGREEN', 'US', NULL, 'https://evergreenscalemodels.com/', 327);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Fairchild Semiconductors', 'FAIRCHILD', 'US', NULL, NULL, 328);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Faller', 'FALLER', 'DE', NULL, 'https://www.faller.de/', 329);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Fleischmann', 'FLEISCHMANN', 'DE', NULL, 'https://www.fleischmann.de/', 330);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Gaßner Beschriftungen', 'GASSNER', 'DE', NULL, 'https://www.gassner-beschriftungen.de/', 331);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Gauge Master', 'GAUGEMASTER', 'UK', NULL, 'http://www.gaugemaster.com/index.html', 332);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Heico Modell', 'HEICO', 'DE', NULL, 'http://www.heico-modell.de/', 333);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Herkat', 'HERKAT', 'DE', NULL, 'http://www.herkat.de/', 334);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Herpa', 'HERPA', 'DE', NULL, 'https://www.herpa.de/', 335);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Humbrol', 'HUMBROL', 'UK', NULL, 'https://www.humbrol.com/uk-en/', 336);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Jordan Modellbau', 'JORDAN', 'DE', NULL, 'http://www.jordan-modellbau.de/', 337);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Kibri', 'KIBRI', 'DE', NULL, 'https://viessmann-modell.com/', 338);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Kingbright', 'KINGBRIGHT', 'TW', NULL, 'https://kingbright-europe.de/', 339);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'KK Produkcja', 'KKPMO', 'PL', NULL, 'http://www.kkpmo.com/', 340);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'KNIPEX', 'KNIPEX', 'DE', NULL, 'https://www.knipex.com/nc/en/home/', 341);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Kühn Digital', 'KUHN', 'DE', NULL, 'http://www.kuehn-digital.de/', 342);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Liliput', 'LILIPUT', 'DE', NULL, 'http://liliput.de/', 343);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Lima', 'LIMA', 'IT', NULL, 'https://www.hornby.com/', 344);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Littfinski Daten Technik', 'LDT', 'DE', NULL, 'https://www.ldt-infocenter.com/', 345);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'LUX-Modellbau', 'LUX', 'DE', NULL, 'https://www.lux-modellbau.de/', 346);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Maquett', 'MAQUETT', 'NL', NULL, 'https://www.maquett.nl/', 347);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Märklin', 'MARKLIN', 'DE', '+49 (0) 71 61 608-0', 'https://www.maerklin.de/', 348);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Mehano', 'MEHANO', 'SI', NULL, 'http://www.mehano.si/', 349);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Merten', 'MERTEN', 'DE', NULL, 'https://www.preiser.de/', 350);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Noch', 'NOCH', 'DE', NULL, 'https://www.noch.de/', 351);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Omron', 'OMRON', 'JP', NULL, 'https://www.omron.com/', 352);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'POLA', 'POLA', 'DE', NULL, 'https://www.faller.de/', 353);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Preiser', 'PREISER', 'DE', NULL, 'https://www.preiser.de/', 354);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Proses', 'PROSES', 'UK', NULL, 'https://proses.com/prestashop/', 355);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Ratio', 'RATIO', 'UK', NULL, 'https://peco-uk.com/pages/ratio', 356);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Red Line', 'REDLINE', 'US', NULL, 'http://www.redline.com/', 357);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Revell', 'REVELL', 'DE', NULL, 'https://www.revell.de/', 358);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Rivarossi', 'RIVAROSSI', 'IT', NULL, 'https://www.hornby.com/uk-en/shop/brands/rivarossi-h0-1-87.html', 359);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Roco', 'ROCO', 'AT', NULL, 'https://www.roco.cc/en/home/index.html', 360);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Schuco', 'SCHUCO', 'DE', NULL, 'https://www.schuco.de/', 361);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Seuthe Dampf', 'SEUTHE', 'DE', NULL, 'http://seuthe-dampf.de/', 362);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Taiwan Semiconductor', 'TAIWAN', 'TW', NULL, 'https://www.tsmc.com/english/default.htm', 363);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Tamiya', 'TAMIYA', 'JP', NULL, 'https://tamiya.com', 364);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Tams Elektronik', 'TAMS', 'DE', NULL, 'https://tams-online.de/de_DE', 365);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Tower Pro', 'TOWERPRO', 'TW', NULL, 'http://www.towerpro.com.tw/', 366);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Trix', 'TRIX', 'DE', '+49 (0) 71 61 608-0', 'https://www.trix.de/', 367);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'TruOpto', 'TRUOPTO', 'TW', NULL, 'https://www.rapidonline.com/brands/truopto', 368);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Uhlenbrock', 'UHLENBROCK', 'DE', NULL, 'https://www.uhlenbrock.de/', 369);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, '', 'UNBEKANT', NULL, NULL, NULL, 370);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Viessmann Modell', 'VIESSMANN', 'DE', NULL, 'https://viessmann-modell.com/', 371);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Walthers', 'WALTHERS', 'US', NULL, 'https://www.faller.de/', 372);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Weinert Modellbau', 'WEINERT', 'DE', NULL, 'https://weinert-modellbau.de/', 373);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Wiking', 'WIKING', 'DE', NULL, 'https://wiking.de/', 374);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Woodland Scenics', 'WOODLAND', 'US', NULL, 'https://woodlandscenics.woodlandscenics.com/', 375);
INSERT INTO hersteller (deleted, bezeichnung, name, land ,telefon, url, id) VALUES (FALSE, 'Zimo', 'ZIMO', 'AT', NULL, 'http://www.zimo.at', 376);
ALTER TABLE hersteller ALTER COLUMN id RESTART WITH 377;