
---------- DATA.SQL
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 94};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 95};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 96};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 97};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 98};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 99};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 100};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 101};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 102};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 103};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 104};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 105};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 106};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 107};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 108};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 109};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 110};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus', 3: 'CSINUS', 4: 463};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'C-Sinus Kompakt', 3: 'KSINUS', 4: 464};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Trommelkollektor', 3: 'DCM', 4: 465};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Drehstrom', 3: 'DREHSTROM', 4: 466};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Glockenanker', 3: 'GLOCKENANKER', 4: 467};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (DCM)', 3: 'HLM', 4: 468};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-7z)', 3: 'HLMMS1-7', 4: 469};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS1-8z)', 3: 'HLMMS1-8', 4: 470};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-7z)', 3: 'HLMMS2-7', 4: 471};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (MS2-8z)', 3: 'HLMMS2-8', 4: 472};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: '5-Stern (SFCM)', 3: 'HLMS', 4: 473};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-7z)', 3: 'LFCMMS1-7', 4: 474};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS1-8z)', 3: 'LFCMMS1-8', 4: 475};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-7z)', 3: 'LFCMMS2-7', 4: 476};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (MS2-8z)', 3: 'LFCMMS2-8', 4: 477};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'SoftDriveSinus', 3: 'SDSINUS', 4: 478};
/*SQL l:73 #:1*/insert into motorTyp (deleted, bezeichnung, name, id) values (?, ?, ?, ?) {1: FALSE, 2: 'Scheibenkollektor (klein)', 3: 'SFCM', 4: 479};
