INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Ahaus Alstätter Eisenbahn (AAE)', 'AAE', NULL, 41);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'ABB Daimler-Benz Transportation (ADtranz)', 'ADTRANZ', NULL, 42);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Anhaltische Leopoldsbahn (AL)', 'AL', NULL, 43);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'ALNO Küchen', 'ALNO', NULL, 44);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'American and Track (AMTRAK)', 'AMTRAK', NULL, 45);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Alaska Railroad (ARR)', 'AR', NULL, 46);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Atchison, Topeka and Santa Fe Railway (AT+SF)', 'ATSF', NULL, 47);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'ES', 'Alta Velocidad Española (AVE)', 'AVE', NULL, 48);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Albtal-Verkehrs-Gesellschaft mbH (AVG)', 'AVG', NULL, 49);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Alaska Railroad (ARR)', 'ALASKA', NULL, 50);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'CH', 'Schweizerische Aluminium AG (Alusuisse)', 'ALUSUISSE', NULL, 51);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Boston and Albany Railway (B+A)', 'BA', NULL, 52);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Baltomore and Ohio Railway (B+0)', 'BO', NULL, 53);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'AT', 'Österreichischen Bundesbahnen (ÖBB)', 'BBO', NULL, 54);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Bebra-Hanauer Eisenbahn (BHE)', 'BHE', NULL, 55);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'CH', 'Bern–Lötschberg–Simplon railway (BLS)', 'BLS', NULL, 56);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Burlington Northern Railroad (BN)', 'BN', NULL, 57);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Berliner Verkehrsbetriebe (BVG)', 'BVG', NULL, 58);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Ruhrkohle AG Bahn und Hafen GmbH (RAG/BuH)', 'BUH', NULL, 59);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Columbus and Greenville Railway (C+G)', 'CG', NULL, 60);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Chicago, Burlington and Quincy Railroad (CBQ)', 'CBQ', NULL, 61);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'LU', 'Société Nationale des Chemins de Fer Luxembourgeois (CFL)', 'CFL', NULL, 62);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'CH', 'Chemin de Fer à Vapeur des 3 Vallées (CFV3V)', 'CFV3V', NULL, 63);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Compagnie Internationale des Wagons-Lits (CIWL)', 'CIWL', NULL, 64);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'CN', 'Canadian National Railway (CN)', 'CN', NULL, 65);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'CONNEX GmbH', 'CONNEX', NULL, 66);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Dortmunder Actien-Brauerei (DAB)', 'DAB', NULL, 67);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Bahn AG (DB AG)', 'DBAG', NULL, 68);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Bahn AG AutoZug (DB AutoZug)', 'DBAUTOZUG', NULL, 69);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Bahn AG Cargo (DB Cargo)', 'DBCARGO', NULL, 70);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Bundesbahn Museum (DB Museum)', 'DBMUSEUM', NULL, 71);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Bundesbahn (DB)', 'DB', NULL, 72);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Reichsbahn (DB/DR)', 'DBDR', NULL, 73);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Bahnpost (DBP)', 'DBP', NULL, 74);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Dixie Line (DL)', 'DL', NULL, 75);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Reichsbahn (DDR)', 'DRDDR', NULL, 76);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Reichsbahn (DR)', 'DR', NULL, 77);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Reichsbahn (DRB)', 'DRB', NULL, 78);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Reichsbahn Gesellschaft (DRG)', 'DRGGVBAY', NULL, 79);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Reichsbahn Gesellschaft (DRG)', 'DRG', NULL, 80);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Denver and Rio Grande Western Railroad (DRGW)', 'DRGW', NULL, 81);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DK', 'Danske Statsbaner (DSB)', 'DSB', NULL, 82);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutsche Schlafwagen und Speisewagengesellschaft (DSG)', 'DSG', NULL, 83);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Elmshorn-Barmstedt-Oldesloer Eisenbahn (EBOE)', 'EBOE', NULL, 84);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Eisenbahn-Service GmbH (ESG)', 'ESG', NULL, 85);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'FR', ' Société Nationale des Chemins de Fer Français (SNCF)', 'EST', NULL, 86);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH (EVB)', 'EVB', NULL, 87);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'GM Electro Motive Division (EMD)', 'EMD', NULL, 88);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', '„Eisenbahn + Häfen“', 'EUH', NULL, 89);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'IT', 'Ferrovie dello Stato Italiane Cargo (FS Cargo)', 'FSCARGO', NULL, 90);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'IT', 'Ferrovie dello Stato Italiane (FS)', 'FS', NULL, 91);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'GATX Corporation (GATX)', 'GATX', NULL, 92);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'GB Netz der Deutschen Bahn AG (GBAG)', 'GBAG', NULL, 93);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Großherzoglich Badische Staatseisenbahn (G.Bad.St.E)', 'GBADSTE', NULL, 94);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Grosskraftwerk Mannheim AG (GKM)', 'GKM', NULL, 95);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Großherzoglich Oldenburgische Staatseisenbahn (G.O.St.B)', 'GOSTB', NULL, 96);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Great Southwest Railroad (GSW)', 'GSW', NULL, 97);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Gruppenverwaltung Bayern (GVB)', 'GVB', NULL, 98);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Großherzoglich Mecklenburgische Friedrich-Franz-Eisenbahn (MFFE)', 'GHMFFE', NULL, 99);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Herzoglich Braunschweigische Staatseisenbahn (HBS)', 'HBS', NULL, 100);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Hersfelder Eisenbahn Gesellschaft mbH (HEG)', 'HEG', NULL, 101);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Herzoglich Nassauische Staatsbahn (HNSt.B)', 'HNSTB', NULL, 102);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Hansabahn Dortmund', 'HANSA', NULL, 103);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Fa Henkel KGaA, Düsseldorf', 'HENKEL', NULL, 104);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Illonois Central Railway (ICG)', 'ICG', NULL, 105);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Internationalen Gesellschaft für Eisenbahnverkehr (IGE)', 'IGE', NULL, 106);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Ilmebahn GmbH', 'ILMEBAHN', NULL, 107);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Königlich Bayerischen Staatseisenbahnen (K.Bay.St.E)', 'KBAYSTE', NULL, 108);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Königlich Hannöversche Staatseisenbahnen (K.H.St.B)', 'KHSTB', NULL, 109);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Königlich Preußische Eisenbahn-Verwaltung (K.P.E.V)', 'KPEV', NULL, 110);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Königlich Preußische Staatseisenbahnen (K.P.St.E)', 'KPSTE', NULL, 111);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Deutschen Bundesbahn (DB)', 'KB', NULL, 112);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Karsdorfer Eisenbahngesellschaft GmbH (KEG)', 'KEG', NULL, 113);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Kraftwerk Herne', 'KH', NULL, 114);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'KLVM', 'KLVM', NULL, 115);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Königlich Preußische und Großherzoglich Hessischen Staatseisenbahnen (K.Pu.G.H.St.E', 'KPUGHSTE', NULL, 116);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Königlich Sächsische Staatseisenbahnen (K.Sächs.St.E)', 'KSACHSSTE', NULL, 117);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Königlich Württembergischen Staatseisenbahnen (K.W.St.E)', 'KWSTE', NULL, 118);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Lokalbahn Aktien-Gesellschaft (LAG)', 'LAG', NULL, 119);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'UK', 'London, Midland and Scottish Railway (LMS)', 'LMS', NULL, 120);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'UK', 'London Northeast Railway (LNER)', 'LNER', NULL, 121);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'CH', 'Luzern–Stans–Engelberg-Bahn (LSE)', 'LSE', NULL, 122);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'HU', 'Magyar Államvasutak(MAV)', 'MAV', NULL, 123);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Großherzoglich Mecklenburgische Friedrich-Franz-Eisenbahn (MFFE)', 'MFFE', NULL, 124);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Chicago, Milwaukee, St Paul and Pacific Railroad (MILW)', 'MILW', NULL, 125);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Museumseisenbahn Küstenbahn Ostfriesland (MKO)', 'MKO', NULL, 126);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Mittelweserbahn GmbH (MWB)', 'MWB', NULL, 127);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Firma „Makies“ AG', 'MAKIESAG', NULL, 128);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'NordseeBahn (NB)', 'NB', NULL, 129);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Norddeutsche Eisenbahngesellschaft Niebüll GmbH (NEG)', 'NEG', NULL, 130);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'New York, New Haven and Hartford Railroad (NH)', 'NH', NULL, 131);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'NL', 'P and O Nedlloyd (NL)', 'NL', NULL, 132);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DK', 'Nydqvist und Holm AB (NOHAB)', 'NOHAB', NULL, 133);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'NL', 'Nederlandse Spoorweggen Cargo (NS Cargo)', 'NSCARGO', NULL, 134);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'NL', 'Nederlandse Spoorweggen (NS)', 'NS', NULL, 135);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DK', 'Norske Statsbaner (NSB)', 'NSB', NULL, 136);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'New York Central Railroad (NYC)', 'NYC', NULL, 137);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'das Bayerische Eisenbahnmuseum (Nördlingen)', 'NORDLINGEN', NULL, 138);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'AT', 'Österreichischen Bundesbahnen (ÖBB)', 'OBB', NULL, 139);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'AT', 'Österreichischen Bundesbahnen (ÖBB)', 'OHB', NULL, 140);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'CN', 'Ontario Northland Railway (ONR)', 'ONR', NULL, 141);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'On Rail Gesellschaft für Eisenbahnausrüstung und Zubehör mbH (On Rail)', 'ONRAIL', NULL, 142);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Opel AG', 'OPEL', NULL, 143);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'CH', 'Transport Vallée de Joux, Yverdon-les-bains et Sainte Croix (Travys)', 'ORBECHAV', NULL, 144);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Pittsburgh and Lake Erie Railroad (P+LE)', 'PLE', NULL, 145);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Preußische Staatseisenbahnen (P.St.E)', 'PSTE', NULL, 146);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Prignitzer Eisenbahn-Gesellschaft (PEG)', 'PEG', NULL, 147);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Pennsylvania Railroad (PRR)', 'PRR', NULL, 148);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Fa Henkel KGaA, Düsseldorf', 'PERSIL', NULL, 149);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Pfälzische Eisenbahnen (Pfalz.B)', 'PFALZB', NULL, 150);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, NULL, 'Privatbahn', 'PRIVAT', NULL, 151);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Rutland Railroad (R)', 'R', NULL, 152);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Ruhrkohle AG (RAG)', 'RAG', NULL, 153);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'UK', 'Royal Corps of Transport (RCT)', 'RCT', NULL, 154);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Reichseisenbahn Elsaß-Lothringen (REL)', 'REL', NULL, 155);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'ES', 'Red Nacional de Ferrocarriles Españoles (RENFE)', 'RENFE', NULL, 156);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'NL', 'Railbouw Leerdam Maatschappij', 'RAILBOUW', NULL, 157);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'CH', 'Schweizerischen Bundesbahnen Cargo (SBB Cargo)', 'SBBCARGO', NULL, 158);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'CH', 'Schweizerischen Bundesbahnen (SBB/CFF/FFS)', 'SBB', NULL, 159);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Southern Central Freight Railroad (SCF)', 'SCF', NULL, 160);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'SECO Rail (SECO)', 'SECO', NULL, 161);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'SE', 'Statens Järnvägar (SJ)', 'SJ', NULL, 162);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Werkseisenbahn SKW Trostberg', 'SKW', NULL, 163);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'BE', 'Société Nationale des Chemins de Fer Belges (SNCB/NMBS)', 'SNCB', NULL, 164);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'FR', 'Société Nationale des Chemins de Fer Français (SNCF)', 'SNCF', NULL, 165);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'SüdOstBayernBahn (SOB)', 'SOB', NULL, 166);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Soo Line Railroad (SOO)', 'SOO', NULL, 167);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Southern Pacific Railroad (SP)', 'SP', NULL, 168);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'RU', 'Sovetskie Železnye dorogi (SŽD)', 'SZD', NULL, 169);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Seehaven Kiel', 'SEEHKIEL', NULL, 170);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Siemens AG', 'SIEMENS', NULL, 171);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'State of Maine (SoM)', 'SOM', NULL, 172);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'SE', 'Trafikaktiebolaget Grängesberg–Oxelösunds Järnvägar (Stora)', 'STORA', NULL, 173);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Südzucker AG', 'SUDDZUCKER', NULL, 174);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Texas and Northern Railway (T+N)', 'TN', NULL, 175);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Texas and Pacific Railway Company (T+P)', 'TP', NULL, 176);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Tegernsee-Bahn', 'TAG', NULL, 177);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'SE', 'Tågåkeriet i Bergslagen AB (TÅGAB)', 'TAGAB', NULL, 178);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'SE', 'Trafikaktiebolaget Grängesberg–Oxelösunds Järnvägar (TGOJ)', 'TGOJ', NULL, 179);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'SE', 'Tågkompaniet AB (TKAB)', 'TKAB', NULL, 180);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Texas Mexican Railway (TM)', 'TMR', NULL, 181);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'FR', 'Travaux du Sud-Ouest (TSO)', 'TSO', NULL, 182);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Texas Western Railroad (TW)', 'TW', NULL, 183);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', '„Tegernsee-Bahn“', 'TEGERNSEE', NULL, 184);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Ulmer Eisenbahnfreunde (UEF)', 'UEF', NULL, 185);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Union Pacific Railroad (UP)', 'UP', NULL, 186);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'United States Transport Corps (USTC)', 'USTC', NULL, 187);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'VTG AG (VTG)', 'VTG', NULL, 188);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Volkswagen AG (VW)', 'VW', NULL, 189);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Württembergische Eisenbahngesellschaft (WEG)', 'WEG', NULL, 190);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Westfälische Landes-Eisenbahn GmbH (WLE)', 'WLE', NULL, 191);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'US', 'Western Pacific Railroad (WP)', 'WP', NULL, 192);
INSERT INTO bahnverwaltung (deleted, land, bezeichnung, name, abbildung, id) VALUES (FALSE, 'DE', 'Wiebe Gleisbau GmbH (Wiebe)', 'WIEBE', NULL, 193);
ALTER TABLE bahnverwaltung ALTER COLUMN id RESTART WITH 194;