INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, '48 / 24 Positions', 1, 687, 1, 0, 1, 688);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'DCC / Motorola', 2, 687, 1, 0, 1, 689);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Position specification', 3, 687, 1, 0, 0, 690);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 708, 80, 1, 3, 709);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 2, 708, 63, 1, 3, 710);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Beschleunigungszeit', 3, 708, 63, 1, 16, 711);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 708, 63, 1, 12, 712);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 708, 63, 1, 63, 713);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 708, NULL, NULL, 8, 714);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Regelungsreferenz', 53, 708, 63, 1, 45, 715);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Lastregelung Param. K', 54, 708, 63, 1, 32, 716);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Lastregelung Param. L', 55, 708, 63, 1, 24, 717);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Regelungseinfluss', 56, 708, 63, 1, 63, 718);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Speicheroptionen', 73, 708, 7, 0, 3, 719);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Addresse 2'), 75, 708, 80, 1, 4, 720);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Anfahrspannung Analog AC', 78, 708, 63, 1, 25, 721);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit Analog AC'), 79, 708, 63, 1, 63, 722);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 725, 80, 1, 3, 726);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 2, 725, 63, 1, 3, 727);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Beschleunigungszeit', 3, 725, 63, 1, 16, 728);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 725, 63, 1, 12, 729);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 725, 63, 1, 63, 730);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 725, NULL, NULL, 8, 731);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Regelungsreferenz', 53, 725, 63, 1, 45, 732);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Lastregelung Param. K', 54, 725, 63, 1, 32, 733);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Lastregelung Param. L', 55, 725, 63, 1, 24, 734);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Regelungseinfluss', 56, 725, 63, 1, 63, 735);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Speicheroptionen', 73, 725, 7, 0, 3, 736);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Addresse 2'), 75, 725, 80, 1, 4, 737);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Anfahrspannung Analog AC', 78, 725, 63, 1, 25, 738);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit Analog AC'), 79, 725, 63, 1, 63, 739);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 742, 80, 1, 3, 743);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 2, 742, 63, 1, 3, 744);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Beschleunigungszeit', 3, 742, 63, 1, 16, 745);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 742, 63, 1, 12, 746);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 742, 63, 1, 63, 747);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 742, NULL, NULL, 8, 748);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Regelungsreferenz', 53, 742, 63, 1, 56, 749);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Lastregelung Param. K', 54, 742, 63, 1, 32, 750);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Lastregelung Param. L', 55, 742, 63, 1, 24, 751);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Regelungseinfluss', 56, 742, 63, 1, 63, 752);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Ger\\u00e4uschmodus 1'), 57, 742, 63, 1, 10, 753);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Ger\\u00e4uschmodus 2'), 58, 742, 63, 1, 58, 754);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Fahrger\\u00e4usch'), 59, 742, 63, 1, 32, 755);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Fahrger\\u00e4usch'), 60, 742, 63, 1, 55, 756);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Ger\\u00e4uschlautst\\u00e4rke'), 63, 742, 63, 1, 63, 757);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Bremssoundschwelle', 64, 742, 63, 1, 7, 758);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Speicheroptionen', 73, 742, 7, 0, 3, 759);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Addresse 2'), 74, 742, 63, 1, NULL, 760);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Addresse 2'), 75, 742, 80, 1, 4, 761);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Anfahrspannung Analog AC', 78, 742, 63, 1, 25, 762);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit Analog AC'), 79, 742, 63, 1, 63, 763);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 782, 80, 1, 3, 783);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 2, 782, 63, 1, 3, 784);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Beschleunigungszeit', 3, 782, 63, 1, 16, 785);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 782, 63, 1, 12, 786);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 782, 63, 1, 63, 787);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 782, NULL, NULL, 8, 788);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Regelungsreferenz', 53, 782, 63, 1, 56, 789);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Lastregelung Param. K', 54, 782, 63, 1, 32, 790);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Lastregelung Param. L', 55, 782, 63, 1, 24, 791);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Regelungseinfluss', 56, 782, 63, 1, 63, 792);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Ger\\u00e4uschmodus 1'), 57, 782, 63, 1, 10, 793);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Ger\\u00e4uschmodus 2'), 58, 782, 63, 1, 58, 794);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Fahrger\\u00e4usch'), 59, 782, 63, 1, 32, 795);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Fahrger\\u00e4usch'), 60, 782, 63, 1, 55, 796);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Ger\\u00e4uschlautst\\u00e4rke'), 63, 782, 63, 1, 63, 797);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Bremssoundschwelle', 64, 782, 63, 1, 7, 798);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Speicheroptionen', 73, 782, 7, 0, 3, 799);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Addresse 2'), 74, 782, 63, 1, NULL, 800);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin Addresse 2'), 75, 782, 80, 1, 4, 801);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Anfahrspannung Analog AC', 78, 782, 63, 1, 25, 802);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit Analog AC'), 79, 782, 63, 1, 63, 803);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 822, 80, 1, NULL, 823);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 822, NULL, NULL, 8, 824);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 832, 80, 1, NULL, 833);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 832, NULL, NULL, 8, 834);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Decoderadresse 1, LSB', 1, 842, 63, 1, 1, 843);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfiguration Ausgang 1', 3, 842, 64, 0, 8, 844);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfiguration Ausgang 2', 4, 842, 64, 0, 8, 845);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfiguration Ausgang 3', 5, 842, 64, 0, 8, 846);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfiguration Ausgang 4', 6, 842, 64, 0, 8, 847);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Versionsnummer', 7, 842, NULL, NULL, 115, 848);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Herstellerkennung', 8, 842, NULL, NULL, 151, 849);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Decoderadresse 1, MSB', 9, 842, 7, 0, 0, 850);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'RailCom Konfiguration', 28, 842, 6, 0, 0, 851);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfigurationsregister', 29, 842, 136, 128, 128, 852);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Funktionsausgangsstatus', 33, 842, 255, 0, NULL, 853);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('\\u201eZoom\\u201c-Konfiguration'), 34, 842, 15, 0, 0, 854);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Decoderadresse 2, LSB', 35, 842, 63, 1, 1, 855);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Decoderadresse 2, MSB', 36, 842, 8, 0, 8, 856);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Servo 1, Drehgeschwindigkeit', 37, 842, 63, 1, 15, 857);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 1, Stellung \\u201eA\\u201c'), 38, 842, 63, 1, 24, 858);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 1, Stellung \\u201eB\\u201c'), 39, 842, 63, 1, 40, 859);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Servo 2, Drehgeschwindigkeit', 40, 842, 63, 1, 15, 860);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 2, Stellung \\u201eA\\u201c'), 41, 842, 63, 1, 24, 861);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 2, Stellung \\u201eB\\u201c'), 42, 842, 63, 1, 40, 862);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Decoderadresse 1, LSB', 1, 869, 63, 1, 1, 870);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfiguration Ausgang 1', 3, 869, 64, 0, 8, 871);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfiguration Ausgang 2', 4, 869, 64, 0, 8, 872);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfiguration Ausgang 3', 5, 869, 64, 0, 8, 873);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfiguration Ausgang 4', 6, 869, 64, 0, 8, 874);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Versionsnummer', 7, 869, NULL, NULL, 115, 875);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Herstellerkennung', 8, 869, NULL, NULL, 151, 876);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Decoderadresse 1, MSB', 9, 869, 7, 0, 0, 877);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'RailCom Konfiguration', 28, 869, 6, 0, 0, 878);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfigurationsregister', 29, 869, 136, 128, 128, 879);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Funktionsausgangsstatus', 33, 869, 255, 0, NULL, 880);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('\\u201eZoom\\u201c-Konfiguration'), 34, 869, 15, 0, 0, 881);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Decoderadresse 2, LSB', 35, 869, 63, 1, 1, 882);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Decoderadresse 2, MSB', 36, 869, 8, 0, 8, 883);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Servo 1, Drehgeschwindigkeit', 37, 869, 63, 1, 15, 884);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 1, Stellung \\u201eA\\u201c'), 38, 869, 63, 1, 24, 885);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 1, Stellung \\u201eB\\u201c'), 39, 869, 63, 1, 40, 886);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Servo 2, Drehgeschwindigkeit', 40, 869, 63, 1, 15, 887);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 2, Stellung \\u201eA\\u201c'), 41, 869, 63, 1, 24, 888);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 2, Stellung \\u201eB\\u201c'), 42, 869, 63, 1, 40, 889);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Decoderadresse 1, LSB', 1, 896, 63, 1, 1, 897);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Versionsnummer', 7, 896, NULL, NULL, 153, 898);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Herstellerkennung', 8, 896, NULL, NULL, 151, 899);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Decoderadresse 1, MSB', 9, 896, 7, 0, 0, 900);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'RailCom Konfiguration', 28, 896, 6, 0, 0, 901);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Konfigurationsregister', 29, 896, 136, 128, 128, 902);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Servo 1, Drehgeschwindigkeit', 37, 896, 63, 1, 15, 903);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 1, Stellung \\u201eA\\u201c'), 38, 896, 63, 1, 24, 904);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 1, Stellung \\u201eB\\u201c'), 39, 896, 63, 1, 40, 905);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Servo 2, Drehgeschwindigkeit', 40, 896, 63, 1, 15, 906);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 2, Stellung \\u201eA\\u201c'), 41, 896, 63, 1, 24, 907);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 2, Stellung \\u201eB\\u201c'), 42, 896, 63, 1, 40, 908);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Servo 3, Drehgeschwindigkeit', 43, 896, 63, 1, 15, 909);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 3, Stellung \\u201eA\\u201c'), 44, 896, 63, 1, 24, 910);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 3, Stellung \\u201eB\\u201c'), 45, 896, 63, 1, 40, 911);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Servo 4, Drehgeschwindigkeit', 46, 896, 63, 1, 15, 912);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 4, Stellung \\u201eA\\u201c'), 47, 896, 63, 1, 24, 913);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Servo 4, Stellung \\u201eB\\u201c'), 48, 896, 63, 1, 40, 914);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 920, 80, 1, 10, 921);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 920, 63, 1, NULL, 922);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 920, 63, 1, NULL, 923);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 920, 63, 1, NULL, 924);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 920, NULL, NULL, 8, 925);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 920, 63, 1, NULL, 926);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 938, 80, 1, 11, 939);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 942, 80, 1, 11, 943);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 946, 80, 1, 11, 947);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 950, 80, 1, 11, 951);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 954, 80, 1, 11, 955);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 958, 80, 1, 11, 959);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 962, 80, 1, 11, 963);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 966, 80, 1, 11, 967);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 970, 80, 1, 11, 971);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 974, 80, 1, NULL, 975);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 974, NULL, NULL, 8, 976);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 981, 80, 1, NULL, 982);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung/Bremsverz\\u00f6gerung'), 3, 981, 63, 1, 16, 983);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 981, 63, 1, NULL, 984);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 981, NULL, NULL, 8, 985);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 988, 255, 1, NULL, 989);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung/Bremsverz\\u00f6gerung'), 2, 988, 31, 1, NULL, 990);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung/Bremsverz\\u00f6gerung'), 3, 988, 63, 1, NULL, 991);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 988, 63, 1, NULL, 992);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 988, NULL, NULL, 8, 993);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 995, 255, 1, 38, 996);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung/Bremsverz\\u00f6gerung'), 3, 995, 63, 1, NULL, 997);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 995, 63, 1, NULL, 998);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 995, NULL, NULL, 8, 999);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1003, 80, 1, 45, 1004);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 2, 1003, 63, 1, NULL, 1005);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1003, 63, 1, NULL, 1006);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1020, 80, 1, NULL, 1021);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 2, 1020, 63, 1, NULL, 1022);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1029, 80, 1, 10, 1030);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 2, 1029, 63, 1, NULL, 1031);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1029, 63, 1, NULL, 1032);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1039, 80, 1, 71, 1040);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Bedienung festgelegt', 2, 1039, 1, 0, 0, 1041);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Baggerschaufel Zeitbegrenzung', 3, 1039, 1, 0, 0, 1042);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1049, 80, 1, NULL, 1050);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung/Bremsverz\\u00f6gerung'), 2, 1049, 63, 1, NULL, 1051);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1049, 63, 1, NULL, 1052);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1049, NULL, NULL, 8, 1053);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1058, 80, 1, NULL, 1059);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1058, 63, 1, NULL, 1060);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1058, 63, 1, NULL, 1061);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1058, 63, 1, NULL, 1062);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1058, NULL, NULL, 8, 1063);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1058, 63, 1, NULL, 1064);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1075, 80, 1, 64, 1076);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1075, 63, 1, 63, 1077);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1075, 63, 1, 63, 1078);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1075, 63, 1, 63, 1079);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1075, NULL, NULL, NULL, 1080);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1075, 63, 1, 63, 1081);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1094, 80, 1, 70, 1095);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1094, 63, 1, NULL, 1096);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1094, 63, 1, NULL, 1097);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1094, 63, 1, NULL, 1098);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1094, NULL, NULL, 8, 1099);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1094, 63, 1, NULL, 1100);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1112, 80, 0, 42, 1113);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1112, 63, 0, 63, 1114);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1112, 63, 0, 63, 1115);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1112, 63, 0, 63, 1116);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1112, NULL, NULL, NULL, 1117);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1112, 63, 0, 63, 1118);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1124, 80, 1, NULL, 1125);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1124, 63, 1, NULL, 1126);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1124, 63, 1, NULL, 1127);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1124, 63, 1, NULL, 1128);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1124, NULL, NULL, 8, 1129);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1124, 63, 1, NULL, 1130);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1139, 80, 1, NULL, 1140);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 2, 1139, 63, 1, NULL, 1141);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1139, 63, 1, NULL, 1142);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1139, 63, 1, NULL, 1143);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1139, 63, 1, NULL, 1144);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1139, NULL, NULL, 8, 1145);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1139, 63, 1, NULL, 1146);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1157, 80, 1, 49, 1158);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1157, 63, 1, NULL, 1159);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1157, 63, 1, NULL, 1160);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1157, 63, 1, NULL, 1161);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1157, NULL, NULL, 8, 1162);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1170, 80, 1, 11, 1171);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1170, 63, 1, NULL, 1172);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1170, 63, 1, NULL, 1173);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1170, 63, 1, NULL, 1174);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1170, NULL, NULL, 8, 1175);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1170, 63, 1, NULL, 1176);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1192, 80, 0, 43, 1193);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1192, 63, 0, 63, 1194);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1192, 63, 0, 63, 1195);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1192, 63, 0, 63, 1196);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1192, NULL, NULL, NULL, 1197);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1192, 63, 0, 63, 1198);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1210, 80, 1, NULL, 1211);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1210, 63, 1, NULL, 1212);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1210, 63, 1, NULL, 1213);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1210, 63, 1, NULL, 1214);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1210, NULL, NULL, 8, 1215);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1210, 63, 1, NULL, 1216);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1234, 80, 1, NULL, 1235);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1234, 63, 1, NULL, 1236);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1234, 63, 1, NULL, 1237);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1234, 63, 1, NULL, 1238);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1234, NULL, NULL, 8, 1239);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Protokolle', 50, 1234, 15, 1, 15, 1240);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1234, 63, 1, NULL, 1241);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1259, 80, 1, NULL, 1260);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1266, 80, 1, NULL, 1267);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 2, 1266, 63, 1, 3, 1268);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1266, 63, 1, NULL, 1269);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1271, 80, 1, NULL, 1272);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung/Bremsverz\\u00f6gerung'), 3, 1271, 63, 1, NULL, 1273);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung/Bremsverz\\u00f6gerung'), 4, 1271, 63, 1, NULL, 1274);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1271, 63, 1, NULL, 1275);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1271, NULL, NULL, 8, 1276);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1280, NULL, NULL, 54, 1281);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1280, NULL, NULL, 8, 1282);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1285, 80, 1, NULL, 1286);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1285, 63, 1, NULL, 1287);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1285, 63, 1, NULL, 1288);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1285, 63, 1, NULL, 1289);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1285, NULL, NULL, 8, 1290);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1285, 63, 1, 63, 1291);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1295, 80, 1, NULL, 1296);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1302, 80, 1, NULL, 1303);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 2, 1302, 63, 1, NULL, 1304);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1302, 63, 1, NULL, 1305);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1309, 80, 1, 39, 1310);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 2, 1309, 63, 1, NULL, 1311);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Anfahrverz\\u00f6gerung'), 3, 1309, 63, 1, NULL, 1312);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Bremsverz\\u00f6gerung'), 4, 1309, 63, 1, NULL, 1313);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('H\\u00f6chstgeschwindigkeit'), 5, 1309, 63, 1, NULL, 1314);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('R\\u00fcckstellen auf Serienwerte'), 8, 1309, NULL, NULL, 8, 1315);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, STRINGDECODE('Lautst\\u00e4rke'), 63, 1309, 63, 1, NULL, 1316);
INSERT INTO decoder_typ_cv (deleted, bezeichnung, cv, decoder_typ_id, maximal, minimal, werkseinstellung, id) VALUES (FALSE, 'Adresse', 1, 1318, 255, 1, NULL, 1319);