
---------- DATA.SQL
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 304};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 305};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 306};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 307};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 308};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 309};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Australian Dollar', 3: 'AUD', 4: 2, 5: 673};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Deutschemark', 3: 'DEM', 4: 2, 5: 674};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Euro', 3: 'EUR', 4: 2, 5: 675};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Pound Serling', 3: 'GBP', 4: 2, 5: 676};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Hong Kong Dollar', 3: 'HKD', 4: 2, 5: 677};
/*SQL l:84 #:1*/insert into wahrung (deleted, bezeichnung, name, dezimal, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'US Dollar', 3: 'USD', 4: 2, 5: 678};
