INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '(1’C)D 3’2’T35', '1-C-D-3-2-T35', 1);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1’C1’ h2t', '1-C1-H2T', 2);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1’C h2t 3T16', '1-C-H2T-3T16', 3);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1’D1’ h2t', '1-D1-H2T', 4);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1’E1’ h3 2’3’T28', '1-E1-H3-2-3-T28', 5);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1’E h2 2’2’T26 KAB5', '1-E-H2-2-2-T26-KAB5', 6);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1’E1’ h3t', '1-E1-H3T', 7);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '2’C1’ h2 2’2’T32', '2-C1-H2-2-2-T32', 8);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '2’C1’ 2’2’T34', '2-C1-2-2-T34', 9);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '2’C1’ h3 2’2’T40', '2-C1-H3-2-2-T40', 10);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'A1 dm', 'A1-DM', 11);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'AA dm', 'AA-DM', 12);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B drn', 'B-DRN', 13);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B h2t', 'B-H2T', 14);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B’2’ dh 2’2’ 2’2’ 2’B’ dh', 'B2DH22222BDH', 15);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B’B’ de', 'B-B-DE', 16);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B’B’ dh', 'B-B-DH', 17);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B’B’', 'B-B', 18);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bo’2’', 'BO-2', 19);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'B’2’+2’2’+2’2’+2’B’', 'B-2-2-2-2-2-2B', 20);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bo’Bo’+Bo’Bo’+Bo’Bo’+Bo’Bo’', 'BO-BO-BO-BO-BO-BO-BO-BO', 21);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'C dh', 'C-DH', 22);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'C h2t', 'C-H2T', 23);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'C’C’ dh', 'C-C-DH', 24);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'Co’Co’ w6gf', 'CO-CO-W6GF', 25);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'Co’Co’', 'CO-CO', 26);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'D h2t', 'D-H2T', 27);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'D’D’ h4vt', 'D-D-H4VT', 28);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '11', '11', 29);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '111', '111', 30);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '1A', '1A', 31);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '2’2’', '2-2', 32);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '3’3’ 2’2’T26', '3-3-2-2-T26', 33);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, '3’3’', '3-3', 34);
INSERT INTO achsfolg (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bo’Bo’', 'BO-BO', 35);

ALTER TABLE achsfolg ALTER COLUMN id RESTART WITH 36;