INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ahaus Alstätter Eisenbahn (AAE)', 'AAE', 41);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ABB Daimler-Benz Transportation (ADtranz)', 'ADTRANZ', 42);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Anhaltische Leopoldsbahn (AL)', 'AL', 43);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'ALNO Küchen', 'ALNO', 44);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'American and Track (AMTRAK)', 'AMTRAK', 45);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Alaska Railroad (ARR)', 'AR', 46);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Atchison, Topeka and Santa Fe Railway (AT+SF)', 'ATSF', 47);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Alta Velocidad Española (AVE)', 'AVE', 48);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Albtal-Verkehrs-Gesellschaft mbH (AVG)', 'AVG', 49);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Alaska Railroad (ARR)', 'ALASKA', 50);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Schweizerische Aluminium AG (Alusuisse)', 'ALUSUISSE', 51);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Boston and Albany Railway (B+A)', 'BA', 52);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Baltomore and Ohio Railway (B+0)', 'BO', 53);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Österreichischen Bundesbahnen (ÖBB)', 'BBO', 54);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bebra-Hanauer Eisenbahn (BHE)', 'BHE', 55);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bern–Lötschberg–Simplon railway (BLS)', 'BLS', 56);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Burlington Northern Railroad (BN)', 'BN', 57);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Berliner Verkehrsbetriebe (BVG)', 'BVG', 58);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ruhrkohle AG Bahn und Hafen GmbH (RAG/BuH)', 'BUH', 59);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Columbus and Greenville Railway (C+G)', 'CG', 60);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Chicago, Burlington and Quincy Railroad (CBQ)', 'CBQ', 61);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Société Nationale des Chemins de Fer Luxembourgeois (CFL)', 'CFL', 62);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Chemin de Fer à Vapeur des 3 Vallées (CFV3V)', 'CFV3V', 63);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Compagnie Internationale des Wagons-Lits (CIWL)', 'CIWL', 64);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Canadian National Railway (CN)', 'CN', 65);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'CONNEX GmbH', 'CONNEX', 66);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Dortmunder Actien-Brauerei (DAB)', 'DAB', 67);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Bahn AG (DB AG)', 'DBAG', 68);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Bahn AG AutoZug (DB AutoZug)', 'DBAUTOZUG', 69);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Bahn AG Cargo (DB Cargo)', 'DBCARGO', 70);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Bundesbahn Museum (DB Museum)', 'DBMUSEUM', 71);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Bundesbahn (DB)', 'DB', 72);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Reichsbahn (DB/DR)', 'DBDR', 73);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Bahnpost (DBP)', 'DBP', 74);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Dixie Line (DL)', 'DL', 75);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Reichsbahn (DDR)', 'DRDDR', 76);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Reichsbahn (DR)', 'DR', 77);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Reichsbahn (DRB)', 'DRB', 78);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Reichsbahn Gesellschaft (DRG)', 'DRGGVBAY', 79);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Reichsbahn Gesellschaft (DRG)', 'DRG', 80);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Denver and Rio Grande Western Railroad (DRGW)', 'DRGW', 81);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Danske Statsbaner (DSB)', 'DSB', 82);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutsche Schlafwagen und Speisewagengesellschaft (DSG)', 'DSG', 83);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Elmshorn-Barmstedt-Oldesloer Eisenbahn (EBOE)', 'EBOE', 84);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Eisenbahn-Service GmbH (ESG)', 'ESG', 85);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, ' Société Nationale des Chemins de Fer Français (SNCF)', 'EST', 86);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH (EVB)', 'EVB', 87);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'GM Electro Motive Division (EMD)', 'EMD', 88);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, '„Eisenbahn + Häfen“', 'EUH', 89);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ferrovie dello Stato Italiane Cargo (FS Cargo)', 'FSCARGO', 90);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ferrovie dello Stato Italiane (FS)', 'FS', 91);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'GATX Corporation (GATX)', 'GATX', 92);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'GB Netz der Deutschen Bahn AG (GBAG)', 'GBAG', 93);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Großherzoglich Badische Staatseisenbahn (G.Bad.St.E)', 'GBADSTE', 94);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Grosskraftwerk Mannheim AG (GKM)', 'GKM', 95);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Großherzoglich Oldenburgische Staatseisenbahn (G.O.St.B)', 'GOSTB', 96);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Great Southwest Railroad (GSW)', 'GSW', 97);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Gruppenverwaltung Bayern (GVB)', 'GVB', 98);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Großherzoglich Mecklenburgische Friedrich-Franz-Eisenbahn (MFFE)', 'GHMFFE', 99);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Herzoglich Braunschweigische Staatseisenbahn (HBS)', 'HBS', 100);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Hersfelder Eisenbahn Gesellschaft mbH (HEG)', 'HEG', 101);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Herzoglich Nassauische Staatsbahn (HNSt.B)', 'HNSTB', 102);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Hansabahn Dortmund', 'HANSA', 103);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Fa Henkel KGaA, Düsseldorf', 'HENKEL', 104);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Illonois Central Railway (ICG)', 'ICG', 105);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Internationalen Gesellschaft für Eisenbahnverkehr (IGE)', 'IGE', 106);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ilmebahn GmbH', 'ILMEBAHN', 107);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Königlich Bayerischen Staatseisenbahnen (K.Bay.St.E)', 'KBAYSTE', 108);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Königlich Hannöversche Staatseisenbahnen (K.H.St.B)', 'KHSTB', 109);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Königlich Preußische Eisenbahn-Verwaltung (K.P.E.V)', 'KPEV', 110);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Königlich Preußische Staatseisenbahnen (K.P.St.E)', 'KPSTE', 111);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Deutschen Bundesbahn (DB)', 'KB', 112);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Karsdorfer Eisenbahngesellschaft GmbH (KEG)', 'KEG', 113);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Kraftwerk Herne', 'KH', 114);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'KLVM', 'KLVM', 115);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Königlich Preußische und Großherzoglich Hessischen Staatseisenbahnen (K.Pu.G.H.St.E', 'KPUGHSTE', 116);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Königlich Sächsische Staatseisenbahnen (K.Sächs.St.E)', 'KSACHSSTE', 117);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Königlich Württembergischen Staatseisenbahnen (K.W.St.E)', 'KWSTE', 118);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Lokalbahn Aktien-Gesellschaft (LAG)', 'LAG', 119);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'London, Midland and Scottish Railway (LMS)', 'LMS', 120);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'London Northeast Railway (LNER)', 'LNER', 121);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Luzern–Stans–Engelberg-Bahn (LSE)', 'LSE', 122);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Magyar Államvasutak(MAV)', 'MAV', 123);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Großherzoglich Mecklenburgische Friedrich-Franz-Eisenbahn (MFFE)', 'MFFE', 124);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Chicago, Milwaukee, St Paul and Pacific Railroad (MILW)', 'MILW', 125);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Museumseisenbahn Küstenbahn Ostfriesland (MKO)', 'MKO', 126);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Mittelweserbahn GmbH (MWB)', 'MWB', 127);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Firma „Makies“ AG', 'MAKIESAG', 128);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'NordseeBahn (NB)', 'NB', 129);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Norddeutsche Eisenbahngesellschaft Niebüll GmbH (NEG)', 'NEG', 130);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'New York, New Haven and Hartford Railroad (NH)', 'NH', 131);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'P and O Nedlloyd (NL)', 'NL', 132);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nydqvist und Holm AB (NOHAB)', 'NOHAB', 133);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nederlandse Spoorweggen Cargo (NS Cargo)', 'NSCARGO', 134);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nederlandse Spoorweggen (NS)', 'NS', 135);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Norske Statsbaner (NSB)', 'NSB', 136);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'New York Central Railroad (NYC)', 'NYC', 137);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'das Bayerische Eisenbahnmuseum (Nördlingen)', 'NORDLINGEN', 138);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Österreichischen Bundesbahnen (ÖBB)', 'OBB', 139);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Österreichischen Bundesbahnen (ÖBB)', 'OHB', 140);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ontario Northland Railway (ONR)', 'ONR', 141);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'On Rail Gesellschaft für Eisenbahnausrüstung und Zubehör mbH (On Rail)', 'ONRAIL', 142);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Opel AG', 'OPEL', 143);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Transport Vallée de Joux, Yverdon-les-bains et Sainte Croix (Travys)', 'ORBECHAV', 144);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pittsburgh and Lake Erie Railroad (P+LE)', 'PLE', 145);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Preußische Staatseisenbahnen (P.St.E)', 'PSTE', 146);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Prignitzer Eisenbahn-Gesellschaft (PEG)', 'PEG', 147);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pennsylvania Railroad (PRR)', 'PRR', 148);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Fa Henkel KGaA, Düsseldorf', 'PERSIL', 149);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Pfälzische Eisenbahnen (Pfalz.B)', 'PFALZB', 150);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Privatbahn', 'PRIVAT', 151);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Rutland Railroad (R)', 'R', 152);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ruhrkohle AG (RAG)', 'RAG', 153);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Royal Corps of Transport (RCT)', 'RCT', 154);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Reichseisenbahn Elsaß-Lothringen (REL)', 'REL', 155);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Red Nacional de Ferrocarriles Españoles (RENFE)', 'RENFE', 156);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Railbouw Leerdam Maatschappij', 'RAILBOUW', 157);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Schweizerischen Bundesbahnen Cargo (SBB Cargo)', 'SBBCARGO', 158);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Schweizerischen Bundesbahnen (SBB/CFF/FFS)', 'SBB', 159);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Southern Central Freight Railroad (SCF)', 'SCF', 160);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'SECO Rail (SECO)', 'SECO', 161);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Statens Järnvägar (SJ)', 'SJ', 162);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Werkseisenbahn SKW Trostberg', 'SKW', 163);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Société Nationale des Chemins de Fer Belges (SNCB/NMBS)', 'SNCB', 164);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Société Nationale des Chemins de Fer Français (SNCF)', 'SNCF', 165);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'SüdOstBayernBahn (SOB)', 'SOB', 166);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Soo Line Railroad (SOO)', 'SOO', 167);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Southern Pacific Railroad (SP)', 'SP', 168);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Sovetskie Železnye dorogi (SŽD)', 'SZD', 169);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Seehaven Kiel', 'SEEHKIEL', 170);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Siemens AG', 'SIEMENS', 171);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'State of Maine (SoM)', 'SOM', 172);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trafikaktiebolaget Grängesberg–Oxelösunds Järnvägar (Stora)', 'STORA', 173);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Südzucker AG', 'SUDDZUCKER', 174);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Texas and Northern Railway (T+N)', 'TN', 175);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Texas and Pacific Railway Company (T+P)', 'TP', 176);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Tegernsee-Bahn', 'TAG', 177);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Tågåkeriet i Bergslagen AB (TÅGAB)', 'TAGAB', 178);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Trafikaktiebolaget Grängesberg–Oxelösunds Järnvägar (TGOJ)', 'TGOJ', 179);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Tågkompaniet AB (TKAB)', 'TKAB', 180);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Texas Mexican Railway (TM)', 'TMR', 181);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Travaux du Sud-Ouest (TSO)', 'TSO', 182);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Texas Western Railroad (TW)', 'TW', 183);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, '„Tegernsee-Bahn“', 'TEGERNSEE', 184);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Ulmer Eisenbahnfreunde (UEF)', 'UEF', 185);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Union Pacific Railroad (UP)', 'UP', 186);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'United States Transport Corps (USTC)', 'USTC', 187);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'VTG AG (VTG)', 'VTG', 188);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Volkswagen AG (VW)', 'VW', 189);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Württembergische Eisenbahngesellschaft (WEG)', 'WEG', 190);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Westfälische Landes-Eisenbahn GmbH (WLE)', 'WLE', 191);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Western Pacific Railroad (WP)', 'WP', 192);
INSERT INTO bahnverwaltung (deleted, bezeichnung, name, id) VALUES (FALSE, 'Wiebe Gleisbau GmbH (Wiebe)', 'WIEBE', 193);