INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Einfach-Spitzensignal vorne', 'L1V', 'static/licht/L1V/abbildung.jpg', 383);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Einfach-Spitzensignal mit der Fahrtrichtung wechselnd.', 'L1W', 'static/licht/L1W/abbildung.jpg', 384);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal vorne', 'L2V', 'static/licht/L2V/abbildung.jpg', 385);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal vorne und hinten', 'L2L2', 'static/licht/L2L2/abbildung.jpg', 386);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal mit der Fahrtrichtung wechselnd', 'L2W', 'static/licht/L2W/abbildung.jpg', 387);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal vorne', 'L3V', 'static/licht/L3V/abbildung.jpg', 388);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal mit der Fahrtrichtung wechselnd', 'L3W', 'static/licht/L3W/abbildung.jpg', 389);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Vierlicht-Spitzensignal mit der Fahrtrichtung wechselnd', 'L4W', 'static/licht/L4W/abbildung.jpg', 390);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Ein rotes Schlusslicht', 'R1H', 'static/licht/R1H/abbildung.jpg', 391);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zwei rote Schlusslichter', 'R2H', 'static/licht/R2H/abbildung.jpg', 392);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal und zwei rote Schlusslichter mit der Fahrtrichtung wechselnd', 'L2R2W', 'static/licht/L2R2W/abbildung.jpg', 393);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und ein rotes Schlusslicht mit der Fahrtrichtung wechselnd', 'L3R1W', 'static/licht/L3R1W/abbildung.jpg', 394);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und zwei rote Schlusslichter mit der Fahrtrichtung wechselnd', 'L3R2W', 'static/licht/L3R2W/abbildung.jpg', 395);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und ein weißes Schlusslicht mit der Fahrtrichtung wechselnd', 'L3L1W', 'static/licht/L3L1W/abbildung.jpg', 396);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und zwei weißes Schlusslicht mit der Fahrtrichtung wechselnd', 'L3L2W', 'static/licht/L3L2W/abbildung.jpg', 397);
ALTER TABLE licht ALTER COLUMN id RESTART WITH 398;