

INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1417);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1423);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1422, 1424);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('G\\u00fctterzug'), 'GUTTERZUG', 1418);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Nahvekerszug', 'NAHVEKERS', 1419);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Bahndienstzug', 'BAHNDIENST', 1420);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Interregiozug', 'IR', 1421);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'Intercityzug', 'IC', 1422);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, 'TEE Zug', 'TEE', 1423);
INSERT INTO zugTyp (deleted, bezeichnung, name, id) VALUES (FALSE, STRINGDECODE('Milit\\u00e4r Zug'), 'MILITAR', 1424);
INSERT INTO zug (deleted, bezeichnung, name, zugTyp_id, id) VALUES (FALSE, STRINGDECODE('TEE \\u201eBavaria\\u201c'), 'BAVARIA', 1423, 1425);
