INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Einfach-Spitzensignal vorne', 'L1V', 'static/data/licht/L1V/abbildung.png', 383);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Einfach-Spitzensignal mit der Fahrtrichtung wechselnd', 'L1W', 'static/data/licht/L1W/abbildung.png', 384);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal vorne', 'L2V', 'static/data/licht/L2V/abbildung.png', 385);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal vorne und hinten', 'L2L2', 'static/data/licht/L2L2/abbildung.png', 386);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal mit der Fahrtrichtung wechselnd', 'L2W', 'static/data/licht/L2W/abbildung.png', 387);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal vorne', 'L3V', 'static/data/licht/L3V/abbildung.png', 388);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal mit der Fahrtrichtung wechselnd', 'L3W', 'static/data/licht/L3W/abbildung.png', 389);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Vierlicht-Spitzensignal mit der Fahrtrichtung wechselnd', 'L4W', 'static/data/licht/L4W/abbildung.png', 390);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Ein rotes Schlusslicht', 'R1H', 'static/data/licht/R1H/abbildung.png', 391);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zwei rote Schlusslichter', 'R2H', 'static/data/licht/R2H/abbildung.png', 392);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Zweilicht-Spitzensignal und zwei rote Schlusslichter mit der Fahrtrichtung wechselnd', 'L2R2W', 'static/data/licht/L2R2W/abbildung.png', 393);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und ein rotes Schlusslicht mit der Fahrtrichtung wechselnd', 'L3R1W', 'static/data/licht/L3R1W/abbildung.png', 394);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und zwei rote Schlusslichter mit der Fahrtrichtung wechselnd', 'L3R2W', 'static/data/licht/L3R2W/abbildung.png', 395);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und ein weißes Schlusslicht mit der Fahrtrichtung wechselnd', 'L3L1W', 'static/data/licht/L3L1W/abbildung.png', 396);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal und zwei weißes Schlusslicht mit der Fahrtrichtung wechselnd', 'L3L2W', 'static/data/licht/L3L2W/abbildung.png', 397);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Innenbeleuchtung', 'IB', 'static/data/licht/IB/abbildung.png', 398);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Innenbeleuchtung aus LED', 'IBL', 'static/data/licht/IBL/abbildung.png', 399);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Innenbeleuchtung mit ein rotes Schlusslicht', 'IBR1H', 'static/data/licht/IBR1H/abbildung.png', 400);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Innenbeleuchtung mit zwei rote Schlusslichter', 'IBR2H', 'static/data/licht/IBR2H/abbildung.png', 401);
INSERT INTO licht (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Dreilicht-Spitzensignal vorne und hinten', 'L3L3', 'static/data/licht/L3L3/abbildung.png', 402);
ALTER TABLE licht ALTER COLUMN id RESTART WITH 403;