INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, '1. FC Märklin Jahresmodell', '1.FC', 'static/data/sondermodell/1.FC/abbildung.png', 495);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Christkindlesmarkt', 'CHRISTKINDLE', 'static/data/sondermodell/CHRISTKINDLE/abbildung.png', 496);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Einmalige Serien', 'EINMALIGE', 'static/data/sondermodell/EINMALIGE/abbildung.png', 491);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Eurotrain exclisiv', 'EUROTRAIN', 'static/data/sondermodell/EUROTRAIN/abbildung.png', 497);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Hobby', 'HOBBY', 'static/data/sondermodell/HOBBY/abbildung.png', 489);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Idee+Spiel', 'IDEE-SPIEL', 'static/data/sondermodell/IDEE-SPIEL/abbildung.png', 498);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Märklin Infotag Wagen', 'INFOTAG', 'static/data/sondermodell/INFOTAG/abbildung.png', 494);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Märklin Insider', 'INSIDER', 'static/data/sondermodell/INSIDER/abbildung.png', 487);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Märklin Kids Club Jahresmodell', 'KIDSCLUB', 'static/data/sondermodell/KIDSCLUB/abbildung.png', 490);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Märklin Magazin Jahresmodell', 'MAGAZIN', 'static/data/sondermodell/MAGAZIN/abbildung.png', 486);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Märklintag Modell', 'MARKLINTAG', 'static/data/sondermodell/MARKLINTAG/abbildung.png', 499);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Messemodell', 'MESSE', NULL, 501);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Märklin Handler Initiative', 'MHI', 'static/data/sondermodell/MHI/abbildung.png', 488);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Museumsmodell', 'MUSEUM', 'static/data/sondermodell/MUSEUM/abbildung.png', 492);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Märklin Start Up Club', 'STARTUP', 'static/data/sondermodell/STARTUP/abbildung.png', 500);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Märklin Weihnachtsmodell', 'WEIHNACHT', 'static/data/sondermodell/WEIHNACHT/abbildung.png', 493);
INSERT INTO sondermodell (deleted, bezeichnung, name, abbildung, id) VALUES (FALSE, 'Märklin Werbemodell', 'WERBEWAGEN', NULL, 502);
ALTER TABLE sondermodell ALTER COLUMN id RESTART WITH 503;