INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Avago Technologies', 'AVAGO', NULL, 'https://www.broadcom.com/', 313);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, '4MFOR', '4MFOR', '+49 (0) 71 61 608-0', 'https://www.maerklin.de/', 314);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Artitec', 'ARTITEC', NULL, 'http://www.artitec.nl', 315);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Auhagen', 'AUHAGEN', NULL, 'https://auhagen.de/', 316);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, STRINGDECODE('Bochmann und Kochend\\u00f6rfer'), 'BK', NULL, NULL, 317);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Brawa', 'BRAWA', NULL, 'https://www.brawa.de/', 318);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Busch Model', 'BUSCH', NULL, 'https://www.busch-model.info/', 319);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'DCC Supplies', 'DCC', NULL, 'https://www.dccsupplies.com/', 320);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Deluxe Materials', 'DELUXE', NULL, 'https://deluxematerials.co.uk/', 321);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Digital-Bahn', 'DIGITALBAHN', NULL, 'https://www.digital-bahn.de/', 322);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'DIGITRAINS Ltd', 'DIGITRAINS', NULL, 'https://www.digitrains.co.uk/', 323);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Diotec Semiconductor AG', 'DIOTEC', NULL, 'https://diotec.com/en/home.html', 324);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Erbert Signale', 'ERBERT', NULL, 'http://www.erbert-signale.de/', 325);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Electronic Solutions Ulm', 'ESU', NULL, 'http://www.esu.eu/', 326);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Evergreen Scale Models', 'EVERGREEN', NULL, 'https://evergreenscalemodels.com/', 327);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Fairchild Semiconductors', 'FAIRCHILD', NULL, NULL, 328);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Faller', 'FALLER', NULL, 'https://www.faller.de/', 329);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Fleischmann', 'FLEISCHMANN', NULL, 'https://www.fleischmann.de/', 330);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, STRINGDECODE('Ga\\u00dfner Beschriftungen'), 'GASSNER', NULL, 'https://www.gassner-beschriftungen.de/', 331);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Gauge Master', 'GAUGEMASTER', NULL, 'http://www.gaugemaster.com/index.html', 332);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Heico Modell', 'HEICO', NULL, 'http://www.heico-modell.de/', 333);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Herkat', 'HERKAT', NULL, 'http://www.herkat.de/', 334);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Herpa', 'HERPA', NULL, 'https://www.herpa.de/', 335);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Humbrol', 'HUMBROL', NULL, 'https://www.humbrol.com/uk-en/', 336);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Jordan Modellbau', 'JORDAN', NULL, 'http://www.jordan-modellbau.de/', 337);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Kibri', 'KIBRI', NULL, 'https://viessmann-modell.com/', 338);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Kingbright', 'KINGBRIGHT', NULL, 'https://kingbright-europe.de/', 339);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'KK Produkcja', 'KKPMO', NULL, 'http://www.kkpmo.com/', 340);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'KNIPEX', 'KNIPEX', NULL, 'https://www.knipex.com/nc/en/home/', 341);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, STRINGDECODE('K\\u00fchn Digital'), 'KUHN', NULL, 'http://www.kuehn-digital.de/', 342);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Liliput', 'LILIPUT', NULL, 'http://liliput.de/', 343);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Lima', 'LIMA', NULL, 'https://www.hornby.com/', 344);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Littfinski Daten Technik', 'LDT', NULL, 'https://www.ldt-infocenter.com/', 345);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'LUX-Modellbau', 'LUX', NULL, 'https://www.lux-modellbau.de/', 346);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Maquett', 'MAQUETT', NULL, 'https://www.maquett.nl/', 347);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, STRINGDECODE('M\\u00e4rklin'), 'MARKLIN', '+49 (0) 71 61 608-0', 'https://www.maerklin.de/', 348);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Mehano', 'MEHANO', NULL, 'http://www.mehano.si/', 349);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Merten', 'MERTEN', NULL, 'https://www.preiser.de/', 350);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Noch', 'NOCH', NULL, 'https://www.noch.de/', 351);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Omron', 'OMRON', NULL, 'https://www.omron.com/', 352);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'POLA', 'POLA', NULL, 'https://www.faller.de/', 353);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Preiser', 'PREISER', NULL, 'https://www.preiser.de/', 354);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Proses', 'PROSES', NULL, 'https://proses.com/prestashop/', 355);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Ratio', 'RATIO', NULL, 'https://peco-uk.com/pages/ratio', 356);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Red Line', 'REDLINE', NULL, 'http://www.redline.com/', 357);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Revell', 'REVELL', NULL, 'https://www.revell.de/', 358);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Rivarossi', 'RIVAROSSI', NULL, 'https://www.hornby.com/uk-en/shop/brands/rivarossi-h0-1-87.html', 359);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Roco', 'ROCO', NULL, 'https://www.roco.cc/en/home/index.html', 360);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Schuco', 'SCHUCO', NULL, 'https://www.schuco.de/', 361);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Seuthe Dampf', 'SEUTHE', NULL, 'http://seuthe-dampf.de/', 362);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Taiwan Semiconductor', 'TAIWAN', NULL, NULL, 363);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Tamiya', 'TAMIYA', NULL, 'https://tamiya.com', 364);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Tams Elektronik', 'TAMS', NULL, 'https://tams-online.de/de_DE', 365);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Tower Pro', 'TOWERPRO', NULL, 'http://www.towerpro.com.tw/', 366);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Trix', 'TRIX', '+49 (0) 71 61 608-0', 'https://www.trix.de/', 367);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'TruOpto', 'TRUOPTO', NULL, 'https://www.rapidonline.com/brands/truopto', 368);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Uhlenbrock', 'UHLENBROCK', NULL, 'https://www.uhlenbrock.de/', 369);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, '', 'UNBEKANT', NULL, NULL, 370);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Viessmann Modell', 'VIESSMANN', NULL, 'https://viessmann-modell.com/', 371);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Walthers', 'WALTHERS', NULL, 'https://www.faller.de/', 372);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Weinert Modellbau', 'WEINERT', NULL, 'https://weinert-modellbau.de/', 373);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Wiking', 'WIKING', NULL, 'https://wiking.de/', 374);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Woodland Scenics', 'WOODLAND', NULL, 'https://woodlandscenics.woodlandscenics.com/', 375);
INSERT INTO hersteller (deleted, bezeichnung, name, telefon, url, id) VALUES (FALSE, 'Zimo', 'ZIMO', NULL, 'http://www.zimo.at', 376);