INSERT INTO vorbild (deleted, name, abbildung, achsfolg_id, anfahrzugkraft, antrieb_id, menge, aufbau, ausserdienst, bahnverwaltung_id, bauzeit, betreibsnummer, bezeichnung, dienstgewicht, dm_laufrad_hinten, dm_laufrad_vorn, dm_Treibrad, dm_Zylinder, drehgestell_bauart, fahrmotoren, gattung_id, geschwindigkeit, hersteller, kapazitat, kesseluberdruck, klasse, kolbenhub, lange, leistung, leistungsubertragung, mittelwagen, motorbauart, reichweite, rostflache, sitzplatze_kl1, sitzplatze_kl2, sitzplatze_kl3, sitzplatze_kl4, triebkopf, uberhitzerflache, unter_kategorie_id, verdampfung, wasservorrat, zylinder, id) VALUES (FALSE, 'BI', 'static/data/vorbild/BI/abbildung.jpg', 23, NULL, NULL, 10, NULL, DATE '1962-01-01', 72, DATE '1904-01-01', 'BI', 'BI', 13.1, NULL, NULL, NULL, NULL, NULL, NULL, 253, 80, 'Bautzen', NULL, NULL, 1, NULL, 11.2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 44, NULL, NULL, NULL, NULL, 644, NULL, NULL, NULL, 1376);
ALTER TABLE vorbild ALTER COLUMN id RESTART WITH 1377;
INSERT INTO produkt (deleted, abbildung, achsfolg_id, anleitungen, anmerkung, aufbau_id, bahnverwaltung_id, bauzeit, bestell_nr, betreibsnummer, bezeichnung, epoch_id, explosionszeichnung, gattung_id, hersteller_id, kupplung_id, lange, licht_id, massstab_id, motor_typ_id, sondermodell_id, spurweite_id, steuerung_id, unter_kategorie_id, vorbild_id, grossansicht, id)
VALUES (FALSE, 'static/data/produkt/MARKLIN/4007/abbildung.jpg', 29, NULL, NULL, 38, 72, DATE '1907-01-01', '4007', '29 758 Stg', 'BI', 196, NULL, 253, 348, 378, 11.0, NULL, 412, NULL, NULL, 497, NULL, 644, 1376, 'static/data/produkt/MARKLIN/4007/grossansicht.jpg', 1418);
ALTER TABLE produkt ALTER COLUMN id RESTART WITH 1419;
INSERT INTO artikel (deleted, abbildung, grossansicht, anmerkung, artikel_id, beladung, bezeichnung, kaufdatum, kupplung_id, licht_id, motor_typ_id, preis, produkt_id, status, steuerung_id, menge, verbleibende, wahrung, id)
VALUES (FALSE, NULL, NULL, NULL, '00002W', NULL, 'BI', DATE '2005-03-24', 378, NULL, NULL, 30.0, 1418, 'GEKAUFT', 508, 1, 1, 'EUR', 1419);
INSERT INTO artikel (deleted, abbildung, grossansicht, anmerkung, artikel_id, beladung, bezeichnung, kaufdatum, kupplung_id, licht_id, motor_typ_id, preis, produkt_id, status, steuerung_id, menge, verbleibende, wahrung, id)
VALUES (FALSE, NULL, NULL, NULL, '00003', NULL, 'BI', DATE '2005-03-24', 378, NULL, NULL, 40.0, 1418, 'GEKAUFT', 508, 1, 1, 'EUR', 1420);
INSERT INTO artikel (deleted, abbildung, grossansicht, anmerkung, artikel_id, beladung, bezeichnung, kaufdatum, kupplung_id, licht_id, motor_typ_id, preis, produkt_id, status, steuerung_id, menge, verbleibende, wahrung, id)
VALUES (FALSE, NULL, NULL, NULL, '00004', NULL, 'BI', DATE '2005-03-24', 378, NULL, NULL, 20.0, 1418, 'GEKAUFT', NULL, 1, 1, 'EUR', 1421);
ALTER TABLE artikel ALTER COLUMN id RESTART WITH 1422;