
---------- DATA.SQL
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 351};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 352};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 353};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 354};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 355};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 356};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 357};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell der Lok aus Metall', 3: 'LK', 4: NULL, 5: 34};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und vorwiegender Aufbau der Loks aus Metall', 3: 'LMK', 4: NULL, 5: 35};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau der Lokomotive aus Metall', 3: 'LM', 4: NULL, 5: 36};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell des Wagens aus Metall', 3: 'WK', 4: NULL, 5: 37};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Wagenaufbaus aus Metall'), 3: 'WMK', 4: NULL, 5: 38};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: 'Fahrgestell und Aufbau des Wagens aus Metall', 3: 'WM', 4: NULL, 5: 39};
/*SQL l:85 #:1*/insert into aufbau (deleted, bezeichnung, name, abbildung, id) values (?, ?, ?, ?, ?) {1: FALSE, 2: STRINGDECODE('\\u00dcberwiegender Teil des Lokaufbaues aus Metall'), 3: 'LKM', 4: NULL, 5: 40};
